// ⟪AUTO-HEADER-START⟫ generated by scripts/extract.mjs + gen-imports.mjs — do not edit this region by hand
import React from 'react';
// ⟪AUTO-HEADER-END⟫
const Icon = ({ name, size = 16, className = '' }) => {
  const paths = ICON_PATHS[name];
  if (!paths) return null;
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" className={`lucide ${className}`} dangerouslySetInnerHTML={{ __html: paths }} />
  );
};

const ICON_PATHS = {
  home:        '<path d="M3 9.5L12 3l9 6.5V20a1 1 0 0 1-1 1h-5v-6h-6v6H4a1 1 0 0 1-1-1V9.5Z"/>',
  inbox:       '<path d="M22 12h-6l-2 3h-4l-2-3H2"/><path d="M5.45 5.11L2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11Z"/>',
  send:        '<path d="m22 2-7 20-4-9-9-4 20-7Z"/><path d="M22 2 11 13"/>',
  list:        '<path d="M8 6h13"/><path d="M8 12h13"/><path d="M8 18h13"/><circle cx="3.5" cy="6" r="1"/><circle cx="3.5" cy="12" r="1"/><circle cx="3.5" cy="18" r="1"/>',
  menu:        '<line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/>',
  package:     '<path d="m7.5 4.27 9 5.15"/><path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5"/><path d="M12 22V12"/>',
  repeat:      '<path d="m17 2 4 4-4 4"/><path d="M3 11v-1a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v1a4 4 0 0 1-4 4H3"/>',
  wallet:      '<path d="M21 12V7H5a2 2 0 0 1 0-4h14v4"/><path d="M3 5v14a2 2 0 0 0 2 2h16v-5"/><path d="M18 12a2 2 0 0 0 0 4h4v-4Z"/>',
  upload:      '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/>',
  download:    '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>',
  cloud:       '<path d="M18 10h-1.26A8 8 0 1 0 9 20h9a5 5 0 0 0 0-10Z"/>',
  bar:         '<line x1="12" y1="20" x2="12" y2="10"/><line x1="18" y1="20" x2="18" y2="4"/><line x1="6" y1="20" x2="6" y2="16"/>',
  shield:      '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/>',
  qr:          '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><path d="M14 14h3v3h-3z"/><path d="M20 14h1"/><path d="M14 20v1"/><path d="M17 17h4v4"/>',
  search:      '<circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>',
  bell:        '<path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>',
  plus:        '<line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>',
  check:       '<polyline points="20 6 9 17 4 12"/>',
  x:           '<line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>',
  chevronDown: '<polyline points="6 9 12 15 18 9"/>',
  chevronUp:   '<polyline points="18 15 12 9 6 15"/>',
  chevronRight:'<polyline points="9 6 15 12 9 18"/>',
  chevronLeft: '<polyline points="15 6 9 12 15 18"/>',
  arrowRight:  '<line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/>',
  arrowLeft:   '<line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/>',
  arrowUp:     '<line x1="12" y1="19" x2="12" y2="5"/><polyline points="5 12 12 5 19 12"/>',
  arrowDown:   '<line x1="12" y1="5" x2="12" y2="19"/><polyline points="19 12 12 19 5 12"/>',
  clock:       '<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>',
  calendar:    '<rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/>',
  filter:      '<polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/>',
  bookmark:    '<path d="m19 21-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>',
  download:    '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>',
  zap:         '<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>',
  bellOff:     '<path d="M8.7 3A6 6 0 0 1 18 8a21.3 21.3 0 0 0 .6 5"/><path d="M17 17H3s3-2 3-9a4.7 4.7 0 0 1 .3-1.7"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/><line x1="1" y1="1" x2="23" y2="23"/>',
  trophy:      '<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6"/><path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18"/><path d="M4 22h16"/><path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22"/><path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22"/><path d="M18 2H6v7a6 6 0 0 0 12 0V2Z"/>',
  user:        '<path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
  users:       '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',
  settings:    '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9 1.65 1.65 0 0 0 4.27 7.18l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1Z"/>',
  paperclip:   '<path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l9.19-9.19a4 4 0 0 1 5.66 5.66l-9.2 9.19a2 2 0 0 1-2.83-2.83l8.49-8.48"/>',
  image:       '<rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/>',
  message:     '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2Z"/>',
  more:        '<circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/>',
  trash:       '<polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"/><path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>',
  edit:        '<path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5Z"/>',
  eye:         '<path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8Z"/><circle cx="12" cy="12" r="3"/>',
  print:       '<polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="6" y="14" width="12" height="8"/>',
  warning:     '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>',
  info:        '<circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/>',
  flame:       '<path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5Z"/>',
  file:        '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><polyline points="14 2 14 8 20 8"/>',
  fileCheck:   '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><polyline points="14 2 14 8 20 8"/><polyline points="9 14 11 16 15 12"/>',
  truck:       '<path d="M5 17h-3v-11h12v11h-3"/><path d="M14 17h6v-5l-3-3h-3v8Z"/><circle cx="7.5" cy="17.5" r="2.5"/><circle cx="17.5" cy="17.5" r="2.5"/>',
  tag:         '<path d="M20.59 13.41 13.42 20.58a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82Z"/><line x1="7" y1="7" x2="7.01" y2="7"/>',
  building:    '<path d="M3 21h18"/><path d="M5 21V7l8-4v18"/><path d="M19 21V11l-6-4"/>',
  trending:    '<polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/>',
  pieChart:    '<path d="M21.21 15.89A10 10 0 1 1 8 2.83"/><path d="M22 12A10 10 0 0 0 12 2v10Z"/>',
  copy:        '<rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>',
  star:        '<polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>',
  starFill:    '<polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" fill="currentColor" stroke="currentColor"/>',
  refresh:     '<polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9A9 9 0 0 1 18.36 5.64L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/>',
  external:    '<path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/>',
  layers:      '<polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/>',
  zap:         '<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>',
  moon:        '<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79Z"/>',
  sun:         '<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',
  grid:        '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>'
};

const STATUS_LABEL = {
  draft:    { th: 'แบบร่าง',         en: 'Draft',        cls: 'badge',       dot: 'status-draft' },
  pending:  { th: 'รออนุมัติ',       en: 'Pending',      cls: 'badge-amber', dot: 'status-pending' },
  approved: { th: 'อนุมัติแล้ว',     en: 'Approved',     cls: 'badge-green', dot: 'status-approved' },
  rejected: { th: 'ปฏิเสธ',          en: 'Rejected',     cls: 'badge-red',   dot: 'status-rejected' },
  progress: { th: 'กำลังดำเนินการ', en: 'In progress',  cls: 'badge-blue',  dot: 'status-progress' },
  done:     { th: 'เสร็จสิ้น',       en: 'Done',         cls: 'badge-green', dot: 'status-done' },
  cancelled:{ th: 'ยกเลิกแล้ว',      en: 'Cancelled',    cls: 'badge',       dot: 'status-draft' },
  revision: { th: 'ตีกลับให้แก้ไข',  en: 'Returned',     cls: 'badge-amber', dot: 'status-pending' }
};

const StatusBadge = ({ status, lang = 'th' }) => {
  const s = STATUS_LABEL[status] || STATUS_LABEL.draft;
  return <span className={`badge ${s.cls}`}>{s[lang]}</span>;
};

const StatusDot = ({ status, lang = 'th' }) => {
  const s = STATUS_LABEL[status] || STATUS_LABEL.draft;
  return (
    <span className={`status ${s.dot}`}>
      <span className="dot"></span>
      {s[lang]}
    </span>
  );
};

const TYPE_LABEL = {
  event:      { th: 'การขออีเว้นท์',  en: 'Event',      icon: 'calendar', color: 'oklch(64% 0.16 25)' },
  general:    { th: 'อนุมัติทั่วไป',   en: 'General',    icon: 'fileCheck', color: 'oklch(56% 0.10 230)' },
  purchase:   { th: 'ขอซื้อ/จัดซื้อ', en: 'Purchase',   icon: 'tag',      color: 'oklch(60% 0.15 330)' },
  overtime:   { th: 'ทำงานล่วงเวลา',  en: 'Overtime',   icon: 'clock',    color: 'oklch(62% 0.14 100)' },
  leave:      { th: 'ใบลา',           en: 'Leave',      icon: 'user',     color: 'oklch(60% 0.13 165)' },
  withdrawal: { th: 'เบิกตัดขาด',    en: 'Withdrawal', icon: 'package',  color: 'oklch(70% 0.17 55)' },
  borrow:     { th: 'ยืม-คืน',        en: 'Borrow',     icon: 'repeat',   color: 'oklch(60% 0.14 240)' },
  expense:    { th: 'เบิกเงิน/IOU',   en: 'Expense',    icon: 'wallet',   color: 'oklch(58% 0.15 290)' },
  hire:       { th: 'ขอเพิ่มพนักงาน', en: 'Hire',       icon: 'users',    color: 'oklch(58% 0.16 200)' }
};

const TypeBadge = ({ type, lang = 'th' }) => {
  const t = TYPE_LABEL[type];
  if (!t) return null;
  return (
    <span className="badge badge-ghost no-dot" style={{ color: t.color, borderColor: 'currentColor', background: 'transparent' }}>
      <Icon name={t.icon} size={11} />
      {t[lang]}
    </span>
  );
};

const TypeIcon = ({ type, size = 32 }) => {
  const t = TYPE_LABEL[type];
  if (!t) return null;
  return (
    <div style={{ width: size, height: size, borderRadius: 8, background: t.color, display: 'grid', placeItems: 'center', color: 'white' }}>
      <div style={{ filter: 'brightness(2)' }}>
        <Icon name={t.icon} size={size * 0.5} />
      </div>
    </div>
  );
};

const Avatar = ({ user, size = 'md', ring = false }) => {
  if (!user) return null;
  const cls = size === 'sm' ? 'avatar avatar-sm' : size === 'lg' ? 'avatar avatar-lg' : size === 'xl' ? 'avatar avatar-xl' : 'avatar';
  const ooo = isUserOOO(user.id);
  const dotSize = size === 'sm' ? 8 : size === 'lg' ? 14 : size === 'xl' ? 16 : 10;
  return (
    <span style={{ position: 'relative', display: 'inline-block' }}>
      <span className={`${cls} avatar-ring`} title={`${user.name} · ${user.roleTh || ''}${ooo ? ' · ออกจากออฟฟิศ' : ''}`} style={{ background: user.color || 'var(--brand-soft)', color: 'oklch(25% 0.05 60)', boxShadow: ring ? '0 0 0 2px var(--surface), 0 0 0 4px var(--brand)' : 'none' }}>
        {user.initials}
      </span>
      {ooo && (
        <span title="ไม่อยู่ออฟฟิศ" style={{ position: 'absolute', bottom: -1, right: -1, width: dotSize, height: dotSize, borderRadius: '50%', background: 'var(--amber)', border: '1.5px solid var(--surface)', display: 'inline-block' }} />
      )}
    </span>
  );
};

const AvatarStack = ({ users, max = 4, size = 'sm' }) => {
  const shown = users.slice(0, max);
  const remaining = users.length - max;
  return (
    <span className="avatar-stack">
      {shown.map((u, i) => <Avatar key={i} user={u} size={size} />)}
      {remaining > 0 && (
        <span className={size === 'sm' ? 'avatar avatar-sm' : 'avatar'} style={{ background: 'var(--surface-3)', color: 'var(--ink-3)' }}>+{remaining}</span>
      )}
    </span>
  );
};

const Modal = ({ open, onClose, title, children, footer, wide = false }) => {
  React.useEffect(() => {
    if (!open) return;
    const handler = (e) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [open, onClose]);
  if (!open) return null;
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className={`modal ${wide ? 'modal-wide' : ''}`} onClick={(e) => e.stopPropagation()}>
        <div className="modal-head">
          <h3 className="modal-title">{title}</h3>
          <button className="btn btn-ghost btn-icon-only btn-sm" onClick={onClose}><Icon name="x" size={16} /></button>
        </div>
        <div className="modal-body">{children}</div>
        {footer && <div className="modal-foot">{footer}</div>}
      </div>
    </div>
  );
};

const fmtBaht = (n) => '฿' + (n || 0).toLocaleString('en-US', { minimumFractionDigits: 0 });
const fmtNum = (n) => (n || 0).toLocaleString('en-US');

const nowTh = () => { const d = new Date(); const p = (n) => String(n).padStart(2,'0'); return `${p(d.getDate())}/${p(d.getMonth()+1)}/${d.getFullYear()} ${p(d.getHours())}:${p(d.getMinutes())}`; };
const parseTh = (s) => { if (!s) return null; const m = s.match(/^(\d{2})\/(\d{2})\/(\d{4})/); if (!m) return null; return new Date(Number(m[3]), Number(m[2]) - 1, Number(m[1])); };
// parseThDT: parse "DD/MM/YYYY HH:mm" รวมเวลา (parseTh ตัดเวลาทิ้ง → SLA รายชั่วโมงเพี้ยน)
const parseThDT = (s) => {
  if (!s) return null;
  const m = String(s).match(/^(\d{2})\/(\d{2})\/(\d{4})(?:\s+(\d{2}):(\d{2}))?/);
  if (!m) return null;
  return new Date(Number(m[3]), Number(m[2]) - 1, Number(m[1]), Number(m[4] || 0), Number(m[5] || 0));
};
// 🐛FIX ID ชนกัน: เดิมใช้ length ของ array (+300/+400/+500 ฐานต่างกันแต่ทับซ้อน)
// → สร้างพร้อมกัน 2 เครื่อง หรือ clone กับ create สลับกัน ได้ ID ซ้ำ → merge ทับกัน = ข้อมูลหาย
// ตอนนี้: สแกน ID เดิมทั้งหมดของ prefix → เลขสูงสุด + 1
const mintReqId = (prefix, requests) => {
  let maxN = 299;
  (requests || []).forEach(r => {
    if (!r || !r.id) return;
    const m = String(r.id).match(new RegExp('^' + prefix + '-26-0*(\\d+)$'));
    if (m) { const n = parseInt(m[1], 10); if (!isNaN(n) && n > maxN) maxN = n; }
  });
  return `${prefix}-26-${String(maxN + 1).padStart(4, '0')}`;
};

// ===== v3.1: รายการตัวเลือก (Option Lists) — ช่องที่เคยพิมพ์เอง เปลี่ยนเป็น dropdown + เพิ่มได้ =====
// เก็บใน state.optionLists (sync ข้ามเครื่อง) · แต่ละ list มี updatedAt สำหรับ merge (ใหม่กว่าชนะทั้ง list)
const DEFAULT_OPTION_LISTS = {
  breakdown: { items: ['ค่าอาหารและเครื่องดื่ม','ค่าเดินทาง','ค่าที่พัก','ค่าสถานที่','ค่าวัสดุอุปกรณ์','ค่าตกแต่งบูธ','ค่าจ้างบุคคลภายนอก','ค่าของที่ระลึก','ค่าขนส่ง','ค่าโฆษณา/สื่อ'], updatedAt: 0 },
  venue:     { items: ['สำนักงานใหญ่','ไบเทค บางนา','อิมแพ็ค เมืองทองธานี','ศูนย์การประชุมแห่งชาติสิริกิติ์','โรงแรมเซ็นทารา แกรนด์','พารากอน ฮอลล์'], updatedAt: 0 },
  receipt:   { items: ['ค่าอาหารกลางวัน','ค่าอาหารเย็น','ค่าน้ำมัน','ค่าทางด่วน','ค่าที่พัก','ค่าแท็กซี่/เดินทาง','ค่าวัสดุอุปกรณ์','ค่าถ่ายเอกสาร'], updatedAt: 0 },
  hireRole:  { items: ['พนักงานขาย','พนักงานอีเว้นท์','พนักงานคลังสินค้า','เจ้าหน้าที่บัญชี','เจ้าหน้าที่การตลาด','เจ้าหน้าที่จัดซื้อ','หัวหน้าทีมขาย','ผู้ช่วยผู้จัดการ'], updatedAt: 0 },
  hireTeam:  { items: ['T1','T2','T3','T4','T5'], updatedAt: 0 },
};
const OPTION_LIST_META = {
  breakdown: { th: 'รายการงบประมาณ / ค่าใช้จ่าย', desc: 'ใช้ในฟอร์ม เบิกตัดขาด · อีเว้นท์ · จัดซื้อ', icon: 'wallet' },
  venue:     { th: 'สถานที่จัดงาน', desc: 'ใช้ในฟอร์มอีเว้นท์', icon: 'building' },
  receipt:   { th: 'ชื่อใบเสร็จ (เคลียร์เอกสาร)', desc: 'ใช้ตอนยื่นเคลียร์เอกสาร', icon: 'fileCheck' },
  hireRole:  { th: 'ตำแหน่งงาน (จ้างพนักงาน)', desc: 'ใช้ในคำขอจ้างพนักงาน', icon: 'user' },
  hireTeam:  { th: 'ทีม (จ้างพนักงาน)', desc: 'ใช้ในคำขอจ้างพนักงาน', icon: 'users' },
};
const getOptionItems = (state, key) => {
  const l = state && state.optionLists && state.optionLists[key];
  if (l && Array.isArray(l.items)) return l.items;
  return (DEFAULT_OPTION_LISTS[key] && DEFAULT_OPTION_LISTS[key].items) || [];
};
const addOptionItem = (state, setState, key, val) => {
  const v = String(val || '').trim();
  const cur = getOptionItems(state, key);
  if (!v || cur.includes(v)) return;
  const lists = { ...(state.optionLists || {}) };
  lists[key] = { items: [...cur, v], updatedAt: Date.now() };
  setState({ optionLists: lists });
};
// merge ต่อ list: updatedAt ใหม่กว่าชนะ (แบบเดียวกับ users)
const mergeOptionLists = (local, remote) => {
  const out = { ...(local || {}) };
  Object.entries(remote || {}).forEach(([k, v]) => {
    if (!v || !Array.isArray(v.items)) return;
    const loc = out[k];
    if (!loc || !Array.isArray(loc.items)) { out[k] = v; return; }
    out[k] = (v.updatedAt || 0) >= (loc.updatedAt || 0) ? v : loc;
  });
  return out;
};
// v3.3: SearchSelect — dropdown ที่พิมพ์ค้นหาได้ (ใช้กับลูกค้า/บูธ)
const SearchSelect = ({ value, onChange, items = [], placeholder = '-- เลือก --', height = 38, emptyText = 'ไม่พบรายการ' }) => {
  const [open, setOpen] = React.useState(false);
  const [q, setQ] = React.useState('');
  const wrapRef = React.useRef(null);
  React.useEffect(() => {
    const h = (e) => { if (wrapRef.current && !wrapRef.current.contains(e.target)) setOpen(false); };
    document.addEventListener('mousedown', h);
    return () => document.removeEventListener('mousedown', h);
  }, []);
  const sel = items.find(it => it.id === value);
  const ql = q.trim().toLowerCase();
  const filtered = ql ? items.filter(it => `${it.name} ${it.sub || ''} ${it.id}`.toLowerCase().includes(ql)) : items;
  return (
    <div ref={wrapRef} style={{ position: 'relative' }}>
      <div className="input row gap-8" onClick={() => setOpen(o => !o)} style={{ height, cursor: 'pointer', alignItems: 'center', userSelect: 'none' }}>
        {sel ? <span className="text-sm" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{sel.name}{sel.sub ? <span className="muted text-xs"> · {sel.sub}</span> : null}</span> : <span className="text-sm muted">{placeholder}</span>}
        <Icon name="chevronRight" size={11} style={{ marginLeft: 'auto', flexShrink: 0, transform: open ? 'rotate(-90deg)' : 'rotate(90deg)', transition: 'transform 0.15s' }} />
      </div>
      {open && (
        <div style={{ position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 60, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, boxShadow: '0 8px 24px rgba(0,0,0,0.18)', marginTop: 4, maxHeight: 280, overflow: 'auto' }}>
          <div style={{ padding: 8, position: 'sticky', top: 0, background: 'var(--surface)', borderBottom: '1px solid var(--border)' }}>
            <input className="input" style={{ height: 32 }} autoFocus placeholder="พิมพ์ค้นหา..." value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => { if (e.key === 'Escape') { setOpen(false); setQ(''); } }} />
          </div>
          {filtered.map(it => (
            <div key={it.id} onClick={() => { onChange(it.id); setOpen(false); setQ(''); }}
              style={{ padding: '8px 12px', cursor: 'pointer', background: it.id === value ? 'var(--brand-soft)' : undefined, borderBottom: '1px solid var(--border)' }}>
              <div className="text-sm medium">{it.name}</div>
              {it.sub && <div className="text-xs muted">{it.sub}</div>}
            </div>
          ))}
          {filtered.length === 0 && <div className="text-xs muted" style={{ padding: 14, textAlign: 'center' }}>{emptyText}{ql ? ` — "${q}"` : ''}</div>}
        </div>
      )}
    </div>
  );
};
// Dropdown + "➕ เพิ่มตัวเลือกใหม่" ในตัว — ค่าเก่าที่ไม่อยู่ในรายการยังแสดงได้ (ไม่ทำข้อมูลเดิมพัง)
const OptionSelect = ({ value, onChange, options = [], onAdd, placeholder = '-- เลือก --', height = 32, allowEmpty = true, style }) => {
  const [adding, setAdding] = React.useState(false);
  const [text, setText] = React.useState('');
  const commit = () => {
    const v = text.trim();
    if (v) { if (onAdd) onAdd(v); onChange(v); }
    setAdding(false); setText('');
  };
  const cancel = () => { setAdding(false); setText(''); };
  if (adding) return (
    <div className="row gap-4" style={{ width: '100%', ...style }}>
      <input className="input" style={{ height, flex: 1, minWidth: 0 }} autoFocus value={text}
        onChange={(e) => setText(e.target.value)}
        onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); commit(); } else if (e.key === 'Escape') { e.preventDefault(); cancel(); } }}
        placeholder="พิมพ์ตัวเลือกใหม่ แล้วกด Enter..." />
      <button type="button" className="btn btn-primary btn-sm btn-icon-only" style={{ height, flexShrink: 0 }} onClick={commit} title="บันทึกเข้ารายการ"><Icon name="check" size={12} /></button>
      <button type="button" className="btn btn-outline btn-sm btn-icon-only" style={{ height, flexShrink: 0 }} onClick={cancel} title="ยกเลิก"><Icon name="x" size={12} /></button>
    </div>
  );
  const opts = (value && !options.includes(value)) ? [value, ...options] : options;
  return (
    <select className="select" style={{ height, width: '100%', ...style }} value={value || ''}
      onChange={(e) => { const v = e.target.value; if (v === '__add__') { setAdding(true); setText(''); } else onChange(v); }}>
      {allowEmpty && <option value="">{placeholder}</option>}
      {opts.map(o => <option key={o} value={o}>{o}</option>)}
      {onAdd && <option value="__add__">➕ เพิ่มตัวเลือกใหม่...</option>}
    </select>
  );
};
const fmtDateRange = (start, end) => { if (!start && !end) return '—'; if (!end || start === end) return start || end; return `${start} — ${end}`; };
const daysBetween = (start, end) => { const a = parseTh(start), b = parseTh(end); if (!a || !b) return 1; return Math.max(1, Math.round((b - a) / 86400000) + 1); };
const isValidThDate = (s) => /^\d{2}\/\d{2}\/\d{4}$/.test(s) && parseTh(s) !== null;

// ===== CSV Export Helper =====
// Generates CSV and triggers download in browser
const exportCSV = (filename, headers, rows) => {
  const escape = (v) => {
    if (v == null) return '';
    const s = String(v);
    return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
  };
  const lines = [headers.map(escape).join(',')];
  rows.forEach(row => lines.push(row.map(escape).join(',')));
  const bom = '﻿'; // UTF-8 BOM for Excel
  const csv = bom + lines.join('\n');
  try {
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    if (window.toast) window.toast(`ดาวน์โหลด ${filename} เรียบร้อย`, { level: 'success' });
    return true;
  } catch (e) {
    if (window.toast) window.toast('ส่งออก CSV ไม่สำเร็จ: ' + e.message, { level: 'error' });
    return false;
  }
};

// ===== OOO (Out of Office) — เก็บ per-user ใน localStorage =====
// Key: fd-ooo-<userId> → { active, from, to, delegate, message }
const getOOO = (userId) => {
  try {
    const raw = localStorage.getItem('fd-ooo-' + userId);
    if (!raw) return { active: false, from: '', to: '', delegate: '', message: '' };
    return JSON.parse(raw);
  } catch (e) { return { active: false, from: '', to: '', delegate: '', message: '' }; }
};
const setOOO = (userId, cfg) => {
  try { localStorage.setItem('fd-ooo-' + userId, JSON.stringify(cfg)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-ooo-changed', { detail: { userId } }));
};
const isUserOOO = (userId) => {
  const o = getOOO(userId);
  if (!o.active) return false;
  if (!o.from || !o.to) return true; // active without dates → always OOO
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const f = parseTh(o.from); const t = parseTh(o.to);
  if (!f || !t) return true;
  return today >= f && today <= t;
};
const useOOO = (userId) => {
  const [cfg, setCfg] = React.useState(() => getOOO(userId));
  React.useEffect(() => {
    const h = (e) => { if (e.detail?.userId === userId) setCfg(getOOO(userId)); };
    window.addEventListener('fd-ooo-changed', h);
    return () => window.removeEventListener('fd-ooo-changed', h);
  }, [userId]);
  return cfg;
};

// ===== Reject Reasons Preset =====
const DEFAULT_REJECT_REASONS = [
  'งบประมาณไม่เพียงพอ',
  'ข้อมูลไม่ครบถ้วน',
  'ไม่เห็นความจำเป็น',
  'ผิดขั้นตอน',
  'รอเอกสารแนบเพิ่ม',
  'ส่งให้คนอื่นพิจารณาก่อน',
  'ยังไม่ใช่ช่วงเวลาที่เหมาะสม'
];
const getRejectReasons = () => {
  try {
    const raw = JSON.parse(localStorage.getItem('fd-reject-reasons'));
    return Array.isArray(raw) && raw.length > 0 ? raw : DEFAULT_REJECT_REASONS;
  } catch (e) { return DEFAULT_REJECT_REASONS; }
};
const setRejectReasons = (list) => {
  try { localStorage.setItem('fd-reject-reasons', JSON.stringify(list)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-reject-reasons-changed'));
};
const useRejectReasons = () => {
  const [list, setList] = React.useState(getRejectReasons);
  React.useEffect(() => {
    const h = () => setList(getRejectReasons());
    window.addEventListener('fd-reject-reasons-changed', h);
    return () => window.removeEventListener('fd-reject-reasons-changed', h);
  }, []);
  return list;
};

// ===== User Templates (Save as Template) =====
const getUserTemplates = () => {
  try {
    const raw = JSON.parse(localStorage.getItem('fd-user-templates'));
    return Array.isArray(raw) ? raw : [];
  } catch (e) { return []; }
};
const setUserTemplates = (list) => {
  try { localStorage.setItem('fd-user-templates', JSON.stringify(list)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-user-templates-changed'));
};
const useUserTemplates = () => {
  const [list, setList] = React.useState(getUserTemplates);
  React.useEffect(() => {
    const h = () => setList(getUserTemplates());
    window.addEventListener('fd-user-templates-changed', h);
    return () => window.removeEventListener('fd-user-templates-changed', h);
  }, []);
  return list;
};

// ===== Default approval reasons (mirror reject reasons) =====
const DEFAULT_APPROVE_REASONS = [
  'อนุมัติตามนโยบาย',
  'งบประมาณรองรับ',
  'ตรวจสอบเรียบร้อย',
  'จำเป็นต่อการดำเนินงาน',
  'อยู่ในแผนงานประจำปี',
  'พิจารณาความเร่งด่วนแล้ว'
];
const getApproveReasons = () => {
  try {
    const raw = JSON.parse(localStorage.getItem('fd-approve-reasons'));
    return Array.isArray(raw) && raw.length > 0 ? raw : DEFAULT_APPROVE_REASONS;
  } catch (e) { return DEFAULT_APPROVE_REASONS; }
};
const setApproveReasons = (list) => {
  try { localStorage.setItem('fd-approve-reasons', JSON.stringify(list)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-approve-reasons-changed'));
};
const useApproveReasons = () => {
  const [list, setList] = React.useState(getApproveReasons);
  React.useEffect(() => {
    const h = () => setList(getApproveReasons());
    window.addEventListener('fd-approve-reasons-changed', h);
    return () => window.removeEventListener('fd-approve-reasons-changed', h);
  }, []);
  return list;
};

// ===== Snooze — ซ่อนคำขอจาก Inbox จนถึงวันที่กำหนด (per-user) =====
// Key: fd-snooze-<userId> → { reqId: ISO-timestamp-string }
const getSnoozeMap = (userId) => {
  try { return JSON.parse(localStorage.getItem('fd-snooze-' + userId)) || {}; }
  catch (e) { return {}; }
};
const setSnoozeMap = (userId, map) => {
  try { localStorage.setItem('fd-snooze-' + userId, JSON.stringify(map)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-snooze-changed', { detail: { userId } }));
};
const isSnoozedUntil = (userId, reqId) => {
  const m = getSnoozeMap(userId);
  const until = m[reqId];
  if (!until) return null;
  const d = new Date(until);
  if (d.getTime() <= Date.now()) {
    // expired → clean up
    delete m[reqId];
    setSnoozeMap(userId, m);
    return null;
  }
  return d;
};
const snoozeRequest = (userId, reqId, untilDate) => {
  const m = getSnoozeMap(userId);
  m[reqId] = untilDate.toISOString();
  setSnoozeMap(userId, m);
};
const unsnoozeRequest = (userId, reqId) => {
  const m = getSnoozeMap(userId);
  delete m[reqId];
  setSnoozeMap(userId, m);
};
const useSnoozeMap = (userId) => {
  const [map, setMap] = React.useState(() => getSnoozeMap(userId));
  React.useEffect(() => {
    const h = (e) => { if (e.detail?.userId === userId) setMap(getSnoozeMap(userId)); };
    window.addEventListener('fd-snooze-changed', h);
    return () => window.removeEventListener('fd-snooze-changed', h);
  }, [userId]);
  return map;
};

// ===== Smart due date — แนะนำตามประเภท =====
const suggestDueDate = (type) => {
  const days = { event: 21, expense: 7, purchase: 14, withdrawal: 3, borrow: 3, overtime: 1, leave: 7, general: 7, hire: 30 }[type] || 7;
  const d = new Date(); d.setDate(d.getDate() + days);
  const p = (n) => String(n).padStart(2, '0');
  return `${p(d.getDate())}/${p(d.getMonth() + 1)}/${d.getFullYear()}`;
};

// ===== Saved Inbox Views (custom filter snapshots) =====
const getInboxViews = () => {
  try { return JSON.parse(localStorage.getItem('fd-inbox-views')) || []; }
  catch (e) { return []; }
};
const setInboxViews = (list) => {
  try { localStorage.setItem('fd-inbox-views', JSON.stringify(list)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-inbox-views-changed'));
};


const usePersistedState = (key, initial) => {
  const [val, setVal] = React.useState(() => {
    try { const raw = localStorage.getItem('fd-' + key); return raw !== null ? JSON.parse(raw) : initial; } catch (e) { return initial; }
  });
  React.useEffect(() => { try { localStorage.setItem('fd-' + key, JSON.stringify(val)); } catch (e) {} }, [key, val]);
  return [val, setVal];
};

// Pinned requests — shared via localStorage + custom event
const getPinned = () => { try { return JSON.parse(localStorage.getItem('fd-pinned') || '[]'); } catch (e) { return []; } };
const togglePin = (id) => {
  const cur = getPinned();
  const next = cur.includes(id) ? cur.filter(x => x !== id) : [...cur, id];
  try { localStorage.setItem('fd-pinned', JSON.stringify(next)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-pins-changed'));
  return next;
};
const usePinned = () => {
  const [pins, setPins] = React.useState(getPinned);
  React.useEffect(() => {
    const handler = () => setPins(getPinned());
    window.addEventListener('fd-pins-changed', handler);
    return () => window.removeEventListener('fd-pins-changed', handler);
  }, []);
  return pins;
};

// approver helper — รองรับทั้ง step.userId (1 คน) และ step.userIds[] (หลายคน OR/role-any)
const canApproveStep = (step, userId) => {
  if (!step || !userId) return false;
  const ids = step.userIds || (step.userId ? [step.userId] : []);
  if (ids.includes(userId)) return true;
  // ===== OOO Auto-forward — ถ้าผู้อนุมัติคนใดคนหนึ่ง OOO และมอบหมายให้ userId นี้ → ให้สิทธิ์อนุมัติ
  for (const id of ids) {
    if (isUserOOO(id)) {
      const ooo = getOOO(id);
      if (ooo.delegate && ooo.delegate === userId) return true;
    }
  }
  return false;
};

// คืน list ของ approver ปัจจุบัน (รวม delegate ของคน OOO)
const effectiveApprovers = (step) => {
  if (!step) return [];
  const ids = step.userIds || (step.userId ? [step.userId] : []);
  const out = [];
  ids.forEach(id => {
    if (isUserOOO(id)) {
      const ooo = getOOO(id);
      if (ooo.delegate) out.push({ userId: ooo.delegate, viaOOO: id });
      else out.push({ userId: id });
    } else {
      out.push({ userId: id });
    }
  });
  return out;
};

// === SLA / Work Timing system ===
const DEFAULT_SLA = {
  approvalDays: 1,        // อนุมัติแต่ละขั้นภายใน X วัน
  workDaysFromCreate: 4,  // โหมด 1: ตั้งแต่วันขอ
  workDaysFromApprove: 3, // โหมด 2: หลังอนุมัติครบ
  workDaysFromReceive: 3, // โหมด 3: หลังกดรับเรื่อง
  deadlineMode: 'from-receive' // default mode
};
const getSLAConfig = () => {
  try {
    const raw = JSON.parse(localStorage.getItem('fd-sla-config'));
    return { ...DEFAULT_SLA, ...(raw || {}) };
  } catch (e) { return DEFAULT_SLA; }
};
const setSLAConfig = (cfg) => {
  try { localStorage.setItem('fd-sla-config', JSON.stringify(cfg)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-sla-changed'));
};
const useSLAConfig = () => {
  const [cfg, setCfg] = React.useState(getSLAConfig);
  React.useEffect(() => {
    const h = () => setCfg(getSLAConfig());
    window.addEventListener('fd-sla-changed', h);
    return () => window.removeEventListener('fd-sla-changed', h);
  }, []);
  return cfg;
};
// บวกวันทำการ (ข้ามเสาร์-อาทิตย์)
const addBusinessDays = (date, days) => {
  const d = new Date(date);
  let added = 0;
  while (added < days) {
    d.setDate(d.getDate() + 1);
    const day = d.getDay();
    if (day !== 0 && day !== 6) added++;
  }
  return d;
};
// คำนวณ approved date จาก flow (วันที่ flow ขั้นสุดท้าย approved)
const getApprovedAt = (req) => {
  if (req.status !== 'progress' && req.status !== 'done') return null;
  for (let i = req.flow.length - 1; i >= 0; i--) {
    if (req.flow[i].status === 'approved' && req.flow[i].at) return parseTh(req.flow[i].at);
  }
  return null;
};
// คำนวณ deadline ของงาน — ขึ้นกับ mode
// 🐛FIX: deadline = สิ้นวัน (23:59) — เดิมเที่ยงคืนทำให้งานเด้ง "เกินกำหนด" ตั้งแต่ 00:00 ของวันครบกำหนด
const _endOfDay = (d) => { const x = new Date(d); x.setHours(23, 59, 59, 999); return x; };
const computeWorkDeadline = (req, cfg) => {
  cfg = cfg || getSLAConfig();
  const mode = req.slaMode || cfg.deadlineMode;
  if (mode === 'from-create') {
    const d = parseTh(req.createdAt); if (!d) return null;
    return { mode, deadline: _endOfDay(addBusinessDays(d, cfg.approvalDays + cfg.workDaysFromCreate)), label: 'ตั้งแต่วันขอ' };
  }
  if (mode === 'from-approve') {
    const d = getApprovedAt(req); if (!d) return null;
    return { mode, deadline: _endOfDay(addBusinessDays(d, cfg.workDaysFromApprove)), label: 'หลังอนุมัติ' };
  }
  if (mode === 'from-receive') {
    if (!req.receivedAt) return null;
    const d = parseTh(req.receivedAt); if (!d) return null;
    return { mode, deadline: _endOfDay(addBusinessDays(d, cfg.workDaysFromReceive)), label: 'หลังรับเรื่อง' };
  }
  return null;
};
// คำนวณ SLA ของขั้นอนุมัติแต่ละขั้น
const approvalStepSLA = (req, stepIdx, cfg) => {
  cfg = cfg || getSLAConfig();
  const step = req.flow[stepIdx]; if (!step || step.status !== 'pending') return null;
  // 🐛FIX: ใช้ parseThDT (รวมเวลา) — เดิม parseTh ตัดเวลาเป็นเที่ยงคืน ทำให้ label ชั่วโมงเพี้ยน/เกินก่อนจริง
  const prevTime = stepIdx > 0 && req.flow[stepIdx - 1].at
    ? parseThDT(req.flow[stepIdx - 1].at)
    : parseThDT(req.createdAt);
  if (!prevTime) return null;
  const deadline = addBusinessDays(prevTime, cfg.approvalDays);
  const now = new Date();
  const diffMs = deadline - now;
  const hours = Math.floor(diffMs / 3600000);
  if (diffMs < 0) return { level: 'overdue', label: `เกิน ${Math.abs(Math.floor(diffMs/3600000))} ชม.`, deadline };
  if (hours < 4) return { level: 'urgent', label: `เหลือ ${hours} ชม.`, deadline };
  if (hours < 24) return { level: 'soon', label: `เหลือ ${hours} ชม.`, deadline };
  return { level: 'ok', label: `เหลือ ${Math.floor(hours/24)} วัน`, deadline };
};
// === Auto-urgent: หากกำหนดวันส่งงานเร็วกว่า SLA → บังคับ priority=high ===
// Buffer ต่อประเภท (วันทำการ): approvalDays + workDays
const URGENT_BUFFER_DEFAULT = {
  withdrawal: 2,  // 1 approve + 2 work = ต้องมีเวลาอย่างน้อย 3 วันทำการก่อนกำหนด
  borrow:     2,
  expense:    3,
  purchase:   5,
  event:      5,
  overtime:   1,
  leave:      1,
  general:    2,
  hire:       7,
};
const getUrgentBuffer = (type) => {
  try {
    const raw = JSON.parse(localStorage.getItem('fd-urgent-buffer'));
    return { ...URGENT_BUFFER_DEFAULT, ...(raw || {}) }[type] ?? 3;
  } catch (e) { return URGENT_BUFFER_DEFAULT[type] ?? 3; }
};
// คำนวณวันที่เร็วสุดที่ยังถือว่า "ปกติ" (ไม่ด่วน)
// ⚡ v3.1: ใช้สูตรโหมด 1 (นับตั้งแต่วันขอ) เสมอ = วันอนุมัติ + วันทำงาน จากตั้งค่า SLA
// (เดิมใช้ buffer รายประเภท — แทนที่ตามที่ผู้ใช้กำหนด · getUrgentBuffer คงไว้เผื่ออ้างอิง แต่ไม่ใช้แล้ว)
const earliestNormalDate = (type, fromDate) => {
  const cfg = getSLAConfig();
  const buffer = (cfg.approvalDays || 1) + (cfg.workDaysFromCreate || 4);
  return addBusinessDays(fromDate || new Date(), buffer);
};
// ตรวจว่ากำหนด dueDate (TH string DD/MM/YYYY) เร็วเกินจนต้องบังคับเป็น "ด่วน" หรือไม่
// ⚡ v3.2: เสาร์/อาทิตย์ไม่ใช่วันทำการ — ถ้ากำหนดวันตรงเสาร์/อาทิตย์ งานต้องเสร็จภายในศุกร์ก่อนหน้า
// → เลื่อนวันเทียบกลับเป็นวันทำการล่าสุดก่อนเทียบกับ SLA (ทำให้เสาร์/อาทิตย์เข้าเกณฑ์ด่วนเหมือนวันศุกร์)
const shouldAutoUrgent = (type, dueDateStr, fromDate) => {
  if (!type || !dueDateStr) return false;
  const due = parseTh(dueDateStr); if (!due) return false;
  while (due.getDay() === 0 || due.getDay() === 6) due.setDate(due.getDate() - 1);
  const safe = earliestNormalDate(type, fromDate || new Date());
  // ถ้า dueDate (วันทำการจริง) มาก่อนหรือเท่ากับวันปลอดภัย → ต้องด่วน
  return due <= safe;
};
// ⚡ v3.2: วันที่ใช้ตัดสิน "ด่วน" ตามประเภท — ประเภทที่มีวันเฉพาะต้องใช้วันนั้นก่อน form.dueDate
// (🐛FIX: เดิม form.dueDate ถูก pre-fill จาก suggestDueDate ทุกประเภท → อีเว้นท์วันเริ่มใกล้ๆ ไม่เคยขึ้นด่วน)
const urgencyDateOf = (type, form) => {
  if (type === 'event') return form.eventStartDate;
  if (type === 'borrow') return form.borrowStartDate || form.dueDate; // v3.3: ยืม-คืน ใช้วันเริ่มยืม (fallback dueDate ของเดิม)
  if (type === 'overtime') return form.otDate;
  if (type === 'leave') return form.startDate;
  if (type === 'hire') return form.hireStartDate;
  return form.dueDate;
};

// SLA ของงาน (หลังอนุมัติ)
const workDeadlineInfo = (req) => {
  const info = computeWorkDeadline(req); if (!info) return null;
  const now = new Date();
  const diffMs = info.deadline - now;
  const days = Math.ceil(diffMs / 86400000);
  if (req.status === 'done') return { level: 'done', label: 'ส่งงานแล้ว', deadline: info.deadline, mode: info.mode };
  if (diffMs < 0) return { level: 'overdue', label: `เกินกำหนด ${Math.abs(days)} วัน`, deadline: info.deadline, mode: info.mode, fmtLabel: info.label };
  if (days <= 1) return { level: 'urgent', label: 'ต้องเสร็จวันนี้/พรุ่งนี้', deadline: info.deadline, mode: info.mode, fmtLabel: info.label };
  if (days <= 3) return { level: 'soon', label: `อีก ${days} วัน`, deadline: info.deadline, mode: info.mode, fmtLabel: info.label };
  return { level: 'ok', label: `อีก ${days} วัน`, deadline: info.deadline, mode: info.mode, fmtLabel: info.label };
};
// ===== แผนกที่จะ "รับเรื่อง" ตาม type — แก้ได้ใน Settings =====
const DEFAULT_RECEIVE_DEPT = {
  borrow: 'warehouse',
  withdrawal: 'warehouse',
  expense: 'accounting',
  purchase: 'procurement',
  event: 'marketing',
  overtime: 'hr',
  leave: 'hr',
  hire: 'hr',
  general: 'requester' // special: ตามแผนกของผู้ขอ
};
const getReceiveDeptConfig = () => {
  try {
    const raw = JSON.parse(localStorage.getItem('fd-receive-dept-config'));
    return { ...DEFAULT_RECEIVE_DEPT, ...(raw || {}) };
  } catch (e) { return DEFAULT_RECEIVE_DEPT; }
};
const setReceiveDeptConfig = (cfg) => {
  try { localStorage.setItem('fd-receive-dept-config', JSON.stringify(cfg)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-receive-dept-changed'));
};
const useReceiveDeptConfig = () => {
  const [cfg, setCfg] = React.useState(getReceiveDeptConfig);
  React.useEffect(() => {
    const h = () => setCfg(getReceiveDeptConfig());
    window.addEventListener('fd-receive-dept-changed', h);
    return () => window.removeEventListener('fd-receive-dept-changed', h);
  }, []);
  return cfg;
};
// แผนกที่จะรับเรื่องสำหรับ request ใดๆ — return deptKey หรือ 'requester'
const getReceiveDeptForReq = (req, users) => {
  const cfg = getReceiveDeptConfig();
  const target = cfg[req.type] || 'requester';
  if (target === 'requester') return users[req.requester]?.deptKey;
  return target;
};

// ตรวจว่าใครสามารถ "รับเรื่อง" ได้ — ต้องเป็นคนในแผนกที่รับผิดชอบประเภทนั้น
// (ผู้ขอจะเห็นเฉพาะกรณี general ที่ระบุ 'requester' เพราะแผนกของผู้ขอเป็น target อยู่แล้ว)
const canReceiveRequest = (req, currentUser, users) => {
  if (!currentUser || !req) return false;
  if (req.status !== 'progress') return false;
  if (req.receivedAt) return false;
  const targetDept = getReceiveDeptForReq(req, users);
  return currentUser.deptKey === targetDept;
};
// ตรวจว่าใครส่งงานได้
const canCompleteRequest = (req, currentUser, users) => {
  if (!currentUser || !req) return false;
  if (req.status !== 'progress') return false;
  if (!req.receivedAt) return false;
  // ผู้รับเรื่องเอง หรือคนในแผนกที่รับ
  if (req.receivedBy === currentUser.id) return true;
  const targetDept = getReceiveDeptForReq(req, users);
  return currentUser.deptKey === targetDept;
};
// ===== Visibility System — ใครเห็นคำขอประเภทไหน (แก้ได้ใน Settings) =====
// 5 mode: public | self | involved | sameDept | adminOnly
const VISIBILITY_MODES = {
  public:    { th: 'ทุกคน',                                icon: '🌐', desc: 'ใครก็เห็นได้' },
  self:      { th: 'เฉพาะของตัวเอง',                       icon: '👤', desc: 'แค่ผู้ขอเท่านั้น' },
  involved:  { th: 'ตัวเอง + ผู้อนุมัติ + ผู้รับเรื่อง',     icon: '👥', desc: 'คนที่เกี่ยวข้องกับคำขอ' },
  sameDept:  { th: 'เฉพาะแผนกของผู้ขอ',                  icon: '🏢', desc: 'คนในแผนกเดียวกับผู้ขอ' },
  depts:     { th: 'เลือกแผนกเอง',                         icon: '🏬', desc: 'ผู้เกี่ยวข้อง + แผนกที่ติ๊กเลือก' },
  adminOnly: { th: 'แอดมินเท่านั้น',                       icon: '🔒', desc: 'เฉพาะผู้ดูแลระบบ' }
};
// v3.3: config ต่อประเภทเป็นได้ทั้ง string (โหมดเดิม) หรือ { mode:'depts', depts:[...] }
const visModeOf = (val) => (val && typeof val === 'object') ? (val.mode || 'involved') : (val || 'involved');
const visDeptsOf = (val) => (val && typeof val === 'object' && Array.isArray(val.depts)) ? val.depts : [];
const DEFAULT_VISIBILITY = {
  event: 'public',      // งานอีเว้นท์ — ทุกคนเห็น
  expense: 'involved',
  purchase: 'involved',
  overtime: 'involved',
  leave: 'involved',
  hire: 'involved',
  withdrawal: 'involved',
  borrow: 'involved',
  general: 'sameDept'
};
const getVisibilityConfig = () => {
  try {
    const raw = JSON.parse(localStorage.getItem('fd-visibility-config'));
    return { ...DEFAULT_VISIBILITY, ...(raw || {}) };
  } catch (e) { return DEFAULT_VISIBILITY; }
};
const setVisibilityConfig = (cfg) => {
  try { localStorage.setItem('fd-visibility-config', JSON.stringify(cfg)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-visibility-changed'));
};
const useVisibilityConfig = () => {
  const [cfg, setCfg] = React.useState(getVisibilityConfig);
  React.useEffect(() => {
    const h = () => setCfg(getVisibilityConfig());
    window.addEventListener('fd-visibility-changed', h);
    return () => window.removeEventListener('fd-visibility-changed', h);
  }, []);
  return cfg;
};
// helper หลัก — ตรวจว่า user เห็นคำขอนี้มั้ย
const canViewRequest = (req, currentUser, users) => {
  if (!currentUser || !req) return false;
  const cfg = getVisibilityConfig();
  const rawVal = cfg[req.type] || 'involved';
  const mode = visModeOf(rawVal);
  // Admin เห็นได้หมด (ทุก mode)
  const perms = getPermissions ? getPermissions(currentUser) : { isAdmin: false };
  if (perms.isAdmin) return true;
  // ผู้เกี่ยวข้องโดยตรง — เห็นเสมอ (ไม่งั้นงานเดินไม่ได้)
  const isInvolved = () => {
    if (req.requester === currentUser.id) return true;
    // event staff — คนที่ไปร่วมงาน
    if (req.eventStaff && req.eventStaff.includes(currentUser.id)) return true;
    // ผู้อนุมัติในขั้นใดก็ตาม
    if (req.flow && req.flow.some(s => canApproveStep(s, currentUser.id))) return true;
    // ผู้รับเรื่อง / คนในแผนกที่รับเรื่อง
    if (req.receivedBy === currentUser.id) return true;
    const receiveDept = getReceiveDeptForReq(req, users);
    if (currentUser.deptKey === receiveDept) return true;
    // watcher
    if ((req.watchers || []).includes(currentUser.id)) return true;
    return false;
  };
  switch (mode) {
    case 'public': return true;
    case 'self': return req.requester === currentUser.id;
    case 'adminOnly': return perms.isAdmin === true;
    case 'sameDept': {
      const reqDept = users[req.requester]?.deptKey;
      return reqDept === currentUser.deptKey;
    }
    // v3.3: เลือกแผนกเอง — แผนกที่ติ๊ก + ผู้เกี่ยวข้องโดยตรง
    case 'depts': {
      if (visDeptsOf(rawVal).includes(currentUser.deptKey)) return true;
      return isInvolved();
    }
    case 'involved':
    default: return isInvolved();
  }
};

// ตรวจว่าใครเห็นรายการเคลียร์เอกสาร (expense) บ้าง
// คนในแผนก accounting + คนในแผนกที่รับเรื่อง (จาก config) + ผู้ขอเอง
const canViewClearingItem = (req, currentUser, users) => {
  if (!currentUser || !req) return false;
  if (req.requester === currentUser.id) return true;
  if (currentUser.deptKey === 'accounting') return true; // บัญชีเห็นเคลียร์ทุกอย่าง
  const targetDept = getReceiveDeptForReq(req, users);
  return currentUser.deptKey === targetDept;
};

// ===== Password + Permission system =====
// hash function ง่ายๆ (ไม่ใช่ crypto-grade — ใช้แค่ obfuscate ใน localStorage)
const hashPassword = (pwd) => {
  if (!pwd) return '';
  let h = 5381;
  for (let i = 0; i < pwd.length; i++) h = ((h << 5) + h) ^ pwd.charCodeAt(i);
  return 'fdh:' + Math.abs(h).toString(36) + ':' + pwd.length;
};
const verifyPassword = (pwd, hash) => hashPassword(pwd) === hash;

// Permission ของ user ขึ้นกับ level + deptKey (ค่าเริ่มต้นตามตำแหน่ง)
const getPermissionsBase = (user) => {
  if (!user) return { canViewAny: false };
  const lvl = user.level;
  const dept = user.deptKey;
  const isAcc = dept === 'accounting';
  const isHR = dept === 'hr';
  const isAdmin = dept === 'accounting' && lvl === 'director'; // ACC-004 default admin
  const isOps = dept === 'warehouse' || dept === 'accounting';
  return {
    // ทุกคนเห็น
    canDashboard: true,
    canInbox: true,
    canMyRequests: true,
    canCalendar: true,
    canTemplates: true,
    canRecurring: true,
    canScorecard: true,
    canInsights: true,
    canCreateRequest: true,

    // ต้องเป็น head ขึ้นไป
    canApprove: lvl === 'head' || lvl === 'manager' || lvl === 'director',
    canViewApprovalsPage: lvl === 'head' || lvl === 'manager' || lvl === 'director',

    // ทุกแผนกอาจมีงานต้องรับเรื่อง (ขึ้นกับ DEFAULT_RECEIVE_DEPT mapping)
    canViewIntake: true,
    canViewClearing: true, // ทุกคนเห็นของตัวเอง — accounting เห็นทั้งหมด

    // รายงาน — manager ขึ้นไป
    canViewExecReport: lvl === 'manager' || lvl === 'director' || isAdmin,
    canViewStockReport: isOps || lvl === 'manager' || lvl === 'director',

    // ข้อมูลหลัก — admin/director เท่านั้น
    canViewMaster: isAdmin || (lvl === 'director' && (isAcc || isHR)),
    canEditMaster: isAdmin,

    // Audit Log — admin/director ของ accounting
    canViewAudit: isAdmin || (lvl === 'director' && (isAcc || isHR)),

    // Settings: ทุกคนเข้าได้ แต่บางแท็บจำกัด
    canViewSettings: true,
    canEditTeam: isAdmin || (isHR && (lvl === 'manager' || lvl === 'director')),
    canEditWorkflow: isAdmin,
    canEditSLA: isAdmin,
    canViewSync: true, // ทุกคน setup cloud sync ของตัวเอง

    // Actions
    canViewAny: true,
    canCancelOwn: true,
    canDelegate: lvl === 'head' || lvl === 'manager' || lvl === 'director',
    isAdmin
  };
};
// v3.3: สิทธิ์รายคน — ค่าเริ่มต้นจากตำแหน่ง (getPermissionsBase) + override ต่อ user (ติ๊กใน Settings)
// เก็บใน user.permOverrides = { key: true/false } → sync ข้ามเครื่องพร้อม users
const getPermissions = (user) => {
  const base = getPermissionsBase(user);
  if (!user || !user.permOverrides) return base;
  const merged = { ...base };
  Object.entries(user.permOverrides).forEach(([k, v]) => { if (typeof v === 'boolean' && k in base) merged[k] = v; });
  return merged;
};

const slaInfo = (dueDate) => {
  const d = parseTh(dueDate); if (!d) return null;
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const diff = Math.round((d - today) / 86400000);
  if (diff < 0) return { days: -diff, level: 'overdue', label: `เกิน ${-diff} วัน`, color: 'var(--red-ink)', bg: 'var(--red-soft)' };
  if (diff === 0) return { days: 0, level: 'today', label: 'วันนี้', color: 'var(--red-ink)', bg: 'var(--red-soft)' };
  if (diff <= 3) return { days: diff, level: 'urgent', label: `อีก ${diff} วัน`, color: 'var(--amber-ink)', bg: 'var(--amber-soft)' };
  if (diff <= 7) return { days: diff, level: 'soon', label: `อีก ${diff} วัน`, color: 'var(--ink-2)', bg: 'var(--surface-3)' };
  return { days: diff, level: 'normal', label: `อีก ${diff} วัน`, color: 'var(--ink-3)', bg: 'transparent' };
};

const SLABadge = ({ dueDate, compact = false }) => {
  const info = slaInfo(dueDate); if (!info) return null;
  const dot = info.level === 'overdue' || info.level === 'today' ? <Icon name="warning" size={10} /> : info.level === 'urgent' ? <Icon name="clock" size={10} /> : null;
  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center', gap: 4,
      padding: compact ? '1px 6px' : '2px 8px',
      borderRadius: 100, fontSize: compact ? 10 : 11,
      fontWeight: 600, color: info.color, background: info.bg,
      border: info.bg === 'transparent' ? '1px solid var(--border)' : 'none', whiteSpace: 'nowrap'
    }}>{dot}{info.label}</span>
  );
};

const downloadCSV = (filename, rows) => {
  if (!rows || !rows.length) return;
  const esc = (v) => { if (v == null) return ''; const s = String(v); return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; };
  const csv = rows.map(r => r.map(esc).join(',')).join('\r\n');
  const blob = new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename; document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
};

const ValidationError = ({ msg }) => msg ? <div className="text-xs mt-4" style={{ color: 'var(--red-ink)' }}><Icon name="warning" size={10} /> {msg}</div> : null;

// Global toast notification system — emit anywhere via window.toast
window.__toastListeners = window.__toastListeners || [];
window.toast = (msg, opts = {}) => {
  const t = { id: Math.random().toString(36).slice(2), msg, level: opts.level || 'info', action: opts.action, duration: opts.duration || 3500, at: Date.now() };
  window.__toastListeners.forEach(fn => fn(t));
  return t.id;
};

const ToastHost = () => {
  const [toasts, setToasts] = React.useState([]);
  React.useEffect(() => {
    const handler = (t) => {
      setToasts(prev => [...prev, t]);
      setTimeout(() => setToasts(prev => prev.filter(x => x.id !== t.id)), t.duration);
    };
    window.__toastListeners.push(handler);
    return () => { window.__toastListeners = window.__toastListeners.filter(f => f !== handler); };
  }, []);
  const dismiss = (id) => setToasts(prev => prev.filter(x => x.id !== id));
  const colorMap = {
    info: { bg: 'var(--blue-soft)', ink: 'var(--blue-ink)', bd: 'var(--blue)', icon: 'info' },
    success: { bg: 'var(--green-soft)', ink: 'var(--green-ink)', bd: 'var(--green)', icon: 'check' },
    warning: { bg: 'var(--amber-soft)', ink: 'var(--amber-ink)', bd: 'var(--amber)', icon: 'warning' },
    error: { bg: 'var(--red-soft)', ink: 'var(--red-ink)', bd: 'var(--red)', icon: 'x' }
  };
  return (
    <div style={{ position: 'fixed', bottom: 24, right: 24, zIndex: 200, display: 'flex', flexDirection: 'column', gap: 10, maxWidth: 380, pointerEvents: 'none' }}>
      {toasts.map(t => {
        const c = colorMap[t.level] || colorMap.info;
        return (
          <div key={t.id} style={{
            background: 'var(--surface)', border: `1px solid var(--border)`, borderLeft: `4px solid ${c.bd}`,
            borderRadius: 10, boxShadow: 'var(--shadow-lg)', padding: '12px 14px',
            display: 'flex', alignItems: 'flex-start', gap: 10, pointerEvents: 'auto',
            animation: 'toastIn 0.25s ease-out'
          }}>
            <div style={{ width: 24, height: 24, borderRadius: 100, background: c.bg, color: c.ink, display: 'grid', placeItems: 'center', flexShrink: 0 }}>
              <Icon name={c.icon} size={12} />
            </div>
            <div style={{ flex: 1, minWidth: 0, fontSize: 13, lineHeight: 1.5 }}>{t.msg}</div>
            {t.action && <button className="btn btn-ghost btn-sm" onClick={() => { t.action.onClick(); dismiss(t.id); }} style={{ padding: '2px 8px', height: 24 }}>{t.action.label}</button>}
            <button onClick={() => dismiss(t.id)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-3)', padding: 0 }}><Icon name="x" size={12} /></button>
          </div>
        );
      })}
    </div>
  );
};

// === Signature system ===
const getSignature = (userId) => {
  try { return localStorage.getItem('fd-sig-' + userId) || ''; } catch (e) { return ''; }
};
const setSignature = (userId, text) => {
  try { localStorage.setItem('fd-sig-' + userId, text); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-sig-changed', { detail: { userId } }));
};
const useSignature = (userId) => {
  const [sig, setSig] = React.useState(() => getSignature(userId));
  React.useEffect(() => {
    const handler = (e) => { if (e.detail?.userId === userId) setSig(getSignature(userId)); };
    window.addEventListener('fd-sig-changed', handler);
    return () => window.removeEventListener('fd-sig-changed', handler);
  }, [userId]);
  return sig;
};
// Render สัญลักษณ์ลายเซ็น — ถ้ามี text จะแสดงด้วย script font, ถ้าไม่มีใช้ initials เป็น fallback
const SigDisplay = ({ userId, user, size = 'md' }) => {
  const sig = useSignature(userId);
  const fontSize = size === 'lg' ? 28 : size === 'md' ? 20 : 16;
  if (sig) {
    return <span style={{ fontFamily: '"Brush Script MT", "Lucida Handwriting", cursive', fontSize, color: 'var(--brand-ink)', fontStyle: 'italic', lineHeight: 1 }}>{sig}</span>;
  }
  if (user?.initials) {
    return <span style={{ fontFamily: 'var(--font-en)', fontWeight: 700, fontSize: fontSize * 0.6, color: 'var(--ink-3)', letterSpacing: '0.1em' }}>{user.initials}</span>;
  }
  return <span style={{ color: 'var(--ink-4)', fontSize: 12 }}>—</span>;
};

// === Hover tracking — สำหรับ spotlight / glow effects ===
const useMouseTrack = () => {
  const ref = React.useRef(null);
  React.useEffect(() => {
    const el = ref.current; if (!el) return;
    const onMove = (e) => {
      const r = el.getBoundingClientRect();
      el.style.setProperty('--mx', (e.clientX - r.left) + 'px');
      el.style.setProperty('--my', (e.clientY - r.top) + 'px');
    };
    const onLeave = () => {
      el.style.setProperty('--mx', '-100px');
      el.style.setProperty('--my', '-100px');
    };
    el.addEventListener('mousemove', onMove);
    el.addEventListener('mouseleave', onLeave);
    return () => { el.removeEventListener('mousemove', onMove); el.removeEventListener('mouseleave', onLeave); };
  }, []);
  return ref;
};

const Spotlight = ({ className = '', style, children, ...rest }) => {
  const ref = useMouseTrack();
  return <div ref={ref} className={`hover-spot ${className}`} style={style} {...rest}>{children}</div>;
};

const Glow = ({ className = '', style, children, ...rest }) => {
  const ref = useMouseTrack();
  return <div ref={ref} className={`hover-glow ${className}`} style={style} {...rest}>{children}</div>;
};

// Card with 3D tilt based on cursor position
const TiltCard = ({ className = '', style, children, intensity = 6, ...rest }) => {
  const ref = React.useRef(null);
  const rafRef = React.useRef(null);
  const onMove = (e) => {
    const el = ref.current; if (!el) return;
    cancelAnimationFrame(rafRef.current);
    rafRef.current = requestAnimationFrame(() => {
      const r = el.getBoundingClientRect();
      const px = (e.clientX - r.left) / r.width;
      const py = (e.clientY - r.top) / r.height;
      const rx = (py - 0.5) * -intensity;
      const ry = (px - 0.5) * intensity;
      el.style.transform = `perspective(1000px) rotateX(${rx}deg) rotateY(${ry}deg)`;
      el.style.setProperty('--mx', (e.clientX - r.left) + 'px');
      el.style.setProperty('--my', (e.clientY - r.top) + 'px');
    });
  };
  const onLeave = () => {
    cancelAnimationFrame(rafRef.current);
    const el = ref.current; if (!el) return;
    el.style.transform = '';
  };
  return <div ref={ref} className={`hover-tilt ${className}`} style={style} onMouseMove={onMove} onMouseLeave={onLeave} {...rest}>{children}</div>;
};

// Button ripple — set --rx/--ry on click
const useRipple = () => {
  const onPointerDown = (e) => {
    const el = e.currentTarget;
    const r = el.getBoundingClientRect();
    el.style.setProperty('--rx', (e.clientX - r.left) + 'px');
    el.style.setProperty('--ry', (e.clientY - r.top) + 'px');
  };
  return { onPointerDown };
};

const CountUp = ({ value, format, duration = 700, className, style }) => {
  const target = Number(value) || 0;
  const [display, setDisplay] = React.useState(0);
  const prevRef = React.useRef(0);
  React.useEffect(() => {
    const from = prevRef.current; const to = target; prevRef.current = to;
    if (from === to) { setDisplay(to); return; }
    let raf, start;
    const tick = (ts) => {
      if (!start) start = ts;
      const p = Math.min(1, (ts - start) / duration);
      const eased = 1 - Math.pow(1 - p, 3);
      setDisplay(from + (to - from) * eased);
      if (p < 1) raf = requestAnimationFrame(tick);
      else setDisplay(to);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [target, duration]);
  const rounded = Math.round(display);
  return <span className={className} style={style}>{format ? format(rounded) : rounded.toLocaleString('en-US')}</span>;
};

const Sparkline = ({ data, color = 'var(--brand)', width = 80, height = 24, fill = true }) => {
  if (!data || data.length === 0) return null;
  const max = Math.max(...data, 1);
  const min = Math.min(...data, 0);
  const range = max - min || 1;
  const pts = data.map((v, i) => [i * (width / (data.length - 1 || 1)), height - ((v - min) / range) * (height - 2) - 1]);
  const path = pts.map((p, i) => (i === 0 ? 'M' : 'L') + p[0].toFixed(1) + ' ' + p[1].toFixed(1)).join(' ');
  const area = path + ` L ${width} ${height} L 0 ${height} Z`;
  return (
    <svg width={width} height={height} style={{ display: 'block' }}>
      {fill && <path d={area} fill={color} opacity="0.15" />}
      <path d={path} fill="none" stroke={color} strokeWidth="1.5" strokeLinejoin="round" strokeLinecap="round" />
      <circle cx={pts[pts.length - 1][0]} cy={pts[pts.length - 1][1]} r="2" fill={color} />
    </svg>
  );
};

const Heatmap = ({ days = 90, getValue, color = 'oklch(60% 0.15 240)', cellSize = 11, gap = 2 }) => {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const cells = [];
  const startOffset = today.getDay();
  for (let i = 0; i < startOffset; i++) cells.push({ pad: true });
  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(today); d.setDate(d.getDate() - i);
    cells.push({ date: d, value: getValue(d) });
  }
  const max = Math.max(1, ...cells.filter(c => !c.pad).map(c => c.value || 0));
  const level = (v) => v === 0 ? 0 : v / max < 0.25 ? 1 : v / max < 0.5 ? 2 : v / max < 0.75 ? 3 : 4;
  const fillFor = (v) => v === 0 ? 'var(--surface-3)' : `color-mix(in oklch, ${color} ${20 + level(v) * 20}%, transparent)`;
  const rows = 7;
  const cols = Math.ceil(cells.length / rows);
  return (
    <div style={{ display: 'inline-grid', gridTemplateRows: `repeat(${rows}, ${cellSize}px)`, gridAutoFlow: 'column', gridAutoColumns: `${cellSize}px`, gap }}>
      {cells.map((c, i) => c.pad ? <div key={i}></div> : (
        <div key={i} title={`${c.date.toLocaleDateString('th-TH')} · ${c.value || 0}`} style={{ width: cellSize, height: cellSize, borderRadius: 2, background: fillFor(c.value || 0), cursor: 'pointer' }}></div>
      ))}
    </div>
  );
};

const thToIso = (v) => { if (!v) return ''; const m = v.match(/^(\d{2})\/(\d{2})\/(\d{4})/); return m ? `${m[3]}-${m[2]}-${m[1]}` : ''; };
const isoToTh = (v) => { if (!v) return ''; const m = v.match(/^(\d{4})-(\d{2})-(\d{2})$/); return m ? `${m[3]}/${m[2]}/${m[1]}` : ''; };
const DateInput = ({ value, onChange, min, max, className = 'input', ...rest }) => (
  <input className={className} type="date" value={thToIso(value)} min={thToIso(min)} max={thToIso(max)}
    onChange={(e) => onChange(isoToTh(e.target.value))} {...rest} />
);
const TimeInput = ({ value, onChange, className = 'input', ...rest }) => (
  <input className={className} type="time" value={value || ''} onChange={(e) => onChange(e.target.value)} {...rest} />
);

const ApprovalStepper = ({ flow, users, createdAt }) => {
  const flowStart = parseTh(createdAt);
  const computeWait = (step, i) => {
    if (step.status !== 'pending') return null;
    const prevTime = i > 0 && flow[i - 1].at ? parseTh(flow[i - 1].at) : flowStart;
    if (!prevTime) return null;
    const now = new Date();
    const days = Math.floor((now - prevTime) / 86400000);
    const hours = Math.floor(((now - prevTime) % 86400000) / 3600000);
    if (days > 0) return `รอ ${days}d ${hours}h`;
    if (hours > 0) return `รอ ${hours} ชม.`;
    return 'เพิ่งเข้าคิว';
  };
  return (
    <div>
      {flow.map((step, i) => {
        const user = users[step.userId];
        const cls = step.status;
        const isCurrent = cls === 'pending';
        const wait = computeWait(step, i);
        const isLong = wait && wait.includes('d') && parseInt(wait.match(/\d+/)?.[0]) >= 3;
        return (
          <div key={i} className={`appr-step ${cls === 'pending' ? 'current' : cls}`}>
            <div className="appr-dot" style={isCurrent && isLong ? { animation: 'pulse 1.5s infinite' } : undefined}>
              {step.status === 'approved' ? <Icon name="check" size={14} />
                : step.status === 'rejected' ? <Icon name="x" size={14} />
                : step.status === 'returned' ? <Icon name="arrowLeft" size={14} />
                : i + 1}
            </div>
            <div>
              <div className="appr-name">
                {user?.name}
                {step.userIds && step.userIds.length > 1 && (
                  <span style={{ marginLeft: 8, padding: '1px 7px', background: 'var(--brand-soft)', color: 'var(--brand-ink)', borderRadius: 100, fontSize: 10, fontWeight: 600 }}>คนใดก็ได้ ใน {step.userIds.length} คน</span>
                )}
              </div>
              <div className="appr-role">{step.role}{user?.roleTh && user.roleTh !== step.role ? ` · ${user.roleTh}` : ''}</div>
              {step.userIds && step.userIds.length > 1 && (
                <div style={{ marginTop: 4, display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                  {step.userIds.map(uid => {
                    const uu = users[uid];
                    return uu ? (
                      <span key={uid} style={{ display: 'inline-flex', alignItems: 'center', gap: 4, padding: '2px 8px 2px 2px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 100, fontSize: 11 }}>
                        <Avatar user={uu} size="sm" />
                        {uu.name.split(' ')[0]}
                      </span>
                    ) : null;
                  })}
                </div>
              )}
              {step.comment && (
                <div style={{ marginTop: 6, padding: '6px 10px', background: 'var(--red-soft)', color: 'var(--red-ink)', borderRadius: 6, fontSize: 12, borderLeft: '2px solid var(--red)' }}>
                  {step.comment}
                </div>
              )}
            </div>
            <div className="appr-meta">
              {step.at && <div>{step.at}</div>}
              {isCurrent && <div style={{ color: isLong ? 'var(--red-ink)' : 'var(--amber-ink)', fontWeight: 600 }}>{wait || 'กำลังพิจารณา'}</div>}
            </div>
          </div>
        );
      })}
    </div>
  );
};

const SplitProgress = ({ taken, sold, returned, bonus }) => {
  const remaining = taken - sold - returned - bonus;
  return (
    <div className="progress split" style={{ background: 'var(--surface-3)' }}>
      {sold > 0 && <div style={{ flex: sold, background: 'var(--green)' }} title={`ขาย ${sold}`}></div>}
      {bonus > 0 && <div style={{ flex: bonus, background: 'var(--violet)' }} title={`แถม ${bonus}`}></div>}
      {returned > 0 && <div style={{ flex: returned, background: 'var(--blue)' }} title={`คืน ${returned}`}></div>}
      {remaining > 0 && <div style={{ flex: remaining, background: 'var(--surface-3)' }} title={`คงเหลือ ${remaining}`}></div>}
    </div>
  );
};

const Empty = ({ icon = 'inbox', title, sub }) => (
  <div style={{ padding: '48px 24px', textAlign: 'center', color: 'var(--ink-3)' }}>
    <div style={{ width: 32, height: 1, background: 'var(--border)', margin: '0 auto 16px' }}></div>
    <div style={{ fontSize: 15, fontWeight: 500, color: 'var(--ink-2)', letterSpacing: '-0.005em' }}>{title}</div>
    {sub && <div style={{ fontSize: 13, marginTop: 6, color: 'var(--ink-3)', maxWidth: 320, margin: '6px auto 0' }}>{sub}</div>}
  </div>
);

Object.assign(window, {
  Icon, ICON_PATHS,
  STATUS_LABEL, StatusBadge, StatusDot,
  TYPE_LABEL, TypeBadge, TypeIcon,
  Avatar, AvatarStack, Modal,
  fmtBaht, fmtNum,
  ApprovalStepper, SplitProgress, Empty,
  usePersistedState, slaInfo, SLABadge, downloadCSV, ValidationError, canApproveStep, effectiveApprovers,
  DEFAULT_SLA, getSLAConfig, setSLAConfig, useSLAConfig, addBusinessDays,
  URGENT_BUFFER_DEFAULT, getUrgentBuffer, earliestNormalDate, shouldAutoUrgent, urgencyDateOf,
  getApprovedAt, computeWorkDeadline, approvalStepSLA, workDeadlineInfo,
  canReceiveRequest, canCompleteRequest, hashPassword, verifyPassword, getPermissions, getPermissionsBase,
  DEFAULT_RECEIVE_DEPT, getReceiveDeptConfig, setReceiveDeptConfig, useReceiveDeptConfig,
  VISIBILITY_MODES, DEFAULT_VISIBILITY, getVisibilityConfig, setVisibilityConfig, useVisibilityConfig, canViewRequest, visModeOf, visDeptsOf,
  getReceiveDeptForReq, canViewClearingItem,
  exportCSV,
  getOOO, setOOO, isUserOOO, useOOO,
  DEFAULT_REJECT_REASONS, getRejectReasons, setRejectReasons, useRejectReasons,
  DEFAULT_APPROVE_REASONS, getApproveReasons, setApproveReasons, useApproveReasons,
  getSnoozeMap, setSnoozeMap, isSnoozedUntil, snoozeRequest, unsnoozeRequest, useSnoozeMap,
  suggestDueDate,
  getUserTemplates, setUserTemplates, useUserTemplates,
  getInboxViews, setInboxViews,
  nowTh, parseTh, parseThDT, mintReqId, fmtDateRange, daysBetween, isValidThDate,
  DEFAULT_OPTION_LISTS, OPTION_LIST_META, getOptionItems, addOptionItem, mergeOptionLists, OptionSelect, SearchSelect,
  DateInput, TimeInput, thToIso, isoToTh,
  Sparkline, Heatmap, CountUp,
  useMouseTrack, Spotlight, Glow, TiltCard, useRipple,
  getPinned, togglePin, usePinned,
  getSignature, setSignature, useSignature, SigDisplay
});
// ⟪AUTO-EXPORTS-START⟫
export { Icon, ICON_PATHS, STATUS_LABEL, StatusBadge, StatusDot, TYPE_LABEL, TypeBadge, TypeIcon, Avatar, AvatarStack, Modal, fmtBaht, fmtNum, nowTh, parseTh, parseThDT, mintReqId, DEFAULT_OPTION_LISTS, OPTION_LIST_META, getOptionItems, addOptionItem, mergeOptionLists, SearchSelect, OptionSelect, fmtDateRange, daysBetween, isValidThDate, exportCSV, getOOO, setOOO, isUserOOO, useOOO, DEFAULT_REJECT_REASONS, getRejectReasons, setRejectReasons, useRejectReasons, getUserTemplates, setUserTemplates, useUserTemplates, DEFAULT_APPROVE_REASONS, getApproveReasons, setApproveReasons, useApproveReasons, getSnoozeMap, setSnoozeMap, isSnoozedUntil, snoozeRequest, unsnoozeRequest, useSnoozeMap, suggestDueDate, getInboxViews, setInboxViews, usePersistedState, getPinned, togglePin, usePinned, canApproveStep, effectiveApprovers, DEFAULT_SLA, getSLAConfig, setSLAConfig, useSLAConfig, addBusinessDays, getApprovedAt, _endOfDay, computeWorkDeadline, approvalStepSLA, URGENT_BUFFER_DEFAULT, getUrgentBuffer, earliestNormalDate, shouldAutoUrgent, urgencyDateOf, workDeadlineInfo, DEFAULT_RECEIVE_DEPT, getReceiveDeptConfig, setReceiveDeptConfig, useReceiveDeptConfig, getReceiveDeptForReq, canReceiveRequest, canCompleteRequest, VISIBILITY_MODES, visModeOf, visDeptsOf, DEFAULT_VISIBILITY, getVisibilityConfig, setVisibilityConfig, useVisibilityConfig, canViewRequest, canViewClearingItem, hashPassword, verifyPassword, getPermissionsBase, getPermissions, slaInfo, SLABadge, downloadCSV, ValidationError, ToastHost, getSignature, setSignature, useSignature, SigDisplay, useMouseTrack, Spotlight, Glow, TiltCard, useRipple, CountUp, Sparkline, Heatmap, thToIso, isoToTh, DateInput, TimeInput, ApprovalStepper, SplitProgress, Empty };
// ⟪AUTO-EXPORTS-END⟫
