// ⟪AUTO-HEADER-START⟫ generated by scripts/extract.mjs + gen-imports.mjs — do not edit this region by hand
import React from 'react';
import { parseThDT } from '../lib/core.jsx';
// ⟪AUTO-HEADER-END⟫
// ── Persistence: เก็บข้อมูลที่ผู้ใช้สร้างไว้ใน localStorage ──
// ฟิลด์ที่เก็บ: requests, activities, users, products, customers, currentUserId
// ไม่เก็บ UI state (route, modal flags) — รีเซ็ตทุกครั้ง
const PERSIST_KEY = 'fd-app-state';
// ⚠️ ห้ามใส่ currentUserId — ต้องเป็น per-device (ไม่ sync ระหว่างเครื่อง)
const PERSIST_FIELDS = ['requests','activities','users','products','customers','optionLists'];
// เก็บ currentUserId แยกใน localStorage ของแต่ละเครื่อง (ไม่ sync ขึ้น cloud)
const CURRENT_USER_KEY = 'fd-current-user';

const loadPersistedState = () => {
  try {
    const raw = localStorage.getItem(PERSIST_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    // 🐛FIX: เดิมเช็ค parsed.users[parsed.currentUserId] แต่ currentUserId ไม่เคยถูก save (per-device)
    // → เงื่อนไขเป็น false เสมอ → ข้อมูล localStorage ไม่เคยถูกโหลดกลับเลย (หายทุกครั้งที่ reload)
    if (!parsed.users || Object.keys(parsed.users).length === 0) return null;
    return parsed;
  } catch (e) { return null; }
};

// ===== Cloud Sync (kvdb.io anonymous bucket) =====
// ผู้ใช้สร้าง bucket → ได้ URL → แชร์ URL ให้คนอื่น
// ทุกคนใช้ URL เดียวกัน → sync auto ทุก 10 วินาที
const SYNC_CONFIG_KEY = 'fd-sync-config';
const getSyncConfig = () => {
  try { return JSON.parse(localStorage.getItem(SYNC_CONFIG_KEY)) || { enabled: false, bucketUrl: '', lastPushAt: 0, lastPullAt: 0, lastVersion: 0 }; }
  catch (e) { return { enabled: false, bucketUrl: '', lastPushAt: 0, lastPullAt: 0, lastVersion: 0 }; }
};
const setSyncConfig = (cfg) => {
  try { localStorage.setItem(SYNC_CONFIG_KEY, JSON.stringify(cfg)); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-sync-config-changed'));
};

// ===== Invite Link — สร้าง URL ที่ฝัง sync config ในตัว =====
// รูปแบบ: https://yoursite.com/#join=<base64url(json)>
// เมื่อเปิด URL นี้ → app auto-config + remove hash + reload
const encodeInvite = (payload) => {
  try {
    const json = JSON.stringify(payload);
    // base64url-safe encoding
    return btoa(unescape(encodeURIComponent(json))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  } catch (e) { return ''; }
};
const decodeInvite = (str) => {
  try {
    const b64 = str.replace(/-/g, '+').replace(/_/g, '/');
    const json = decodeURIComponent(escape(atob(b64)));
    return JSON.parse(json);
  } catch (e) { return null; }
};
const buildInviteUrl = (origin) => {
  const cfg = getSyncConfig();
  const fbUrl = getFirebaseUrl();
  const jbKey = getApiKey('jsonbin');
  if (!cfg.bucketUrl) return null;
  const payload = {
    v: 1,
    bucket: cfg.bucketUrl,
    fb: fbUrl || undefined,         // ส่ง Firebase URL ด้วย (สำหรับ provider firebase)
    jbk: jbKey || undefined         // ส่ง JSONBin key ด้วย (สำหรับ provider jsonbin)
  };
  const code = encodeInvite(payload);
  const base = origin || (typeof location !== 'undefined' ? `${location.origin}${location.pathname}` : '');
  return `${base}#join=${code}`;
};
// อ่าน invite จาก URL hash + apply config
const consumeInvite = () => {
  if (typeof location === 'undefined') return false;
  const m = location.hash.match(/[#&]join=([A-Za-z0-9_-]+)/);
  if (!m) return false;
  const payload = decodeInvite(m[1]);
  if (!payload || !payload.bucket) return false;
  // apply config
  if (payload.fb) setFirebaseUrl(payload.fb);
  if (payload.jbk) setApiKey('jsonbin', payload.jbk);
  const newCfg = {
    enabled: true,
    bucketUrl: payload.bucket,
    deviceId: 'dev-' + Math.random().toString(36).slice(2, 8),
    lastPushAt: 0, lastPullAt: 0, lastVersion: 0
  };
  setSyncConfig(newCfg);
  // เอา hash ออก เพื่อกัน apply ซ้ำ
  try { history.replaceState(null, '', location.pathname + location.search); } catch (e) {}
  return true;
};
// ===== Cloud Sync — รองรับ JSONBin API key (เสถียร) + fallback =====
// URL patterns:
//   jsonbin:  https://api.jsonbin.io/v3/b/{id}/latest  (ใช้ API key ของผู้ใช้)
//   jsonblob: https://jsonblob.com/api/jsonBlob/{id}
//   npoint:   https://api.npoint.io/{id}
//
// API key helper — เก็บใน localStorage เฉพาะเครื่อง (ไม่ sync ไป cloud)
const getApiKey = (provider) => {
  try { return localStorage.getItem('fd-apikey-' + provider) || ''; }
  catch (e) { return ''; }
};
const setApiKey = (provider, key) => {
  try {
    if (key) localStorage.setItem('fd-apikey-' + provider, key);
    else localStorage.removeItem('fd-apikey-' + provider);
  } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-apikey-changed', { detail: { provider } }));
};
const useApiKey = (provider) => {
  const [key, setKey] = React.useState(() => getApiKey(provider));
  React.useEffect(() => {
    const h = (e) => { if (e.detail?.provider === provider) setKey(getApiKey(provider)); };
    window.addEventListener('fd-apikey-changed', h);
    return () => window.removeEventListener('fd-apikey-changed', h);
  }, [provider]);
  return key;
};
const detectProvider = (url) => {
  if (!url) return null;
  if (url.includes('firebaseio.com') || url.includes('firebasedatabase.app')) return 'firebase';
  if (url.includes('jsonbin.io')) return 'jsonbin';
  if (url.includes('jsonblob.com')) return 'jsonblob';
  if (url.includes('npoint.io')) return 'npoint';
  return null;
};

// ===== Firebase Realtime DB helper — เก็บ URL ใน localStorage =====
// URL pattern: https://PROJECT-default-rtdb.REGION.firebasedatabase.app
const getFirebaseUrl = () => { try { return localStorage.getItem('fd-firebase-url') || ''; } catch (e) { return ''; } };
const setFirebaseUrl = (url) => {
  try { if (url) localStorage.setItem('fd-firebase-url', url); else localStorage.removeItem('fd-firebase-url'); } catch (e) {}
  window.dispatchEvent(new CustomEvent('fd-firebase-url-changed'));
};
const useFirebaseUrl = () => {
  const [u, setU] = React.useState(getFirebaseUrl);
  React.useEffect(() => {
    const h = () => setU(getFirebaseUrl());
    window.addEventListener('fd-firebase-url-changed', h);
    return () => window.removeEventListener('fd-firebase-url-changed', h);
  }, []);
  return u;
};

// สร้าง bucket ใหม่ — Firebase (ถ้ามี URL) → JSONBin → jsonblob → npoint
const createSyncBucket = async () => {
  const errors = [];

  // 0) Firebase — ถ้าผู้ใช้ตั้ง Firebase URL ไว้ → สร้างห้องใต้ path /rooms/<random>
  const fbUrl = getFirebaseUrl();
  if (fbUrl) {
    try {
      const base = fbUrl.replace(/\/+$/, '');
      const roomId = 'room-' + Math.random().toString(36).slice(2, 10);
      const url = `${base}/flowdesk/${roomId}.json`;
      const initial = { _created: Date.now(), data: {} };
      const res = await fetch(url, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(initial)
      });
      if (res.ok) return url;
      const txt = await res.text().catch(() => '');
      errors.push(`firebase: HTTP ${res.status}${txt ? ' (' + txt.slice(0, 80) + ')' : ''}`);
    } catch (e) { errors.push('firebase: ' + e.message); }
  } else {
    errors.push('firebase: ยังไม่ได้ใส่ Firebase URL');
  }

  // 1) JSONBin.io พร้อม API key ของผู้ใช้ — เสถียรอันดับ 2
  const apiKey = getApiKey('jsonbin');
  if (apiKey) {
    try {
      const initial = { _created: Date.now(), data: {} };
      const res = await fetch('https://api.jsonbin.io/v3/b', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Master-Key': apiKey,
          'X-Bin-Name': 'flowdesk-sync-' + Date.now()
        },
        body: JSON.stringify(initial)
      });
      if (res.ok) {
        const data = await res.json();
        const id = data?.metadata?.id;
        if (id) return `https://api.jsonbin.io/v3/b/${id}/latest`;
        errors.push('jsonbin: response ไม่มี id');
      } else {
        const txt = await res.text().catch(() => '');
        errors.push(`jsonbin: HTTP ${res.status}${txt ? ' (' + txt.slice(0, 80) + ')' : ''}`);
      }
    } catch (e) { errors.push('jsonbin: ' + e.message); }
  } else {
    errors.push('jsonbin: ยังไม่ได้ใส่ API key');
  }

  // 2) ลอง jsonblob.com — CORS allow *, ไม่ต้อง signup
  try {
    const initial = { _created: Date.now(), data: {} };
    const res = await fetch('https://jsonblob.com/api/jsonBlob', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },
      body: JSON.stringify(initial)
    });
    if (res.ok || res.status === 201) {
      const loc = res.headers.get('Location') || res.headers.get('Content-Location') || res.headers.get('X-jsonblob');
      if (loc) {
        const url = loc.startsWith('http') ? loc : `https://jsonblob.com${loc}`;
        return url;
      }
      errors.push('jsonblob: ตอบกลับแต่ไม่มี Location header');
    } else {
      errors.push(`jsonblob: HTTP ${res.status}`);
    }
  } catch (e) { errors.push('jsonblob: ' + e.message); }

  // 3) Fallback npoint.io — anonymous, ใช้ POST root
  try {
    const initial = { _created: Date.now(), data: {} };
    const res = await fetch('https://api.npoint.io/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(initial)
    });
    if (res.ok) {
      const data = await res.json();
      if (data && data.id) return `https://api.npoint.io/${data.id}`;
      errors.push('npoint: response ไม่มี id');
    } else {
      errors.push(`npoint: HTTP ${res.status}`);
    }
  } catch (e) { errors.push('npoint: ' + e.message); }

  // ทุก provider fail
  const isFile = (typeof location !== 'undefined' && location.protocol === 'file:');
  const hint = isFile
    ? ' · คุณเปิดไฟล์จาก file:// — browser block CORS · แนะนำอัพไฟล์ขึ้น tiiny.host หรือ Netlify (drag-drop ฟรี) แล้วลองใหม่ · หรือใช้ "ส่งออก/นำเข้า JSON" ใน tab ทั่วไป'
    : ' · เน็ตอาจมีปัญหา หรือ providers ล่ม';
  throw new Error('สร้างห้องไม่สำเร็จ' + hint + ' · รายละเอียด: ' + errors.join(' | '));
};

// ===== Merge helpers — กัน last-write-wins ทำให้ข้อมูลข้ามเครื่องหาย =====
// ใช้ตอน pull: รวม cloud + local แทนการ overwrite
// (parseThDT นิยามใน block แรก — ใช้ผ่าน window)
const _stepScore = (r) => (r.flow || []).filter(s => s.status === 'approved' || s.status === 'rejected').length;
const _reqRecency = (r) => {
  // คะแนนความใหม่ — สูง = ใหม่กว่า
  let s = _stepScore(r) * 1000;
  if (r.completedAt) s += 500;
  if (r.receivedAt) s += 200;
  if (r.cleared) s += 100;
  if (r.clearingStatus === 'submitted') s += 150;
  if (r.clearingStatus === 'verified' || r.clearingStatus === 'rejected') s += 300;
  if (r.status === 'revision') s += 150;
  if (r.flow && r.flow.length) {
    // หา timestamp ล่าสุดใน flow — 🐛FIX: ใช้ parseThDT (Date.parse อ่าน DD/MM ไทยผิด/NaN)
    const ats = r.flow.map(x => x.at).filter(Boolean).map(a => parseThDT(a)?.getTime()).filter(n => n && !isNaN(n));
    if (ats.length) s += Math.floor((Math.max(...ats) - 1700000000000) / 60000); // นาทีตั้งแต่ ref
  }
  return s;
};
const mergeRequests = (local, remote) => {
  if (!Array.isArray(local)) local = [];
  if (!Array.isArray(remote)) remote = [];
  const byId = new Map();
  local.forEach(r => { if (r && r.id) byId.set(r.id, r); });
  remote.forEach(r => {
    if (!r || !r.id) return;
    const existing = byId.get(r.id);
    if (!existing) { byId.set(r.id, r); return; }
    // 🐛FIX: ใช้ updatedAt เป็นเกณฑ์หลัก (ครอบคลุม comment/priority/verify ที่ recency มองไม่เห็น)
    const ur = r.updatedAt || 0, ue = existing.updatedAt || 0;
    if (ur !== ue) { byId.set(r.id, ur > ue ? r : existing); return; }
    // ไม่มี updatedAt ทั้งคู่/เท่ากัน — fallback recency (cloud เสมอกัน → trust cloud)
    byId.set(r.id, _reqRecency(r) >= _reqRecency(existing) ? r : existing);
  });
  return Array.from(byId.values()).sort((a, b) => (b.id || '').localeCompare(a.id || ''));
};
const mergeActivities = (local, remote) => {
  if (!Array.isArray(local)) local = [];
  if (!Array.isArray(remote)) remote = [];
  const key = (a) => `${a.at || ''}|${a.user || ''}|${a.action || ''}|${a.refId || ''}|${a.summary || ''}`;
  const seen = new Set();
  const result = [];
  [...remote, ...local].forEach(a => {
    if (!a) return;
    const k = key(a);
    if (!seen.has(k)) { seen.add(k); result.push(a); }
  });
  // 🐛FIX: sort ใหม่→เก่า ก่อนตัด 500 — เดิม remote มาก่อนเสมอ ทำ audit log เรียงผิด
  // และรายการใหม่ล่าสุดของเครื่องนี้โดนตัดทิ้งก่อน
  result.sort((a, b) => (parseThDT(b.at)?.getTime() || 0) - (parseThDT(a.at)?.getTime() || 0));
  return result.slice(0, 500);
};
const mergeUsersById = (local, remote) => {
  // users เป็น object — รวม keys · 🐛FIX: เทียบ updatedAt แทน remote-ทับ-เสมอ
  // (เดิม: ตั้งรหัสผ่าน/แก้ user บนเครื่อง A โดน cloud copy เก่าทับกลับ)
  const out = { ...(local || {}) };
  Object.entries(remote || {}).forEach(([k, v]) => {
    if (!v) return;
    const loc = out[k];
    if (!loc) { out[k] = v; return; }
    out[k] = (v.updatedAt || 0) >= (loc.updatedAt || 0) ? v : loc;
  });
  return out;
};
const mergeArrayByKey = (local, remote, keyField) => {
  if (!Array.isArray(local)) local = [];
  if (!Array.isArray(remote)) remote = [];
  const byKey = new Map();
  local.forEach(x => { if (x && x[keyField]) byKey.set(x[keyField], x); });
  remote.forEach(x => { if (x && x[keyField]) byKey.set(x[keyField], x); });
  return Array.from(byKey.values());
};

// ดึงข้อมูลล่าสุดจาก cloud
const pullFromCloud = async (bucketUrl) => {
  if (!bucketUrl) return null;
  const provider = detectProvider(bucketUrl);
  try {
    const headers = {};
    if (provider === 'jsonbin') {
      headers['X-Bin-Meta'] = 'false';
      const k = getApiKey('jsonbin'); if (k) headers['X-Master-Key'] = k;
    }
    const res = await fetch(bucketUrl, { method: 'GET', headers });
    if (res.status === 404) return null;
    if (!res.ok) throw new Error('Pull HTTP ' + res.status);
    const text = await res.text();
    if (!text || text.trim() === '' || text === 'null') return null;
    const parsed = JSON.parse(text);
    // Firebase / npoint / jsonblob: { _created, data }
    // jsonbin (X-Bin-Meta:false): { _created, data } | else: { record: {...} }
    const root = (parsed && parsed.record) ? parsed.record : parsed;
    return root && root.data ? root.data : root;
  } catch (e) {
    console.warn('Cloud pull failed:', e.message);
    return null;
  }
};

// ส่งข้อมูลขึ้น cloud (overwrite)
const pushToCloud = async (bucketUrl, payload) => {
  if (!bucketUrl) return false;
  const provider = detectProvider(bucketUrl);
  try {
    // method per provider: firebase=PUT, jsonblob=PUT, jsonbin=PUT, npoint=POST
    const method = provider === 'npoint' ? 'POST' : 'PUT';
    let url = bucketUrl;
    if (provider === 'jsonbin' && url.endsWith('/latest')) url = url.replace(/\/latest$/, '');
    const headers = { 'Content-Type': 'application/json' };
    if (provider === 'jsonbin') {
      headers['X-Bin-Versioning'] = 'false';
      const k = getApiKey('jsonbin'); if (k) headers['X-Master-Key'] = k;
    }
    const body = JSON.stringify({ _created: Date.now(), data: payload });
    const res = await fetch(url, { method, headers, body });
    if (!res.ok) throw new Error('Push HTTP ' + res.status);
    return true;
  } catch (e) {
    console.warn('Cloud push failed:', e.message);
    return false;
  }
};

// ⟪AUTO-EXPORTS-START⟫
export { PERSIST_KEY, PERSIST_FIELDS, CURRENT_USER_KEY, loadPersistedState, SYNC_CONFIG_KEY, getSyncConfig, setSyncConfig, encodeInvite, decodeInvite, buildInviteUrl, consumeInvite, getApiKey, setApiKey, useApiKey, detectProvider, getFirebaseUrl, setFirebaseUrl, useFirebaseUrl, createSyncBucket, _stepScore, _reqRecency, mergeRequests, mergeActivities, mergeUsersById, mergeArrayByKey, pullFromCloud, pushToCloud };
// ⟪AUTO-EXPORTS-END⟫
