// ⟪AUTO-HEADER-START⟫ generated by scripts/extract.mjs + gen-imports.mjs — do not edit this region by hand
import React from 'react';
import { Avatar, AvatarStack, CountUp, Empty, Glow, Icon, Modal, SLABadge, STATUS_LABEL, Sparkline, StatusBadge, TYPE_LABEL, TypeBadge, TypeIcon, canApproveStep, canReceiveRequest, downloadCSV, fmtBaht, getOOO, getSignature, nowTh, parseTh, slaInfo, togglePin, usePersistedState, usePinned, workDeadlineInfo } from '../lib/core.jsx';
// ⟪AUTO-HEADER-END⟫
const DashboardPage = ({ ctx }) => {
  const { state, setState, currentUser } = ctx;
  const pins = usePinned();
  const pinnedReqs = pins.map(id => state.requests.find(r => r.id === id)).filter(Boolean);
  const myApprovals = state.requests.filter(r =>
    r.status === 'pending' && canApproveStep(r.flow[r.currentStep], currentUser.id)
  );
  const myRequests = state.requests.filter(r => r.requester === currentUser.id);
  const myPendingClears = state.requests.filter(r => r.requester === currentUser.id && r.type === 'expense' && r.pendingClear && (r.status === 'progress' || r.status === 'done') && (r.cleared || 0) < r.amount);
  const myBorrows = state.requests.filter(r => r.requester === currentUser.id && r.type === 'borrow' && r.status !== 'rejected');
  const myWaiting = myRequests.filter(r => r.status === 'pending');

  // 14-day sparkline data for each KPI
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const days14 = Array.from({ length: 14 }, (_, i) => { const d = new Date(today); d.setDate(d.getDate() - (13 - i)); return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`; });
  const sparkApprovals = days14.map(ds => state.activities.filter(a => a.user === currentUser.id && a.action === 'approve' && a.at.startsWith(ds)).length);
  const sparkMyReqs = days14.map(ds => myRequests.filter(r => r.createdAt && r.createdAt.startsWith(ds)).length);
  const sparkBorrows = days14.map(ds => myBorrows.filter(r => r.createdAt && r.createdAt.startsWith(ds)).length);
  const sparkClears = days14.map(ds => state.activities.filter(a => a.user === currentUser.id && a.action === 'clear' && a.at.startsWith(ds)).length);

  const kpis = [
    { label: 'รอคุณพิจารณา',     value: myApprovals.length,       delta: myApprovals.length > 0 ? 'ขั้นถัดไปคืนของคุณ' : 'ไม่มีงานค้าง',  color: 'var(--amber)', spark: sparkApprovals },
    { label: 'คำขอที่ฉันยื่นไว้', value: myWaiting.length,         delta: myWaiting.length > 0 ? 'ยังอยู่ในคิว' : 'ยังไม่ได้ยื่นใหม่',        color: 'var(--blue)',   spark: sparkMyReqs },
    { label: 'ยืม–คืน',          value: myBorrows.length,         delta: myBorrows.length > 0 ? 'ต้องเคลียร์ของ' : 'ไม่มีรายการ',           color: 'var(--blue)',   spark: sparkBorrows },
    { label: 'เคลียร์ค่าใช้จ่าย', value: myPendingClears.length,   delta: myPendingClears.length > 0 ? fmtBaht(myPendingClears.reduce((s, r) => s + r.amount - (r.cleared || 0), 0)) + ' ค้าง' : 'ไม่มีค้าง', color: 'var(--violet)', spark: sparkClears }
  ];

  // ====== Today's Focus — งานที่ต้องทำวันนี้ ======
  // รวม: รออนุมัติเร่งด่วน + รับเรื่อง + งานที่กำลังทำ + เคลียร์ค้าง
  const myToReceive = state.requests.filter(r => canReceiveRequest(r, currentUser, state.users));
  const myInProgress = state.requests.filter(r => r.status === 'progress' && r.receivedAt && !r.completedAt && r.receivedBy === currentUser.id);
  const focusItems = [];
  // urgent: เกินกำหนดหรือครบวันนี้
  myApprovals.forEach(r => {
    const s = slaInfo(r.dueDate);
    if (s && (s.level === 'overdue' || s.level === 'today')) {
      focusItems.push({ req: r, priority: 1, why: s.level === 'overdue' ? 'เกินกำหนดอนุมัติ' : 'ครบกำหนดวันนี้', action: 'อนุมัติ', icon: 'warning', color: 'var(--red)' });
    }
  });
  myToReceive.forEach(r => {
    focusItems.push({ req: r, priority: 2, why: 'อนุมัติครบ รอรับเรื่อง', action: 'รับเรื่อง', icon: 'truck', color: 'var(--amber)' });
  });
  myInProgress.forEach(r => {
    const ws = workDeadlineInfo(r);
    if (ws && (ws.level === 'overdue' || ws.level === 'urgent')) {
      focusItems.push({ req: r, priority: 1, why: ws.level === 'overdue' ? 'งานเกินกำหนดส่ง' : 'ใกล้ถึงกำหนดส่ง', action: 'ส่งงาน', icon: 'clock', color: 'var(--red)' });
    }
  });
  myApprovals.forEach(r => {
    const s = slaInfo(r.dueDate);
    if (!s || (s.level !== 'overdue' && s.level !== 'today')) {
      focusItems.push({ req: r, priority: 3, why: 'รออนุมัติ', action: 'อนุมัติ', icon: 'inbox', color: 'var(--brand)' });
    }
  });
  myPendingClears.forEach(r => {
    focusItems.push({ req: r, priority: 2, why: `รอเคลียร์ ${fmtBaht(r.amount - (r.cleared || 0))}`, action: 'เคลียร์', icon: 'wallet', color: 'var(--violet)' });
  });
  // sort and dedupe by request id
  focusItems.sort((a, b) => a.priority - b.priority);
  const focusSeen = new Set();
  const focusTop = focusItems.filter(it => { if (focusSeen.has(it.req.id)) return false; focusSeen.add(it.req.id); return true; }).slice(0, 5);
  // urgent banner — รวม "ต้องด่วน" priority 1
  const urgentCount = focusItems.filter(it => it.priority === 1).length;

  // ===== Stuck Requests — คำขอของฉันที่ค้าง > 2 วันโดยไม่มี activity =====
  const stuckThreshold = 2 * 86400000; // 2 days
  const now = new Date();
  const myStuckReqs = myRequests
    .filter(r => r.status === 'pending')
    .map(r => {
      const created = parseTh(r.createdAt);
      const lastActivityAt = (() => {
        const acts = state.activities.filter(a => a.refId === r.id && a.user !== currentUser.id);
        const latest = acts[0]; // activities sorted desc
        return latest ? parseTh(latest.at) : created;
      })();
      const stuckMs = lastActivityAt ? (now - lastActivityAt) : 0;
      return { req: r, stuckMs, stuckDays: Math.floor(stuckMs / 86400000) };
    })
    .filter(x => x.stuckMs > stuckThreshold)
    .sort((a, b) => b.stuckMs - a.stuckMs)
    .slice(0, 3);

  // ===== Smart Insights — แนะนำการกระทำ =====
  const smartInsights = (() => {
    const insights = [];
    // 1. งานที่ค้างนาน > 5 วัน — แนะนำส่งเตือนหรือ escalate
    const veryStuck = myRequests.filter(r => {
      if (r.status !== 'pending') return false;
      const created = parseTh(r.createdAt);
      return created && (Date.now() - created.getTime()) > 5 * 86400000;
    });
    if (veryStuck.length > 0) {
      insights.push({
        icon: 'bell', color: 'var(--red)',
        title: `${veryStuck.length} คำขอค้างเกิน 5 วัน`,
        body: 'แนะนำส่งเตือนผู้อนุมัติ หรือพิจารณายกระดับความเร่งด่วน',
        action: 'ดูคำขอแรก',
        onClick: () => setState({ route: 'detail', selectedId: veryStuck[0].id })
      });
    }
    // 2. หา bottleneck — ผู้อนุมัติคนเดียวที่กั้น > 3 คำขอของฉัน
    const stuckByApprover = {};
    myRequests.filter(r => r.status === 'pending').forEach(r => {
      const uid = r.flow[r.currentStep]?.userId; if (!uid) return;
      stuckByApprover[uid] = (stuckByApprover[uid] || 0) + 1;
    });
    const topBottleneck = Object.entries(stuckByApprover).filter(([_, n]) => n >= 3).sort((a, b) => b[1] - a[1])[0];
    if (topBottleneck) {
      const bu = state.users[topBottleneck[0]];
      insights.push({
        icon: 'user', color: 'var(--amber)',
        title: `${bu?.name?.split(' ')[0] || topBottleneck[0]} กั้น ${topBottleneck[1]} คำขอของคุณ`,
        body: 'คนเดียวที่ค้างเยอะ — ถ้าเร่งด่วน ลองตรวจสอบความพร้อม (อาจ OOO?)',
        action: 'ดูคำขอ',
        onClick: () => setState({ route: 'detail', selectedId: myRequests.find(r => r.status === 'pending' && r.flow[r.currentStep]?.userId === topBottleneck[0])?.id })
      });
    }
    // 3. มี draft ที่ยังไม่ได้ส่ง
    try {
      const draft = JSON.parse(localStorage.getItem(`fd-draft-${currentUser.id}`));
      if (draft && draft.type && draft.form && draft.form.title) {
        insights.push({
          icon: 'bookmark', color: 'var(--brand)',
          title: 'มี Draft ที่ยังไม่ได้ส่ง',
          body: `"${draft.form.title}" — บันทึกเมื่อ ${draft.savedAt}`,
          action: 'สร้างคำขอต่อ',
          onClick: () => setState({ createOpen: true })
        });
      }
    } catch (e) {}
    // 4. งานที่จะครบเคลียร์ใน 3 วัน
    const dueClear = state.requests.filter(r => r.requester === currentUser.id && r.pendingClear && r.clearDueDate).filter(r => {
      const d = parseTh(r.clearDueDate); if (!d) return false;
      const days = (d.getTime() - Date.now()) / 86400000;
      return days >= 0 && days <= 3;
    });
    if (dueClear.length > 0) {
      insights.push({
        icon: 'wallet', color: 'var(--violet)',
        title: `${dueClear.length} คำขอใกล้ครบกำหนดเคลียร์`,
        body: 'ภายใน 3 วัน — ควรเตรียมเอกสารและรีบเคลียร์',
        action: 'ไปเคลียร์',
        onClick: () => setState({ route: 'clearing' })
      });
    }
    // 5. ถ้าไม่มี OOO ตั้งไว้แต่กำลังจะลาเร็วๆ นี้ (มีคำขอ leave ที่ยังไม่ส่ง)
    const myOoo = getOOO(currentUser.id);
    if (!myOoo.active) {
      const upcomingLeave = state.requests.find(r => r.requester === currentUser.id && r.type === 'leave' && (r.status === 'pending' || r.status === 'progress') && r.startDate);
      if (upcomingLeave) {
        insights.push({
          icon: 'bellOff', color: 'var(--brand)',
          title: 'คุณมีใบลาแต่ยังไม่ตั้ง Out of Office',
          body: `${upcomingLeave.title} — ตั้ง OOO + ผู้รับมอบเพื่อไม่ให้งานค้าง`,
          action: 'ไป Settings',
          onClick: () => { setState({ route: 'settings' }); try { localStorage.setItem('fd-settings.tab', JSON.stringify('ooo')); } catch (e) {} }
        });
      }
    }
    return insights.slice(0, 4);
  })();

  // ===== Today's Personal Stats — สถิติของฉันวันนี้ =====
  const todayStr = (() => { const d = new Date(); return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`; })();
  const myActsToday = state.activities.filter(a => a.user === currentUser.id && a.at && a.at.startsWith(todayStr));
  const personalToday = {
    approved: myActsToday.filter(a => a.action === 'approve').length,
    rejected: myActsToday.filter(a => a.action === 'reject').length,
    commented: myActsToday.filter(a => a.action === 'comment').length,
    created: myActsToday.filter(a => a.action === 'create').length,
    received: myActsToday.filter(a => a.action === 'qr-scan').length,
    total: myActsToday.length
  };

  // ===== Recent Activity Ticker — กิจกรรมล่าสุดเกี่ยวกับฉัน =====
  const myRelevantActivities = state.activities.filter(a => {
    if (a.user === currentUser.id) return false; // ไม่ใช่กิจกรรมที่ฉันทำเอง
    const refReq = state.requests.find(r => r.id === a.refId);
    if (!refReq) return false;
    // เกี่ยวข้องถ้า: ฉันเป็นผู้ขอ / ฉันเป็น watcher / ฉันเป็น approver step
    if (refReq.requester === currentUser.id) return true;
    if ((refReq.watchers || []).includes(currentUser.id)) return true;
    if (refReq.flow?.some(s => canApproveStep(s, currentUser.id))) return true;
    return false;
  }).slice(0, 6);

  return (
    <div>
      <div className="page-head">
        <div>
          <h1 className="page-title" style={{ fontWeight: 500 }}>{(() => { const h = new Date().getHours(); return h < 6 ? 'ดึกแล้ว' : h < 12 ? 'อรุณสวัสดิ์' : h < 17 ? 'สวัสดีตอนบ่าย' : 'สวัสดีตอนเย็น'; })()}, <span style={{ fontWeight: 700 }}>{currentUser.name.split(' ')[0]}</span></h1>
          <div className="page-sub">{(() => { const d = new Date(); const days = ['อาทิตย์','จันทร์','อังคาร','พุธ','พฤหัสบดี','ศุกร์','เสาร์']; const months = ['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม']; return `วัน${days[d.getDay()]} ที่ ${d.getDate()} ${months[d.getMonth()]} ${d.getFullYear()}`; })() } · มีงาน {myApprovals.length} รายการรออนุมัติของคุณ</div>
        </div>
        <div className="row gap-8">
          <button className="btn btn-outline" onClick={() => setState({ route: 'audit' })}>
            <Icon name="shield" size={14} /> Audit log
          </button>
          <button className="btn btn-primary" onClick={() => setState({ createOpen: true })}>
            <Icon name="plus" size={14} /> สร้างคำขอใหม่
          </button>
        </div>
      </div>

      {/* Urgent banner */}
      {urgentCount > 0 && (
        <div className="alert alert-red mb-16" style={{ borderColor: 'var(--red)', background: 'color-mix(in oklch, var(--red) 10%, var(--surface))' }}>
          <Icon name="warning" size={18} style={{ marginTop: 1, color: 'var(--red)' }} />
          <div className="flex-1">
            <div className="medium" style={{ color: 'var(--red-ink)' }}>🚨 มี {urgentCount} เรื่องเร่งด่วนต้องทำวันนี้</div>
            <div className="text-xs muted mt-2">งานที่เกินกำหนดหรือครบกำหนดวันนี้ — ดูที่ "วันนี้ต้องทำ" ด้านล่าง</div>
          </div>
        </div>
      )}

      {/* Today's Focus */}
      {focusTop.length > 0 && (
        <div className="card mb-20" style={{ overflow: 'hidden' }}>
          <div className="card-head" style={{ background: 'color-mix(in oklch, var(--brand) 6%, var(--surface))' }}>
            <div className="row gap-8" style={{ alignItems: 'center' }}>
              <Icon name="zap" size={16} style={{ color: 'var(--brand)' }} />
              <h3 className="card-title">วันนี้ต้องทำ — Top {focusTop.length}</h3>
            </div>
            <span className="text-xs muted">{focusItems.length} เรื่องทั้งหมด · เรียงตามความเร่งด่วน</span>
          </div>
          <div className="col gap-0">
            {focusTop.map((f, i) => {
              const u = state.users[f.req.requester];
              return (
                <div key={f.req.id} className="row gap-12 clickable" style={{ padding: 12, borderBottom: i < focusTop.length - 1 ? '1px solid var(--border)' : 'none', cursor: 'pointer', alignItems: 'center' }} onClick={() => setState({ route: 'detail', selectedId: f.req.id })}>
                  <div style={{ width: 32, height: 32, borderRadius: 8, background: `color-mix(in oklch, ${f.color} 18%, var(--surface-2))`, color: f.color, display: 'grid', placeItems: 'center', flexShrink: 0 }}><Icon name={f.icon} size={16} /></div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div className="row gap-8" style={{ alignItems: 'center' }}>
                      <span className="text-sm medium" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{f.req.title}</span>
                      <TypeBadge type={f.req.type} />
                      <span className="badge" style={{ background: `color-mix(in oklch, ${f.color} 18%, var(--surface-2))`, color: f.color, fontWeight: 600 }}>{f.why}</span>
                    </div>
                    <div className="text-xs muted mt-2">
                      <span className="en tnum">{f.req.id}</span> · {u?.name} · ครบกำหนด {f.req.dueDate}
                    </div>
                  </div>
                  <button className="btn btn-primary btn-sm" onClick={(e) => { e.stopPropagation(); setState({ route: 'detail', selectedId: f.req.id }); }}>
                    {f.action} <Icon name="chevronRight" size={11} />
                  </button>
                </div>
              );
            })}
          </div>
        </div>
      )}

      <div className="grid grid-4 mb-24">
        {kpis.map((k, i) => (
          <Glow key={i} style={{ padding: 18, background: 'var(--surface)', borderRadius: 12, border: '1px solid var(--border)', overflow: 'hidden', cursor: 'default' }}>
            <div className="text-xs muted" style={{ marginBottom: 8 }}>{k.label}</div>
            <div className="row spread" style={{ alignItems: 'baseline', gap: 8 }}>
              <div className="en" style={{ fontSize: 30, fontWeight: 600, letterSpacing: '-0.02em', lineHeight: 1, color: k.value > 0 ? 'var(--ink)' : 'var(--ink-3)' }}>
                {typeof k.value === 'number' ? <CountUp value={k.value} /> : k.value}
              </div>
              {k.spark && k.spark.some(v => v > 0) && <Sparkline data={k.spark} color={k.color} width={56} height={20} />}
            </div>
            <div className="text-xs muted" style={{ marginTop: 8, lineHeight: 1.3 }}>{k.delta}</div>
            <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 2, background: k.color, opacity: k.value > 0 ? 1 : 0.2, zIndex: 2 }}></div>
          </Glow>
        ))}
      </div>

      {/* Smart Insights — แนะนำการกระทำ */}
      {smartInsights.length > 0 && (
        <div className="card mb-16" style={{ borderLeft: '3px solid var(--brand)', overflow: 'hidden' }}>
          <div className="card-head" style={{ background: 'color-mix(in oklch, var(--brand) 5%, var(--surface))' }}>
            <div className="row gap-8" style={{ alignItems: 'center' }}>
              <Icon name="zap" size={16} style={{ color: 'var(--brand)' }} />
              <h3 className="card-title">💡 ข้อเสนอแนะอัจฉริยะ</h3>
            </div>
            <span className="text-xs muted">{smartInsights.length} ข้อเสนอแนะ</span>
          </div>
          <div className="grid grid-2" style={{ gap: 0 }}>
            {smartInsights.map((ins, i) => (
              <div key={i} style={{ padding: 14, borderRight: i % 2 === 0 ? '1px solid var(--border)' : 'none', borderBottom: i < smartInsights.length - 2 ? '1px solid var(--border)' : 'none', display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <div style={{ width: 32, height: 32, borderRadius: 8, background: `color-mix(in oklch, ${ins.color} 18%, var(--surface-2))`, color: ins.color, display: 'grid', placeItems: 'center', flexShrink: 0 }}><Icon name={ins.icon} size={14} /></div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div className="medium text-sm">{ins.title}</div>
                  <div className="text-xs muted mt-2" style={{ lineHeight: 1.5 }}>{ins.body}</div>
                  <button className="btn btn-ghost btn-sm mt-6" onClick={ins.onClick} style={{ height: 24, padding: '0 8px', color: ins.color }}>{ins.action} <Icon name="chevronRight" size={10} /></button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Today's Personal Stats — สถิติของฉันวันนี้ */}
      {personalToday.total > 0 && (
        <div className="card card-pad mb-16" style={{ background: 'linear-gradient(135deg, color-mix(in oklch, var(--green) 6%, var(--surface)) 0%, var(--surface) 100%)', borderLeft: '3px solid var(--green)' }}>
          <div className="row gap-12 flex-wrap" style={{ alignItems: 'center' }}>
            <div className="row gap-8" style={{ alignItems: 'center', flexShrink: 0 }}>
              <Icon name="trophy" size={18} style={{ color: 'var(--green)' }} />
              <h3 className="card-title">📈 วันนี้ฉันทำไปแล้ว</h3>
            </div>
            <div className="row gap-16 flex-wrap" style={{ marginLeft: 'auto', alignItems: 'center' }}>
              {personalToday.approved > 0 && (
                <div className="row gap-6" style={{ alignItems: 'center' }}>
                  <div style={{ width: 26, height: 26, borderRadius: 6, background: 'var(--green-soft)', color: 'var(--green-ink)', display: 'grid', placeItems: 'center' }}><Icon name="check" size={13} /></div>
                  <div><div className="en bold" style={{ fontSize: 18, lineHeight: 1 }}>{personalToday.approved}</div><div className="text-xs muted">อนุมัติ</div></div>
                </div>
              )}
              {personalToday.rejected > 0 && (
                <div className="row gap-6" style={{ alignItems: 'center' }}>
                  <div style={{ width: 26, height: 26, borderRadius: 6, background: 'var(--red-soft)', color: 'var(--red-ink)', display: 'grid', placeItems: 'center' }}><Icon name="x" size={13} /></div>
                  <div><div className="en bold" style={{ fontSize: 18, lineHeight: 1 }}>{personalToday.rejected}</div><div className="text-xs muted">ปฏิเสธ</div></div>
                </div>
              )}
              {personalToday.received > 0 && (
                <div className="row gap-6" style={{ alignItems: 'center' }}>
                  <div style={{ width: 26, height: 26, borderRadius: 6, background: 'var(--brand-soft)', color: 'var(--brand-ink)', display: 'grid', placeItems: 'center' }}><Icon name="truck" size={13} /></div>
                  <div><div className="en bold" style={{ fontSize: 18, lineHeight: 1 }}>{personalToday.received}</div><div className="text-xs muted">รับเรื่อง</div></div>
                </div>
              )}
              {personalToday.commented > 0 && (
                <div className="row gap-6" style={{ alignItems: 'center' }}>
                  <div style={{ width: 26, height: 26, borderRadius: 6, background: 'var(--blue-soft)', color: 'var(--blue-ink)', display: 'grid', placeItems: 'center' }}><Icon name="message" size={13} /></div>
                  <div><div className="en bold" style={{ fontSize: 18, lineHeight: 1 }}>{personalToday.commented}</div><div className="text-xs muted">คอมเมนต์</div></div>
                </div>
              )}
              {personalToday.created > 0 && (
                <div className="row gap-6" style={{ alignItems: 'center' }}>
                  <div style={{ width: 26, height: 26, borderRadius: 6, background: 'var(--violet-soft)', color: 'var(--violet-ink)', display: 'grid', placeItems: 'center' }}><Icon name="plus" size={13} /></div>
                  <div><div className="en bold" style={{ fontSize: 18, lineHeight: 1 }}>{personalToday.created}</div><div className="text-xs muted">สร้างคำขอ</div></div>
                </div>
              )}
              <div style={{ borderLeft: '1px solid var(--border)', paddingLeft: 16 }}>
                <div className="en bold" style={{ fontSize: 24, lineHeight: 1, color: 'var(--green-ink)' }}>{personalToday.total}</div>
                <div className="text-xs muted">รวม</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Stuck Requests — แนะนำให้เตือนผู้อนุมัติ */}
      {myStuckReqs.length > 0 && (
        <div className="card mb-16" style={{ borderLeft: '3px solid var(--amber)', overflow: 'hidden' }}>
          <div className="card-head" style={{ background: 'color-mix(in oklch, var(--amber) 6%, var(--surface))' }}>
            <div className="row gap-8" style={{ alignItems: 'center' }}>
              <Icon name="bell" size={16} style={{ color: 'var(--amber-ink)' }} />
              <h3 className="card-title">💡 คำขอที่ค้างไม่ขยับ — แนะนำส่งเตือนผู้อนุมัติ</h3>
            </div>
            <span className="text-xs muted">{myStuckReqs.length} รายการที่ค้าง &gt; 2 วัน</span>
          </div>
          <div className="col gap-0">
            {myStuckReqs.map((x, i) => {
              const r = x.req;
              const stepUser = state.users[r.flow[r.currentStep]?.userId];
              return (
                <div key={r.id} className="row gap-12 clickable" style={{ padding: 12, borderBottom: i < myStuckReqs.length - 1 ? '1px solid var(--border)' : 'none', cursor: 'pointer', alignItems: 'center' }} onClick={() => setState({ route: 'detail', selectedId: r.id })}>
                  <Avatar user={stepUser} size="sm" />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div className="row gap-8" style={{ alignItems: 'center' }}>
                      <span className="en tnum text-xs muted">{r.id}</span>
                      <TypeBadge type={r.type} />
                      <span className="text-sm medium" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.title}</span>
                    </div>
                    <div className="text-xs muted mt-2">รออยู่ที่ <span className="medium">{stepUser?.name || 'ผู้อนุมัติ'}</span> · ค้างมา <span style={{ color: x.stuckDays >= 5 ? 'var(--red-ink)' : 'var(--amber-ink)', fontWeight: 600 }}>{x.stuckDays} วัน</span>{r.nudgeCount ? ` · เคยเตือนแล้ว ${r.nudgeCount} ครั้ง` : ''}</div>
                  </div>
                  <button className="btn btn-outline btn-sm" onClick={(e) => { e.stopPropagation(); setState({ route: 'detail', selectedId: r.id }); }}>
                    <Icon name="bell" size={11} /> ไปเตือน
                  </button>
                </div>
              );
            })}
          </div>
        </div>
      )}

      <div className="grid" style={{ gridTemplateColumns: '1.5fr 1fr', gap: 16 }}>
        <div className="col gap-16">
          {pinnedReqs.length > 0 && (
            <div className="card">
              <div className="card-head">
                <div>
                  <h3 className="card-title"><Icon name="starFill" size={14} style={{ color: '#facc15' }} /> ปักหมุดไว้</h3>
                  <div className="card-sub">{pinnedReqs.length} คำขอที่คุณติดตาม</div>
                </div>
              </div>
              <div>{pinnedReqs.map(r => <RequestRow key={r.id} req={r} users={state.users} onClick={() => setState({ route: 'detail', selectedId: r.id })} compact />)}</div>
            </div>
          )}
          <div className="card">
            <div className="card-head">
              <div>
                <h3 className="card-title">รออนุมัติของคุณ</h3>
                <div className="card-sub">{myApprovals.length} รายการต้องการ Action</div>
              </div>
              <button className="btn btn-ghost btn-sm" onClick={() => setState({ route: 'approvals' })}>
                ดูทั้งหมด <Icon name="arrowRight" size={12} />
              </button>
            </div>
            {myApprovals.length === 0 ? (
              <div style={{ padding: 20 }}><Empty icon="check" title="ว่างอยู่" sub="ไม่มีคำขอที่รอคุณพิจารณา" /></div>
            ) : (
              <div>{myApprovals.map(r => <RequestRow key={r.id} req={r} users={state.users} onClick={() => setState({ route: 'detail', selectedId: r.id })} compact />)}</div>
            )}
          </div>
          <div className="card">
            <div className="card-head">
              <div>
                <h3 className="card-title">คำขอของฉัน</h3>
                <div className="card-sub">{myRequests.length} รายการในระบบ</div>
              </div>
              <button className="btn btn-ghost btn-sm" onClick={() => setState({ route: 'my-requests' })}>
                ดูทั้งหมด <Icon name="arrowRight" size={12} />
              </button>
            </div>
            <div>
              {myRequests.slice(0, 4).map(r => <RequestRow key={r.id} req={r} users={state.users} onClick={() => setState({ route: 'detail', selectedId: r.id })} compact />)}
              {myRequests.length === 0 && <div style={{ padding: 20 }}><Empty title="ยังไม่มีคำขอ" sub="กดสร้างคำขอใหม่เพื่อเริ่ม" /></div>}
            </div>
          </div>
        </div>
        <div className="col gap-16">
          {(() => {
            const now = new Date(); now.setHours(0,0,0,0);
            const horizon = new Date(now); horizon.setDate(horizon.getDate() + 14);
            const upcoming = [];
            state.requests.forEach(r => {
              if (r.status === 'rejected') return;
              if (r.type === 'event' && r.eventStartDate) {
                const d = parseTh(r.eventStartDate);
                if (d && d >= now && d <= horizon) upcoming.push({ d, r, kind: 'event' });
              } else if (r.dueDate) {
                const d = parseTh(r.dueDate);
                if (d && d >= now && d <= horizon && (r.status === 'pending' || r.status === 'progress')) upcoming.push({ d, r, kind: 'due' });
              }
            });
            upcoming.sort((a, b) => a.d - b.d);
            const top = upcoming.slice(0, 6);
            return (
              <>
              {/* Recent Activity Ticker */}
              {myRelevantActivities.length > 0 && (
                <div className="card mb-16">
                  <div className="card-head">
                    <div>
                      <h3 className="card-title">📡 กิจกรรมที่เกี่ยวข้องกับฉัน</h3>
                      <div className="card-sub">คนอื่นทำอะไรกับคำขอที่ฉันยื่น / ติดตาม / อนุมัติ</div>
                    </div>
                    <button className="btn btn-ghost btn-sm" onClick={() => setState({ route: 'audit' })}>ดูทั้งหมด <Icon name="arrowRight" size={12} /></button>
                  </div>
                  <div style={{ padding: '4px 0' }}>
                    {myRelevantActivities.map((a, i) => {
                      const actor = state.users[a.user];
                      const refReq = state.requests.find(r => r.id === a.refId);
                      const actionIcon = a.action === 'approve' ? { ic: 'check', col: 'var(--green-ink)' } : a.action === 'reject' ? { ic: 'x', col: 'var(--red-ink)' } : a.action === 'comment' ? { ic: 'message', col: 'var(--brand-ink)' } : { ic: 'plus', col: 'var(--ink-2)' };
                      return (
                        <div key={i} className="row gap-10 clickable" style={{ padding: '10px 16px', borderBottom: i < myRelevantActivities.length - 1 ? '1px solid var(--border)' : 'none', cursor: 'pointer', alignItems: 'center' }} onClick={() => refReq && setState({ route: 'detail', selectedId: refReq.id })}>
                          <div style={{ width: 24, height: 24, borderRadius: '50%', background: 'var(--surface-2)', color: actionIcon.col, display: 'grid', placeItems: 'center', flexShrink: 0 }}><Icon name={actionIcon.ic} size={11} /></div>
                          <Avatar user={actor} size="sm" />
                          <div style={{ flex: 1, minWidth: 0 }}>
                            <div className="text-sm" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              <span className="medium">{actor?.name?.split(' ')[0] || a.user}</span> <span className="muted">{a.summary}</span>
                            </div>
                            <div className="text-xs muted">
                              <span className="en">{a.at}</span>{refReq && <> · <span className="en">{refReq.id}</span> · {refReq.title}</>}
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}
              <div className="card">
                <div className="card-head">
                  <div>
                    <h3 className="card-title">กำหนดการ 14 วันข้างหน้า</h3>
                    <div className="card-sub">{upcoming.length} รายการ — งานอีเว้นท์ + คำขอใกล้ครบกำหนด</div>
                  </div>
                  <button className="btn btn-ghost btn-sm" onClick={() => setState({ route: 'calendar' })}>ปฏิทิน <Icon name="arrowRight" size={12} /></button>
                </div>
                <div style={{ padding: '4px 0' }}>
                  {top.length === 0 ? <div style={{ padding: 20 }}><Empty icon="calendar" title="ไม่มีกำหนดการในช่วงนี้" /></div> : top.map((x, i) => {
                    const days = Math.round((x.d - now) / 86400000);
                    const ty = TYPE_LABEL[x.r.type];
                    return (
                      <button key={i} className="row gap-12" style={{ width: '100%', padding: '10px 18px', borderBottom: i < top.length - 1 ? '1px solid var(--border)' : 'none', cursor: 'pointer', textAlign: 'left', background: 'transparent', border: 'none' }}
                        onClick={() => setState({ route: 'detail', selectedId: x.r.id })}>
                        <div style={{ minWidth: 44, textAlign: 'center', padding: '4px 6px', background: ty.color + '18', color: ty.color, borderRadius: 6 }}>
                          <div className="en bold" style={{ fontSize: 16, lineHeight: 1 }}>{x.d.getDate()}</div>
                          <div className="en" style={{ fontSize: 9 }}>{['ม.ค','ก.พ','มี.ค','เม.ย','พ.ค','มิ.ย','ก.ค','ส.ค','ก.ย','ต.ค','พ.ย','ธ.ค'][x.d.getMonth()]}</div>
                        </div>
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <div className="row gap-6"><TypeBadge type={x.r.type} /><span className="text-xs muted">{x.kind === 'event' ? 'จัดงาน' : 'ครบกำหนด'}</span></div>
                          <div className="text-sm medium" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', marginTop: 2 }}>{x.r.title}</div>
                        </div>
                        <span className="text-xs" style={{ color: days <= 1 ? 'var(--red-ink)' : days <= 3 ? 'var(--amber-ink)' : 'var(--ink-3)', whiteSpace: 'nowrap' }}>{days === 0 ? 'วันนี้' : days === 1 ? 'พรุ่งนี้' : `อีก ${days} วัน`}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
              </>
            );
          })()}
          <div className="card card-pad">
            <div className="spread mb-16">
              <h3 className="card-title">สัดส่วนคำขอตามประเภท</h3>
              <span className="text-xs muted en">30 วันล่าสุด</span>
            </div>
            <DonutChart
              data={['event','general','purchase','overtime','leave','withdrawal','borrow','expense']
                .map(t => ({ label: TYPE_LABEL[t].th, value: state.requests.filter(r => r.type === t).length, color: TYPE_LABEL[t].color }))
                .filter(d => d.value > 0)}
            />
          </div>
          <div className="card">
            <div className="card-head">
              <div>
                <h3 className="card-title">ความเคลื่อนไหวล่าสุด</h3>
                <div className="card-sub">{state.activities.length} เหตุการณ์ในระบบ</div>
              </div>
              <button className="btn btn-ghost btn-sm" onClick={() => setState({ route: 'audit' })}>ดูทั้งหมด <Icon name="arrowRight" size={12} /></button>
            </div>
            {state.activities.length === 0 ? (
              <div style={{ padding: 20 }}><Empty title="ยังไม่มีเหตุการณ์" sub="กิจกรรมจะปรากฏที่นี่เมื่อมีคนสร้างหรืออนุมัติคำขอ" /></div>
            ) : (
              <div style={{ padding: '8px 18px 16px' }}>
                {state.activities.slice(0, 8).map((a, i) => {
                  const u = state.users[a.user];
                  const iconMap = { approve: { icon: 'check', cls: 'green' }, reject: { icon: 'x', cls: 'red' }, create: { icon: 'plus', cls: 'brand' }, import: { icon: 'upload', cls: '' }, clear: { icon: 'wallet', cls: 'green' }, 'qr-scan': { icon: 'qr', cls: '' }, return: { icon: 'repeat', cls: '' }, comment: { icon: 'message', cls: '' } };
                  const ic = iconMap[a.action] || { icon: 'info', cls: '' };
                  const isFresh = i === 0;
                  return (
                    <div className="tl-item clickable" key={i}
                      onClick={() => a.refId && setState({ route: 'detail', selectedId: a.refId })}
                      style={{ cursor: a.refId ? 'pointer' : 'default', borderRadius: 6, padding: 4, margin: -4, transition: 'background 0.15s' }}
                      onMouseEnter={(e) => { e.currentTarget.style.background = 'var(--surface-2)'; }}
                      onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent'; }}>
                      <div className={`tl-dot ${ic.cls}`} style={isFresh ? { animation: 'pulse 1.8s infinite' } : undefined}><Icon name={ic.icon} size={13} /></div>
                      <div className="tl-content">
                        <div className="text-sm"><span className="bold">{u?.name?.split(' ')[0] || a.user}</span> <span className="muted">{a.summary}</span> {a.refId && <span className="en muted-2 tnum">{a.refId}</span>}</div>
                        <div className="tl-meta">{a.at}</div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

const DonutChart = ({ data }) => {
  const total = data.reduce((s, d) => s + d.value, 0);
  let offset = 0;
  const r = 56, c = 2 * Math.PI * r;
  return (
    <div className="row gap-20" style={{ alignItems: 'center' }}>
      <svg width="140" height="140" viewBox="0 0 140 140" style={{ flexShrink: 0 }}>
        <circle cx="70" cy="70" r={r} fill="none" stroke="var(--surface-3)" strokeWidth="16" />
        {data.map((d, i) => {
          const frac = d.value / total;
          const len = frac * c;
          const el = <circle key={i} cx="70" cy="70" r={r} fill="none" stroke={d.color} strokeWidth="16" strokeDasharray={`${len} ${c}`} strokeDashoffset={-offset} transform="rotate(-90 70 70)" strokeLinecap="butt" />;
          offset += len;
          return el;
        })}
        <text x="70" y="68" textAnchor="middle" fontFamily="var(--font-en)" fontSize="22" fontWeight="600" fill="var(--ink)">{total}</text>
        <text x="70" y="86" textAnchor="middle" fontFamily="var(--font-en)" fontSize="10" fill="var(--ink-3)">รวม</text>
      </svg>
      <div className="col gap-8" style={{ flex: 1 }}>
        {data.map((d, i) => (
          <div key={i} className="spread">
            <div className="row gap-8"><span style={{ width: 10, height: 10, borderRadius: 2, background: d.color, display: 'inline-block' }}></span><span style={{ fontSize: 12.5 }}>{d.label}</span></div>
            <span className="en tnum medium" style={{ fontSize: 13 }}>{d.value}</span>
          </div>
        ))}
      </div>
    </div>
  );
};

const RequestRow = ({ req, users, onClick, compact = false, showRequester = true }) => {
  const u = users[req.requester];
  const total = req.flow.length;
  const done = req.flow.filter(s => s.status === 'approved').length;
  const pins = usePinned();
  const pinned = pins.includes(req.id);
  const [previewOpen, setPreviewOpen] = React.useState(false);
  const [previewPos, setPreviewPos] = React.useState({ x: 0, y: 0 });
  const hoverTimer = React.useRef(null);
  const rowRef = React.useRef(null);
  const onEnter = (e) => {
    e.currentTarget.style.background = 'color-mix(in oklch, var(--brand) 7%, var(--surface))';
    e.currentTarget.style.paddingLeft = '26px';
    e.currentTarget.style.boxShadow = 'inset 4px 0 0 var(--brand)';
    clearTimeout(hoverTimer.current);
    hoverTimer.current = setTimeout(() => {
      const el = rowRef.current; if (!el) return;
      const r = el.getBoundingClientRect();
      setPreviewPos({ x: r.right - 280, y: r.bottom + 6 });
      setPreviewOpen(true);
    }, 650);
  };
  const onLeave = (e) => {
    e.currentTarget.style.background = 'transparent';
    e.currentTarget.style.paddingLeft = '18px';
    e.currentTarget.style.boxShadow = 'none';
    clearTimeout(hoverTimer.current);
    setPreviewOpen(false);
  };
  const isHighPriority = req.priority === 'high' || req.priority === 'critical';
  const isAutoUrgent = !!req.autoUrgent;
  return (
    <div ref={rowRef} onClick={onClick} className="row-hover" style={{ display: 'grid', gridTemplateColumns: '32px 1fr auto auto auto', gap: 14, padding: '14px 18px', borderBottom: '1px solid var(--border)', cursor: 'pointer', alignItems: 'center', transition: 'background 0.2s cubic-bezier(.22,1,.36,1), padding 0.2s cubic-bezier(.22,1,.36,1), box-shadow 0.2s ease', position: 'relative', background: isHighPriority ? 'color-mix(in oklch, var(--red) 5%, var(--surface))' : undefined, borderLeft: isHighPriority ? '3px solid var(--red)' : '3px solid transparent' }}
      onMouseEnter={onEnter} onMouseLeave={onLeave}>
      <span className="type-icon-wrap"><TypeIcon type={req.type} size={32} /></span>
      <div style={{ minWidth: 0 }}>
        <div className="row gap-8" style={{ marginBottom: 3 }}>
          <span className="en tnum text-xs muted">{req.id}</span>
          {isHighPriority && <span style={{ display: 'inline-flex', alignItems: 'center', gap: 3, fontSize: 11, color: 'var(--red-ink)', fontWeight: 700 }}><Icon name="flame" size={11} /> {req.priority === 'critical' ? 'วิกฤต' : 'เร่งด่วน'}{isAutoUrgent && ' ⚡'}</span>}
          {req.overdue && <span className="badge badge-red">เกินกำหนด</span>}
        </div>
        <div className="medium" style={{ fontSize: 13.5, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{req.title}</div>
        {compact ? (
          <div className="row gap-12 text-xs muted mt-2">
            {showRequester && <span>{u?.name}</span>}
            <span className="en tnum">{fmtBaht(req.amount)}</span>
            <span>{req.lastActivity}</span>
          </div>
        ) : (
          <div className="row gap-12 text-xs muted mt-4">
            {showRequester && <span><Icon name="user" size={11} /> {u?.name}</span>}
            <span><Icon name="calendar" size={11} /> ครบกำหนด {req.dueDate}</span>
            {req.amount && <span className="en tnum">{fmtBaht(req.amount)}</span>}
          </div>
        )}
      </div>
      <div className="col" style={{ alignItems: 'flex-end', gap: 6, minWidth: 110 }}>
        <StatusBadge status={req.status} />
        {req.status === 'pending' || req.status === 'progress' ? <SLABadge dueDate={req.dueDate} compact /> : <div className="text-xs muted en tnum">{done}/{total}</div>}
      </div>
      <div className={pinned ? "row gap-2" : "row-actions row gap-2"}>
        <button className="btn btn-ghost btn-icon-only btn-sm" title={pinned ? 'เลิกปักหมุด' : 'ปักหมุด'}
          onClick={(e) => { e.stopPropagation(); togglePin(req.id); }}
          style={{ color: pinned ? '#facc15' : 'var(--ink-4)' }}>
          <Icon name={pinned ? 'starFill' : 'star'} size={14} />
        </button>
      </div>
      <Icon name="chevronRight" size={14} className="muted-2" style={{ transition: 'transform 0.2s' }} />
      {previewOpen && (
        <div style={{ position: 'fixed', left: Math.max(12, previewPos.x), top: previewPos.y, width: 300, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 10, boxShadow: '0 16px 40px -12px oklch(20% 0.04 60 / 0.3), 0 4px 12px -4px oklch(20% 0.04 60 / 0.15)', padding: 14, zIndex: 30, pointerEvents: 'none', animation: 'fadeIn 0.15s ease-out' }}>
          <div className="row gap-8 mb-8">
            <TypeIcon type={req.type} size={28} />
            <div style={{ flex: 1, minWidth: 0 }}>
              <div className="text-xs muted en">{req.id}</div>
              <div className="text-sm medium" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{req.title}</div>
            </div>
          </div>
          <div className="text-xs muted" style={{ lineHeight: 1.5, marginBottom: 10, display: '-webkit-box', WebkitLineClamp: 3, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>{req.purpose}</div>
          <div className="row spread text-xs mb-8">
            <span className="muted">ผู้ขอ</span>
            <span className="medium">{u?.name}</span>
          </div>
          {req.amount > 0 && <div className="row spread text-xs mb-8"><span className="muted">มูลค่า</span><span className="en bold">{fmtBaht(req.amount)}</span></div>}
          <div className="row spread text-xs mb-8"><span className="muted">ขั้น</span><span className="en">{done}/{total} · {req.flow[req.currentStep]?.role || 'เสร็จ'}</span></div>
          {req.eventStaff && req.eventStaff.length > 0 && (
            <div className="row gap-4" style={{ marginTop: 8, paddingTop: 8, borderTop: '1px solid var(--border)' }}>
              <span className="text-xs muted">ไปงาน:</span>
              <AvatarStack users={req.eventStaff.map(uid => users[uid]).filter(Boolean)} max={4} size="sm" />
            </div>
          )}
        </div>
      )}
    </div>
  );
};

const ApprovalsPage = ({ ctx }) => {
  const { state, setState, currentUser } = ctx;
  const [filter, setFilter] = usePersistedState('approvals.filter', 'mine');
  const [sortBy, setSortBy] = usePersistedState('approvals.sort', 'urgency');
  const all = state.requests.filter(r => r.status === 'pending');
  const mine = all.filter(r => canApproveStep(r.flow[r.currentStep], currentUser.id));
  const mineUrgent = mine.filter(r => r.priority === 'high' || r.priority === 'critical');
  let list = filter === 'mine' ? mine : filter === 'urgent' ? mineUrgent : all;
  const PRIO_W_AP = { critical: 4, high: 3, normal: 2, low: 1 };
  if (sortBy === 'urgency') {
    const score = (r) => { const s = slaInfo(r.dueDate); return s ? (s.level === 'overdue' ? -1000 - s.days : s.days) : 9999; };
    list = [...list].sort((a, b) => score(a) - score(b));
  } else if (sortBy === 'amount') {
    list = [...list].sort((a, b) => (b.amount || 0) - (a.amount || 0));
  } else if (sortBy === 'priority') {
    list = [...list].sort((a, b) => (PRIO_W_AP[b.priority] || 0) - (PRIO_W_AP[a.priority] || 0));
  }
  // เรียง: ด่วนขึ้นบนสุดเสมอ (เว้นแต่ user เลือก sort อื่นที่ override)
  if (filter !== 'urgent' && sortBy !== 'priority') {
    list = [...list].sort((a, b) => {
      const ah = (a.priority === 'high' || a.priority === 'critical') ? 1 : 0;
      const bh = (b.priority === 'high' || b.priority === 'critical') ? 1 : 0;
      return bh - ah;
    });
  }
  const [selected, setSelected] = React.useState(new Set());
  const [rejectModal, setRejectModal] = React.useState(false);
  const [rejectReason, setRejectReason] = React.useState('');
  const toggleSelected = (id) => { const next = new Set(selected); next.has(id) ? next.delete(id) : next.add(id); setSelected(next); };

  const bulkApprove = () => {
    const snapshot = { requests: state.requests, activities: state.activities };
    // 🐛FIX: เดิมไม่เช็คสิทธิ์ — ใครก็ได้เลือกทั้งหมดใน tab "ทั้งหมด" แล้วอนุมัติแทน ผอ./CEO ได้
    const approvableIds = new Set([...selected].filter(id => { const r = state.requests.find(x => x.id === id); return r && canApproveStep(r.flow[r.currentStep], currentUser.id); }));
    if (approvableIds.size === 0) { window.toast('ไม่มีรายการที่คุณมีสิทธิ์อนุมัติในที่เลือก', { level: 'warning' }); return; }
    const skipped = selected.size - approvableIds.size;
    const count = approvableIds.size;
    const next = state.requests.map(r => {
      if (!approvableIds.has(r.id)) return r;
      const newFlow = [...r.flow];
      newFlow[r.currentStep] = { ...newFlow[r.currentStep], status: 'approved', at: nowTh(), approvedBy: currentUser.id, signature: getSignature(currentUser.id) || '' };
      const n = r.currentStep + 1;
      return { ...r, flow: newFlow, currentStep: n, status: n >= r.flow.length ? 'progress' : 'pending' };
    });
    const acts = [...approvableIds].map(id => ({ at: nowTh(), user: currentUser.id, action: 'approve', refId: id, summary: 'อนุมัติคำขอ (bulk)' }));
    setState({ requests: next, activities: [...acts, ...state.activities] });
    setSelected(new Set());
    window.toast(`อนุมัติ ${count} คำขอเรียบร้อย${skipped > 0 ? ` (ข้าม ${skipped} รายการที่ไม่มีสิทธิ์)` : ''}`, { level: 'success', duration: 8000, action: { label: 'ย้อน', onClick: () => { setState(snapshot); window.toast('ยกเลิกการอนุมัติแล้ว', { level: 'info' }); } } });
  };
  const bulkReject = () => {
    if (!rejectReason.trim()) return;
    const snapshot = { requests: state.requests, activities: state.activities };
    // 🐛FIX: เช็คสิทธิ์เหมือน bulkApprove
    const rejectableIds = new Set([...selected].filter(id => { const r = state.requests.find(x => x.id === id); return r && canApproveStep(r.flow[r.currentStep], currentUser.id); }));
    if (rejectableIds.size === 0) { window.toast('ไม่มีรายการที่คุณมีสิทธิ์ปฏิเสธในที่เลือก', { level: 'warning' }); setRejectModal(false); return; }
    const count = rejectableIds.size;
    const next = state.requests.map(r => {
      if (!rejectableIds.has(r.id)) return r;
      const newFlow = [...r.flow];
      newFlow[r.currentStep] = { ...newFlow[r.currentStep], status: 'rejected', at: nowTh(), comment: rejectReason };
      return { ...r, flow: newFlow, status: 'rejected' };
    });
    const acts = [...rejectableIds].map(id => ({ at: nowTh(), user: currentUser.id, action: 'reject', refId: id, summary: 'ปฏิเสธคำขอ (bulk): ' + rejectReason }));
    setState({ requests: next, activities: [...acts, ...state.activities] });
    setSelected(new Set()); setRejectModal(false); setRejectReason('');
    window.toast(`ปฏิเสธ ${count} คำขอแล้ว`, { level: 'warning', duration: 8000, action: { label: 'ย้อน', onClick: () => { setState(snapshot); window.toast('ยกเลิกการปฏิเสธแล้ว', { level: 'info' }); } } });
  };

  const exportCSV = () => {
    const rows = [['ID', 'ประเภท', 'หัวข้อ', 'ผู้ขอ', 'แผนก', 'ยอด', 'ขั้นปัจจุบัน', 'ผู้พิจารณา', 'วันสร้าง', 'ครบกำหนด', 'สถานะ SLA']];
    list.forEach(r => {
      const u = state.users[r.requester]; const approver = state.users[r.flow[r.currentStep]?.userId];
      const sla = slaInfo(r.dueDate);
      rows.push([r.id, TYPE_LABEL[r.type]?.th || r.type, r.title, u?.name || '', u?.dept || '', r.amount || 0, `${r.currentStep + 1}/${r.flow.length} ${r.flow[r.currentStep]?.role || ''}`, approver?.name || '', r.createdAt, r.dueDate, sla?.label || '']);
    });
    downloadCSV(`รออนุมัติ-${nowTh().replace(/[/:\s]/g, '-')}.csv`, rows);
  };

  return (
    <div>
      <div className="page-head">
        <div><h1 className="page-title">รออนุมัติ</h1><div className="page-sub">{mine.length > 0 ? <>มี <span style={{color:'var(--red-ink)'}} className="medium">{mine.length}</span> รายการรออนุมัติของคุณ</> : 'ไม่มีคำขอรออนุมัติของคุณ'}</div></div>
        <div className="row gap-8">
          {selected.size > 0 && (<>
            <span className="text-sm muted">{selected.size} รายการ</span>
            <button className="btn btn-ghost btn-sm" onClick={() => setSelected(new Set())}>ยกเลิก</button>
            <button className="btn btn-danger btn-sm" onClick={() => setRejectModal(true)}><Icon name="x" size={13} /> ปฏิเสธ</button>
            <button className="btn btn-success btn-sm" onClick={bulkApprove}><Icon name="check" size={13} /> อนุมัติทั้งหมด</button>
          </>)}
          <button className="btn btn-outline btn-sm" onClick={exportCSV} disabled={list.length === 0}><Icon name="download" size={13} /> ส่งออก CSV</button>
        </div>
      </div>
      <div className="row spread mb-12">
        <div className="tabs" style={{ margin: 0 }}>
          <button className={`tab ${filter === 'mine' ? 'active' : ''}`} onClick={() => setFilter('mine')}>ของฉัน <span className="tab-count">{mine.length}</span></button>
          {mineUrgent.length > 0 && <button className={`tab ${filter === 'urgent' ? 'active' : ''}`} onClick={() => setFilter('urgent')} style={{ color: 'var(--red-ink)', fontWeight: 600 }}>⚡ ด่วน <span className="tab-count" style={{ background: 'var(--red)', color: 'white' }}>{mineUrgent.length}</span></button>}
          <button className={`tab ${filter === 'all' ? 'active' : ''}`} onClick={() => setFilter('all')}>ทั้งหมด <span className="tab-count">{all.length}</span></button>
        </div>
        <div className="row gap-6">
          <span className="text-xs muted">เรียงตาม:</span>
          <select className="select" style={{ height: 30, fontSize: 12, width: 130 }} value={sortBy} onChange={e => setSortBy(e.target.value)}>
            <option value="urgency">ความเร่งด่วน (SLA)</option>
            <option value="priority">ระดับ Priority</option>
            <option value="amount">ยอดเงิน</option>
            <option value="created">วันที่สร้าง</option>
          </select>
        </div>
      </div>
      <div className="card" style={{ overflow: 'hidden' }}>
        {list.length === 0 ? <div style={{ padding: 40 }}><Empty icon="check" title="ไม่มีคำขอรออนุมัติ" sub="ทุกอย่างเดินหน้าได้" /></div> : (
          <table className="table"><thead><tr>
            <th style={{ width: 36 }}><input type="checkbox" checked={selected.size > 0 && selected.size === list.filter(r => canApproveStep(r.flow[r.currentStep], currentUser.id)).length} onChange={() => { const mine = list.filter(r => canApproveStep(r.flow[r.currentStep], currentUser.id)); if (selected.size === mine.length && mine.length > 0) setSelected(new Set()); else setSelected(new Set(mine.map(r => r.id))); }} title="เลือกเฉพาะรายการที่คุณมีสิทธิ์อนุมัติ" /></th>
            <th>คำขอ</th><th>ผู้ขอ</th><th>ประเภท</th><th>ยอด</th><th>ขั้น</th><th>ครบกำหนด · SLA</th><th></th>
          </tr></thead><tbody>
            {(() => {
              const renderRow = (r, opts = {}) => {
                const u = state.users[r.requester];
                const isUrgent = r.priority === 'high' || r.priority === 'critical';
                return (
                  <tr key={r.id} className="clickable" onClick={() => setState({ route: 'detail', selectedId: r.id })} style={{ background: isUrgent ? 'color-mix(in oklch, var(--red) 5%, var(--surface))' : undefined, borderLeft: isUrgent ? '3px solid var(--red)' : undefined }}>
                    <td onClick={(e) => e.stopPropagation()}><input type="checkbox" checked={selected.has(r.id)} onChange={() => toggleSelected(r.id)} /></td>
                    <td><div className="row gap-12"><TypeIcon type={r.type} size={28} /><div><div className="row gap-8"><span className="en tnum text-xs muted">{r.id}</span>{isUrgent && <span style={{ fontSize: 11, color: 'var(--red-ink)', fontWeight: 700, display: 'inline-flex', alignItems: 'center', gap: 2 }}><Icon name="flame" size={11} /> {r.priority === 'critical' ? 'วิกฤต' : 'เร่งด่วน'}{r.autoUrgent && ' ⚡'}</span>}</div><div className="medium" style={{ fontSize: 13 }}>{r.title}</div></div></div></td>
                    <td><div className="row gap-8"><Avatar user={u} size="sm" /><div className="text-sm">{u?.name.split(' ')[0]}</div></div></td>
                    <td><TypeBadge type={r.type} /></td>
                    <td className="num-cell">{fmtBaht(r.amount)}</td>
                    <td className="num-cell text-sm"><div>{r.currentStep + 1}/{r.flow.length}</div><div className="text-xs muted">{r.flow[r.currentStep]?.role}</div></td>
                    <td className="text-sm"><div className="col gap-2"><span className="num-cell">{r.dueDate}</span><SLABadge dueDate={r.dueDate} compact /></div></td>
                    <td><Icon name="chevronRight" size={14} className="muted-2" /></td>
                  </tr>
                );
              };
              const urgentList = list.filter(r => r.priority === 'high' || r.priority === 'critical');
              const normalList = list.filter(r => !(r.priority === 'high' || r.priority === 'critical'));
              const split = filter !== 'urgent' && urgentList.length > 0 && normalList.length > 0;
              if (!split) return list.map(r => renderRow(r));
              return (
                <>
                  <tr><td colSpan={8} style={{ background: 'var(--red)', color: 'white', padding: '8px 12px', fontSize: 12, fontWeight: 700 }}>⚡ ด่วน · {urgentList.length}</td></tr>
                  {urgentList.map(r => renderRow(r))}
                  <tr><td colSpan={8} style={{ background: 'var(--ink-3)', color: 'white', padding: '8px 12px', fontSize: 12, fontWeight: 700 }}>ปกติ · {normalList.length}</td></tr>
                  {normalList.map(r => renderRow(r))}
                </>
              );
            })()}
          </tbody></table>
        )}
      </div>

      <Modal open={rejectModal} onClose={() => setRejectModal(false)} title={`ปฏิเสธคำขอ ${selected.size} รายการ`}
        footer={<><button className="btn btn-outline" onClick={() => setRejectModal(false)}>ยกเลิก</button><button className="btn btn-danger" onClick={bulkReject} disabled={!rejectReason.trim()}><Icon name="x" size={13} /> ยืนยันปฏิเสธ</button></>}>
        <div className="col gap-12">
          <div className="alert alert-amber"><Icon name="warning" size={14} style={{ marginTop: 1 }} /><div className="text-sm">คำขอที่ปฏิเสธจะถูกตีกลับให้ผู้ขอแก้ไข — กรุณาระบุเหตุผลให้ชัดเจน</div></div>
          <div className="field"><label className="field-label">เหตุผล <span className="req">*</span></label>
            <textarea className="textarea" placeholder="ระบุเหตุผลในการปฏิเสธทั้งหมด..." value={rejectReason} onChange={e => setRejectReason(e.target.value)} style={{ minHeight: 100 }} />
          </div>
        </div>
      </Modal>
    </div>
  );
};

const MyRequestsPage = ({ ctx }) => {
  const { state, setState, currentUser } = ctx;
  const [filter, setFilter] = usePersistedState('myreq.status', 'all');
  const [type, setType] = usePersistedState('myreq.type', 'all');
  const [search, setSearch] = React.useState('');
  const [compareIds, setCompareIds] = React.useState([]);
  const [compareOpen, setCompareOpen] = React.useState(false);
  // Advanced filters
  const [dateFrom, setDateFrom] = React.useState('');
  const [dateTo, setDateTo] = React.useState('');
  const [amountMin, setAmountMin] = React.useState('');
  const [amountMax, setAmountMax] = React.useState('');
  const [sortBy, setSortBy] = usePersistedState('myreq.sortBy', 'newest');
  const [advancedOpen, setAdvancedOpen] = React.useState(false);
  let list = state.requests.filter(r => r.requester === currentUser.id);
  if (filter === 'urgent') list = list.filter(r => (r.priority === 'high' || r.priority === 'critical') && (r.status === 'pending' || r.status === 'progress'));
  else if (filter !== 'all') list = list.filter(r => r.status === filter);
  if (type !== 'all') list = list.filter(r => r.type === type);
  if (search.trim()) {
    const q = search.toLowerCase();
    list = list.filter(r => (r.id + r.title + (r.purpose || '')).toLowerCase().includes(q));
  }
  // Date range filter (on createdAt)
  if (dateFrom) {
    const fd = new Date(dateFrom);
    list = list.filter(r => { const d = parseTh(r.createdAt); return d && d >= fd; });
  }
  if (dateTo) {
    const td = new Date(dateTo); td.setHours(23, 59, 59, 999);
    list = list.filter(r => { const d = parseTh(r.createdAt); return d && d <= td; });
  }
  // Amount range filter
  if (amountMin !== '') list = list.filter(r => (r.amount || 0) >= Number(amountMin));
  if (amountMax !== '') list = list.filter(r => (r.amount || 0) <= Number(amountMax));
  // Sort
  const sortedList = [...list].sort((a, b) => {
    if (sortBy === 'newest') { const ad = parseTh(a.createdAt)?.getTime() || 0; const bd = parseTh(b.createdAt)?.getTime() || 0; return bd - ad; }
    if (sortBy === 'oldest') { const ad = parseTh(a.createdAt)?.getTime() || 0; const bd = parseTh(b.createdAt)?.getTime() || 0; return ad - bd; }
    if (sortBy === 'amount-desc') return (b.amount || 0) - (a.amount || 0);
    if (sortBy === 'amount-asc') return (a.amount || 0) - (b.amount || 0);
    if (sortBy === 'deadline') { const ad = parseTh(a.dueDate)?.getTime() || Infinity; const bd = parseTh(b.dueDate)?.getTime() || Infinity; return ad - bd; }
    if (sortBy === 'priority') {
      const w = { critical: 4, high: 3, normal: 2, low: 1 };
      return (w[b.priority] || 0) - (w[a.priority] || 0);
    }
    return 0;
  });
  list = sortedList;
  const activeFilters = [filter !== 'all', type !== 'all', search.trim(), dateFrom, dateTo, amountMin, amountMax].filter(Boolean).length;
  const clearFilters = () => { setFilter('all'); setType('all'); setSearch(''); setDateFrom(''); setDateTo(''); setAmountMin(''); setAmountMax(''); };

  const toggleCompare = (id) => {
    setCompareIds(prev => prev.includes(id) ? prev.filter(x => x !== id) : prev.length >= 3 ? prev : [...prev, id]);
  };
  const compareReqs = compareIds.map(id => state.requests.find(r => r.id === id)).filter(Boolean);

  const counts = {
    all: state.requests.filter(r => r.requester === currentUser.id).length,
    urgent: state.requests.filter(r => r.requester === currentUser.id && (r.priority === 'high' || r.priority === 'critical') && (r.status === 'pending' || r.status === 'progress')).length,
    pending: state.requests.filter(r => r.requester === currentUser.id && r.status === 'pending').length,
    progress: state.requests.filter(r => r.requester === currentUser.id && r.status === 'progress').length,
    rejected: state.requests.filter(r => r.requester === currentUser.id && r.status === 'rejected').length,
    revision: state.requests.filter(r => r.requester === currentUser.id && r.status === 'revision').length,
  };

  const exportCSV = () => {
    const rows = [['ID', 'ประเภท', 'หัวข้อ', 'ยอด', 'สถานะ', 'ขั้น', 'วันสร้าง', 'ครบกำหนด', 'SLA']];
    list.forEach(r => {
      const sla = slaInfo(r.dueDate);
      rows.push([r.id, TYPE_LABEL[r.type]?.th || r.type, r.title, r.amount || 0, STATUS_LABEL[r.status]?.th || r.status, `${r.currentStep + 1}/${r.flow.length}`, r.createdAt, r.dueDate, sla?.label || '']);
    });
    downloadCSV(`คำขอของฉัน-${nowTh().replace(/[/:\s]/g, '-')}.csv`, rows);
  };

  return (
    <div>
      <div className="page-head">
        <div><h1 className="page-title">คำขอของฉัน</h1><div className="page-sub">รายการคำขอที่คุณส่งเข้าระบบ — {counts.all} รายการทั้งหมด</div></div>
        <div className="row gap-8">
          {compareIds.length >= 2 && <button className="btn btn-primary btn-sm" onClick={() => setCompareOpen(true)}><Icon name="copy" size={13} /> เทียบ {compareIds.length}</button>}
          {compareIds.length > 0 && <button className="btn btn-ghost btn-sm" onClick={() => setCompareIds([])}>ยกเลิก</button>}
          <button className="btn btn-outline btn-sm" onClick={exportCSV} disabled={list.length === 0}><Icon name="download" size={13} /> CSV</button>
          <button className="btn btn-primary" onClick={() => setState({ createOpen: true })}><Icon name="plus" size={14} /> สร้างคำขอ</button>
        </div>
      </div>
      <div className="card card-pad mb-12">
        <div className="row gap-12 flex-wrap" style={{ alignItems: 'center' }}>
          <div className="search" style={{ flex: 1, minWidth: 200, maxWidth: 320 }}>
            <Icon name="search" size={14} className="search-icon" />
            <input value={search} onChange={e => setSearch(e.target.value)} placeholder="ค้นหา ID, หัวข้อ, รายละเอียด..." />
          </div>
          <select className="select" style={{ height: 32, fontSize: 12, padding: '0 10px', maxWidth: 200 }} value={sortBy} onChange={(e) => setSortBy(e.target.value)} title="เรียงลำดับ">
            <option value="newest">📅 ใหม่สุด</option>
            <option value="oldest">📅 เก่าสุด</option>
            <option value="amount-desc">฿ ยอดสูง→ต่ำ</option>
            <option value="amount-asc">฿ ยอดต่ำ→สูง</option>
            <option value="deadline">⏰ ครบกำหนดเร็วสุด</option>
            <option value="priority">⚡ ด่วนก่อน</option>
          </select>
          <button className={`btn btn-outline btn-sm ${advancedOpen || activeFilters > 0 ? '' : ''}`} onClick={() => setAdvancedOpen(!advancedOpen)} style={advancedOpen ? { background: 'var(--brand-soft)', borderColor: 'var(--brand)' } : {}}>
            <Icon name="filter" size={12} /> ตัวกรอง{activeFilters > 0 && <span className="badge badge-brand" style={{ marginLeft: 6 }}>{activeFilters}</span>}
          </button>
          {activeFilters > 0 && <button className="btn btn-ghost btn-sm" onClick={clearFilters} style={{ color: 'var(--red-ink)' }}><Icon name="x" size={11} /> ล้าง</button>}
          <span className="text-xs muted" style={{ marginLeft: 'auto' }}>{list.length} จาก {counts.all} รายการ</span>
        </div>
        {advancedOpen && (
          <div className="grid grid-4 mt-12" style={{ gap: 12, paddingTop: 12, borderTop: '1px solid var(--border)' }}>
            <div className="field">
              <label className="field-label">วันที่สร้าง — ตั้งแต่</label>
              <input type="date" className="input" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} />
            </div>
            <div className="field">
              <label className="field-label">วันที่สร้าง — ถึง</label>
              <input type="date" className="input" value={dateTo} onChange={(e) => setDateTo(e.target.value)} />
            </div>
            <div className="field">
              <label className="field-label">มูลค่า ตั้งแต่ (บาท)</label>
              <input type="number" className="input" value={amountMin} onChange={(e) => setAmountMin(e.target.value)} placeholder="0" />
            </div>
            <div className="field">
              <label className="field-label">มูลค่า ถึง (บาท)</label>
              <input type="number" className="input" value={amountMax} onChange={(e) => setAmountMax(e.target.value)} placeholder="∞" />
            </div>
          </div>
        )}
      </div>
      <div className="row gap-8 mb-16 flex-wrap">
        <span className="text-xs muted en" style={{ marginRight: 4 }}>STATUS</span>
        {[['all','ทั้งหมด',counts.all],['urgent','⚡ ด่วน',counts.urgent],['pending','รออนุมัติ',counts.pending],['revision','↩ ตีกลับ',counts.revision],['progress','กำลังดำเนินการ',counts.progress],['rejected','ปฏิเสธ',counts.rejected]].map(([k,lbl,n]) => {
          if ((k === 'urgent' || k === 'revision') && n === 0) return null;
          const isUrgentChip = k === 'urgent';
          return (
            <button key={k} className={`chip ${filter === k ? 'active' : ''}`} onClick={() => setFilter(k)} style={isUrgentChip ? { color: filter === k ? 'white' : 'var(--red-ink)', background: filter === k ? 'var(--red)' : undefined, borderColor: 'var(--red)' } : undefined}>{lbl}{n > 0 && <span className="en tnum" style={{ marginLeft: 5, opacity: 0.85 }}>{n}</span>}</button>
          );
        })}
        <span className="divider-v" style={{ height: 18, margin: '0 8px' }}></span>
        <span className="text-xs muted en" style={{ marginRight: 4 }}>TYPE</span>
        {[['all','ทั้งหมด'],['event','อีเว้นท์'],['general','อนุมัติทั่วไป'],['purchase','จัดซื้อ'],['overtime','OT'],['leave','ใบลา'],['withdrawal','เบิกตัดขาด'],['borrow','ยืม-คืน'],['expense','เบิกเงิน']].map(([k,lbl]) => (
          <button key={k} className={`chip ${type === k ? 'active' : ''}`} onClick={() => setType(k)}>{lbl}</button>
        ))}
      </div>
      <div className="card" style={{ overflow: 'hidden' }}>
        {list.length === 0 ? <div style={{ padding: 40 }}><Empty title="ไม่มีคำขอตามตัวกรอง" sub={search ? 'ลองเปลี่ยนคำค้นหา' : 'กดสร้างคำขอใหม่เพื่อเริ่ม'} /></div>
          : list.map(r => (
            <div key={r.id} style={{ display: 'flex', alignItems: 'stretch', borderBottom: '1px solid var(--border)' }}>
              <label style={{ padding: '0 14px', display: 'flex', alignItems: 'center', cursor: 'pointer', background: compareIds.includes(r.id) ? 'var(--brand-soft)' : 'transparent' }} onClick={(e) => e.stopPropagation()} title="เลือกเพื่อเปรียบเทียบ">
                <input type="checkbox" checked={compareIds.includes(r.id)} onChange={() => toggleCompare(r.id)} disabled={!compareIds.includes(r.id) && compareIds.length >= 3} />
              </label>
              <div style={{ flex: 1, minWidth: 0 }}>
                <RequestRow req={r} users={state.users} onClick={() => setState({ route: 'detail', selectedId: r.id })} showRequester={false} />
              </div>
            </div>
          ))
        }
      </div>

      <Modal open={compareOpen} onClose={() => setCompareOpen(false)} wide title={`เปรียบเทียบคำขอ (${compareReqs.length})`}
        footer={<><button className="btn btn-outline" onClick={() => setCompareOpen(false)}>ปิด</button><button className="btn btn-primary" onClick={() => { setCompareOpen(false); setCompareIds([]); }}>เคลียร์การเลือก</button></>}>
        <div style={{ overflowX: 'auto' }}>
          <table className="table">
            <thead><tr>
              <th>หัวข้อ</th>
              {compareReqs.map(r => <th key={r.id} style={{ minWidth: 220 }}><div className="col gap-4"><span className="en text-xs muted">{r.id}</span><TypeBadge type={r.type} /></div></th>)}
            </tr></thead>
            <tbody>
              <tr><td className="muted text-xs">ชื่อ</td>{compareReqs.map(r => <td key={r.id} className="medium text-sm">{r.title}</td>)}</tr>
              <tr><td className="muted text-xs">สถานะ</td>{compareReqs.map(r => <td key={r.id}><StatusBadge status={r.status} /></td>)}</tr>
              <tr><td className="muted text-xs">มูลค่า</td>{compareReqs.map(r => { const max = Math.max(...compareReqs.map(x => x.amount || 0)); const isMax = r.amount === max && max > 0; return <td key={r.id} className="num-cell" style={{ color: isMax ? 'var(--red-ink)' : 'var(--ink)', fontWeight: isMax ? 600 : 400 }}>{fmtBaht(r.amount)}{isMax && compareReqs.length > 1 && <span className="text-xs muted en"> (สูงสุด)</span>}</td>; })}</tr>
              <tr><td className="muted text-xs">วันสร้าง</td>{compareReqs.map(r => <td key={r.id} className="text-sm">{r.createdAt}</td>)}</tr>
              <tr><td className="muted text-xs">ครบกำหนด</td>{compareReqs.map(r => <td key={r.id} className="text-sm"><div className="col gap-2"><span>{r.dueDate}</span><SLABadge dueDate={r.dueDate} compact /></div></td>)}</tr>
              <tr><td className="muted text-xs">ขั้นปัจจุบัน</td>{compareReqs.map(r => <td key={r.id} className="text-sm">{r.currentStep + 1} / {r.flow.length}<div className="text-xs muted">{r.flow[r.currentStep]?.role}</div></td>)}</tr>
              <tr><td className="muted text-xs">ความเร่งด่วน</td>{compareReqs.map(r => <td key={r.id}>{r.priority === 'high' ? <span className="badge badge-red">เร่งด่วน</span> : <span className="text-xs muted">ปกติ</span>}</td>)}</tr>
              <tr><td className="muted text-xs">วัตถุประสงค์</td>{compareReqs.map(r => <td key={r.id} className="text-xs" style={{ verticalAlign: 'top' }}>{r.purpose}</td>)}</tr>
              <tr><td className="muted text-xs">เอกสารแนบ</td>{compareReqs.map(r => <td key={r.id} className="text-sm">{r.attachments} ไฟล์</td>)}</tr>
              <tr><td className="muted text-xs">ความคิดเห็น</td>{compareReqs.map(r => <td key={r.id} className="text-sm">{r.comments} ข้อความ</td>)}</tr>
            </tbody>
          </table>
        </div>
      </Modal>
    </div>
  );
};

Object.assign(window, { DashboardPage, ApprovalsPage, MyRequestsPage, RequestRow, DonutChart });
// ⟪AUTO-EXPORTS-START⟫
export { DashboardPage, DonutChart, RequestRow, ApprovalsPage, MyRequestsPage };
// ⟪AUTO-EXPORTS-END⟫
