// ⟪AUTO-HEADER-START⟫ generated by scripts/extract.mjs + gen-imports.mjs — do not edit this region by hand
import React from 'react';
import { MOCK } from '../data/mock.js';
import { Avatar, Empty, Icon, Modal, hashPassword } from '../lib/core.jsx';
// ⟪AUTO-HEADER-END⟫
const LEVEL_TH = { staff: 'พนักงาน', head: 'หัวหน้า', manager: 'ผู้จัดการ', director: 'ผู้อำนวยการ' };
const LEVEL_ORDER = { director: 0, manager: 1, head: 2, staff: 3 };
const DEPT_PREFIX = {
  accounting: 'ACC', marketing: 'MKT', callcenter: 'CC',
  warehouse: 'WH', procurement: 'PC', office: 'OA', hr: 'HR',
  sales: 'SA', events: 'EM'
};

const PeoplePage = ({ ctx, hideHead = false }) => {
  const { state, setState } = ctx;
  const DEPTS = MOCK.DEPTS;
  const [showAdd, setShowAdd] = React.useState(false);
  const [showDemo, setShowDemo] = React.useState(false);
  const [showAllPwd, setShowAllPwd] = React.useState(false);
  const empFileRef = React.useRef(null);

  // ===== CSV Import พนักงาน =====
  const parseCSVEmp = (text) => {
    const lines = text.replace(/^﻿/, '').split(/\r?\n/).filter(l => l.trim());
    if (lines.length < 2) return [];
    const headers = lines[0].split(',').map(h => h.trim().toLowerCase());
    return lines.slice(1).map(line => {
      const cells = [];
      let cur = '', inQ = false;
      for (let i = 0; i < line.length; i++) {
        const ch = line[i];
        if (ch === '"' && line[i+1] === '"') { cur += '"'; i++; }
        else if (ch === '"') { inQ = !inQ; }
        else if (ch === ',' && !inQ) { cells.push(cur); cur = ''; }
        else { cur += ch; }
      }
      cells.push(cur);
      const obj = {};
      headers.forEach((h, i) => { obj[h] = (cells[i] || '').trim(); });
      return obj;
    });
  };

  const importEmpCSV = (file) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const rows = parseCSVEmp(e.target.result);
        if (rows.length === 0) { window.toast?.('CSV ว่างหรือไม่มี header', { level: 'warning' }); return; }
        const validDepts = Object.keys(DEPTS);
        const validLevels = ['staff','head','manager','director'];
        let added = 0, skipped = 0;
        const newUsers = { ...state.users };
        rows.forEach(r => {
          if (!r.name) { skipped++; return; }
          const deptKey = (r.dept || 'office').toLowerCase();
          if (!validDepts.includes(deptKey)) { skipped++; return; }
          const level = (r.level || 'staff').toLowerCase();
          if (!validLevels.includes(level)) { skipped++; return; }
          // Generate ID
          const prefix = DEPT_PREFIX[deptKey];
          const existing = Object.values(newUsers).filter(u => u.id.startsWith(prefix + '-')).map(u => parseInt(u.id.split('-')[1], 10) || 0);
          const n = (existing.length ? Math.max(...existing) : 0) + 1;
          const id = `${prefix}-${String(n).padStart(3, '0')}`;
          const parts = r.name.trim().split(/\s+/);
          const initials = (parts[0]?.[0] || '') + (parts[1]?.[0] || parts[0]?.[1] || '');
          newUsers[id] = {
            id, name: r.name.trim(), initials, deptKey, dept: DEPTS[deptKey].th,
            level, role: { staff: 'Staff', head: 'Head', manager: 'Manager', director: 'Director' }[level],
            roleTh: r.roleth || r.role || `${LEVEL_TH[level]}${DEPTS[deptKey].th}`,
            color: MOCK.deptColor(deptKey),
            startDate: r.startdate || '2026-06-03',
            email: r.email || id.toLowerCase().replace(/-/g, '') + '@flowdesk.co',
            phone: r.phone || '',
            passwordHash: r.password ? hashPassword(r.password) : ''
          };
          added++;
        });
        setState({ users: newUsers });
        window.toast?.(`Import พนักงาน: เพิ่ม ${added}${skipped ? ` · ข้าม ${skipped}` : ''}`, { level: 'success', duration: 6000 });
      } catch (err) { window.toast?.('ไม่สามารถอ่านไฟล์: ' + err.message, { level: 'error' }); }
    };
    reader.readAsText(file, 'utf-8');
  };

  const downloadEmpTemplate = () => {
    const csv = '﻿name,dept,level,roleTh,email,phone,password\nสมชาย ใจดี,marketing,staff,พนักงานการตลาด,somchai@company.com,0812345678,1234\nสมหญิง ขยัน,hr,head,หัวหน้าบุคคล,somying@company.com,0823456789,\n';
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'employees-template.csv'; a.click();
  };
  const [lastAdded, setLastAdded] = React.useState(null);
  const [search, setSearch] = React.useState('');
  const [deptFilter, setDeptFilter] = React.useState('all');
  const [pwdTarget, setPwdTarget] = React.useState(null);

  React.useEffect(() => {
    if (!lastAdded) return;
    const t = setTimeout(() => setLastAdded(null), 4000);
    return () => clearTimeout(t);
  }, [lastAdded]);

  const all = Object.values(state.users);
  let list = all;
  if (deptFilter !== 'all') list = list.filter(u => u.deptKey === deptFilter);
  if (search) {
    const q = search.toLowerCase();
    list = list.filter(u => (u.name + u.roleTh + u.id).toLowerCase().includes(q));
  }

  const grouped = {};
  list.forEach(u => { (grouped[u.deptKey] = grouped[u.deptKey] || []).push(u); });
  Object.values(grouped).forEach(arr => arr.sort((a, b) => (LEVEL_ORDER[a.level] ?? 9) - (LEVEL_ORDER[b.level] ?? 9)));

  const addEmployee = (data) => {
    const prefix = DEPT_PREFIX[data.deptKey];
    const existing = all.filter(u => u.id.startsWith(prefix + '-')).map(u => parseInt(u.id.split('-')[1], 10) || 0);
    const n = (existing.length ? Math.max(...existing) : 0) + 1;
    const id = `${prefix}-${String(n).padStart(3, '0')}`;
    const parts = data.name.trim().split(/\s+/);
    const initials = (parts[0]?.[0] || '') + (parts[1]?.[0] || parts[0]?.[1] || '');
    const user = {
      id, name: data.name.trim(), initials,
      deptKey: data.deptKey, dept: DEPTS[data.deptKey].th,
      level: data.level, role: { staff: 'Staff', head: 'Head', manager: 'Manager', director: 'Director' }[data.level],
      roleTh: data.roleTh || `${LEVEL_TH[data.level]}${DEPTS[data.deptKey].th}`,
      color: MOCK.deptColor(data.deptKey),
      startDate: '2026-06-03', email: id.toLowerCase().replace(/-/g, '') + '@flowdesk.co',
      passwordHash: data.passwordHash || '' // ตั้งรหัสตอนสร้างเลย
    };
    setState({ users: { ...state.users, [id]: user } });
    window.toast?.(`เพิ่ม ${user.name} (${id}) เรียบร้อย${data.passwordHash ? ' · login ได้ทันที' : ''}`, { level: 'success', duration: 6000 });
    setShowAdd(false);
    setLastAdded(id);
    setDeptFilter(data.deptKey);
    setSearch('');
  };

  return (
    <div>
      {!hideHead && (
        <div className="page-head">
          <div>
            <h1 className="page-title">พนักงาน</h1>
            <div className="page-sub">รายชื่อพนักงานทั้งหมด {all.length} คน · {Object.keys(DEPTS).length} แผนก</div>
          </div>
          <div className="row gap-8">
            <input ref={empFileRef} type="file" accept=".csv" style={{ display: 'none' }} onChange={(e) => { const f = e.target.files?.[0]; if (f) importEmpCSV(f); e.target.value = ''; }} />
            <button className="btn btn-outline" onClick={downloadEmpTemplate} title="ดาวน์โหลด CSV template"><Icon name="download" size={14} /> Template</button>
            <button className="btn btn-outline" onClick={() => empFileRef.current?.click()}><Icon name="upload" size={14} /> Import CSV</button>
            <button className="btn btn-outline" onClick={() => setShowDemo(true)} title="ดูรายชื่อ + รหัสผ่านที่ใช้ทดลอง login ได้"><Icon name="shield" size={14} /> รหัส Login ทดลอง</button>
            <button className="btn btn-primary" onClick={() => setShowAdd(true)}>
              <Icon name="plus" size={14} /> เพิ่มพนักงาน
            </button>
          </div>
        </div>
      )}
      {hideHead && (
        <div className="row spread mb-16 flex-wrap">
          <div className="text-sm muted">พนักงานทั้งหมด {all.length} คน · {Object.keys(DEPTS).length} แผนก</div>
          <div className="row gap-6 flex-wrap">
            <input ref={empFileRef} type="file" accept=".csv" style={{ display: 'none' }} onChange={(e) => { const f = e.target.files?.[0]; if (f) importEmpCSV(f); e.target.value = ''; }} />
            <button className="btn btn-outline btn-sm" onClick={downloadEmpTemplate}><Icon name="download" size={13} /> Template</button>
            <button className="btn btn-outline btn-sm" onClick={() => empFileRef.current?.click()}><Icon name="upload" size={13} /> Import CSV</button>
            <button className="btn btn-outline btn-sm" onClick={() => setShowDemo(true)}><Icon name="shield" size={13} /> รหัส Login ทดลอง</button>
            <button className="btn btn-primary btn-sm" onClick={() => setShowAdd(true)}>
              <Icon name="plus" size={13} /> เพิ่มพนักงาน
            </button>
          </div>
        </div>
      )}

      <div className="alert alert-green mb-16">
        <Icon name="zap" size={16} style={{ marginTop: 1 }} />
        <div className="flex-1">
          <div className="medium">อัปเดตแบบเรียลไทม์</div>
          <div className="text-xs mt-2">เพิ่ม/แก้ไขพนักงานแล้วรายชื่อจะปรากฏทันที — ไม่ต้องกดรีเฟรชหน้าอีกต่อไป</div>
        </div>
      </div>

      <div className="card card-pad mb-16">
        <div className="row gap-12 flex-wrap">
          <div className="search" style={{ flex: 1, maxWidth: 300 }}>
            <Icon name="search" size={14} className="search-icon" />
            <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ค้นหาชื่อ, ตำแหน่ง, รหัส..." />
          </div>
          <button className={`chip ${deptFilter === 'all' ? 'active' : ''}`} onClick={() => setDeptFilter('all')}>ทุกแผนก</button>
          {Object.values(DEPTS).map(d => (
            <button key={d.key} className={`chip ${deptFilter === d.key ? 'active' : ''}`} onClick={() => setDeptFilter(d.key)}>{d.th}</button>
          ))}
        </div>
      </div>

      {Object.keys(grouped).length === 0 && (
        <div className="card"><div style={{ padding: 40 }}><Empty icon="users" title="ไม่พบพนักงานตามตัวกรอง" /></div></div>
      )}
      <div className="col gap-16">
        {Object.values(DEPTS).filter(d => grouped[d.key]).map(d => (
          <div className="card" key={d.key} style={{ overflow: 'hidden' }}>
            <div className="card-head">
              <div className="row gap-8">
                <span style={{ width: 10, height: 10, borderRadius: 3, background: MOCK.deptColor(d.key, 65, 0.13), display: 'inline-block' }}></span>
                <h3 className="card-title">{d.th}</h3>
                <span className="text-xs muted">{grouped[d.key].length} คน</span>
              </div>
            </div>
            <table className="table">
              <thead>
                <tr>
                  <th>ชื่อ</th>
                  <th>ตำแหน่ง</th>
                  <th>ระดับ</th>
                  <th>รหัส</th>
                  <th className="center">รหัสผ่าน</th>
                </tr>
              </thead>
              <tbody>
                {grouped[d.key].map(u => (
                  <tr key={u.id} style={u.id === lastAdded ? { background: 'var(--green-soft)', transition: 'background 0.4s' } : undefined}>
                    <td>
                      <div className="row gap-10">
                        <Avatar user={u} size="sm" />
                        <span className="medium text-sm">{u.name}</span>
                        {u.id === lastAdded && <span className="badge badge-green"><Icon name="check" size={10} /> เพิ่มใหม่</span>}
                      </div>
                    </td>
                    <td className="text-sm">{u.roleTh}</td>
                    <td>
                      <span className="badge no-dot" style={{ color: 'var(--ink-2)' }}>{LEVEL_TH[u.level] || u.level}</span>
                    </td>
                    <td className="num-cell text-xs muted">{u.id}</td>
                    <td className="center">
                      {u.passwordHash ? (
                        <div className="row gap-4" style={{ justifyContent: 'center' }}>
                          <span className="badge badge-green">🔒 ตั้งแล้ว</span>
                          <button className="btn btn-ghost btn-sm" onClick={() => setPwdTarget(u)} title="เปลี่ยนรหัส"><Icon name="edit" size={11} /></button>
                          <button className="btn btn-ghost btn-sm" style={{ color: 'var(--red-ink)' }} onClick={() => {
                            if (!confirm(`ลบรหัสผ่านของ ${u.name}?`)) return;
                            const newUsers = { ...state.users, [u.id]: { ...u, passwordHash: '' } };
                            setState({ users: newUsers });
                            window.toast(`ลบรหัสของ ${u.name} แล้ว`, { level: 'info' });
                          }} title="ลบรหัส"><Icon name="trash" size={11} /></button>
                        </div>
                      ) : (
                        <button className="btn btn-outline btn-sm" onClick={() => setPwdTarget(u)}><Icon name="plus" size={11} /> ตั้งรหัสผ่าน</button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ))}
      </div>

      <AddEmployeeModal open={showAdd} onClose={() => setShowAdd(false)} onAdd={addEmployee} DEPTS={DEPTS} />

      {/* Demo Login Credentials Modal */}
      <Modal open={showDemo} onClose={() => setShowDemo(false)} wide title="🔐 รหัสทดลอง Login"
        footer={
          <>
            <button className="btn btn-outline" onClick={() => setShowDemo(false)}>ปิด</button>
            <button className="btn btn-primary" onClick={() => {
              // ตั้งรหัส 1234 ให้ user ที่ยังไม่มีรหัส (ทุกคน)
              if (!confirm('ตั้งรหัสผ่าน "1234" ให้พนักงานทุกคนที่ยังไม่ได้ตั้ง? (ใช้สำหรับทดลองเท่านั้น — ไม่กระทบคนที่ตั้งรหัสเองไว้แล้ว)')) return;
              const updated = { ...state.users };
              let count = 0;
              Object.keys(updated).forEach(uid => {
                if (!updated[uid].passwordHash) {
                  updated[uid] = { ...updated[uid], passwordHash: hashPassword('1234') };
                  count++;
                }
              });
              setState({ users: updated });
              window.toast?.(`ตั้งรหัส "1234" ให้ ${count} คนเรียบร้อย — ทุกคน login ได้แล้ว`, { level: 'success', duration: 6000 });
            }}><Icon name="zap" size={13} /> ตั้งรหัส "1234" ให้ทุกคน (Quick Demo)</button>
          </>
        }>
        <div className="col gap-12">
          <div className="alert alert-info">
            <Icon name="info" size={14} style={{ marginTop: 1 }} />
            <div className="text-xs flex-1">
              <div className="medium mb-2">วิธีใช้</div>
              <ul style={{ margin: 0, paddingLeft: 18, lineHeight: 1.7 }}>
                <li>กดปุ่ม <span className="medium">"ตั้งรหัส 1234 ให้ทุกคน"</span> ด้านล่าง → ทุกคนใช้รหัส <span className="medium" style={{ fontFamily: 'monospace' }}>1234</span> login ได้ทันที</li>
                <li>คนที่ตั้งรหัสเองไว้แล้ว → ไม่กระทบ ใช้รหัสเดิม</li>
                <li>ปุ่ม <span className="medium">"แสดงรหัสผ่านทั้งหมด"</span> = unmask รหัสที่ตั้งไว้แล้ว (ใช้ตอน demo)</li>
                <li>ใน production ให้พนักงานแต่ละคนเปลี่ยนรหัสของตัวเอง</li>
              </ul>
            </div>
          </div>

          <div className="row spread">
            <span className="medium">บัญชีในระบบ ({Object.keys(state.users).length})</span>
            <button className="btn btn-ghost btn-sm" onClick={() => setShowAllPwd(s => !s)}>
              <Icon name={showAllPwd ? 'x' : 'shield'} size={11} /> {showAllPwd ? 'ซ่อนรหัส' : 'แสดงรหัสผ่าน (debug)'}
            </button>
          </div>

          <div style={{ maxHeight: 460, overflowY: 'auto', border: '1px solid var(--border)', borderRadius: 8 }}>
            <table className="table table-compact">
              <thead style={{ position: 'sticky', top: 0, background: 'var(--surface-2)', zIndex: 1 }}>
                <tr>
                  <th>ID</th>
                  <th>ชื่อ</th>
                  <th>แผนก</th>
                  <th>ระดับ</th>
                  <th>สถานะรหัส</th>
                  {showAllPwd && <th>รหัสผ่าน</th>}
                </tr>
              </thead>
              <tbody>
                {Object.values(state.users).sort((a, b) => a.deptKey.localeCompare(b.deptKey) || a.id.localeCompare(b.id)).map(u => {
                  // เช็คว่าใช้รหัส 1234 มั้ย
                  const is1234 = u.passwordHash === hashPassword('1234');
                  return (
                    <tr key={u.id}>
                      <td><span className="en tnum text-xs">{u.id}</span></td>
                      <td><div className="row gap-6"><Avatar user={u} size="sm" /><span className="text-sm">{u.name}</span></div></td>
                      <td><span className="text-xs">{u.dept}</span></td>
                      <td><span className="badge badge-ghost">{LEVEL_TH[u.level] || u.level}</span></td>
                      <td>
                        {u.passwordHash
                          ? (is1234 ? <span className="badge badge-amber">demo: 1234</span> : <span className="badge badge-green"><Icon name="check" size={9} /> ตั้งแล้ว</span>)
                          : <span className="badge badge-red">ยังไม่ได้ตั้ง</span>}
                      </td>
                      {showAllPwd && (
                        <td>
                          {is1234 ? <span style={{ fontFamily: 'monospace', color: 'var(--amber-ink)' }}>1234</span>
                            : u.passwordHash ? <span className="text-xs muted" style={{ fontStyle: 'italic' }}>(hashed — ดูไม่ได้)</span>
                              : <span className="text-xs muted">—</span>}
                        </td>
                      )}
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          <div className="alert alert-amber">
            <Icon name="warning" size={14} style={{ marginTop: 1 }} />
            <div className="text-xs flex-1">⚠️ รหัส "1234" ใช้สำหรับ <span className="medium">ทดลองเท่านั้น</span> · ตอน deploy จริงให้บอกพนักงานแต่ละคนเข้าไปเปลี่ยนรหัสของตัวเองที่ Settings → ทีมงาน → กดที่ชื่อ → ตั้งรหัสผ่าน</div>
          </div>
        </div>
      </Modal>
      <SetPasswordModal target={pwdTarget} onClose={() => setPwdTarget(null)} onSet={(uid, hash) => {
        const u = state.users[uid];
        const newUsers = { ...state.users, [uid]: { ...u, passwordHash: hash } };
        setState({ users: newUsers });
        setPwdTarget(null);
        window.toast(`ตั้งรหัสผ่านของ ${u.name} แล้ว`, { level: 'success' });
      }} />
    </div>
  );
};

const SetPasswordModal = ({ target, onClose, onSet }) => {
  const [pwd, setPwd] = React.useState('');
  const [pwd2, setPwd2] = React.useState('');
  const [showPwd, setShowPwd] = React.useState(false);
  const [err, setErr] = React.useState('');
  React.useEffect(() => { if (target) { setPwd(''); setPwd2(''); setErr(''); setShowPwd(false); } }, [target?.id]);
  const submit = () => {
    setErr('');
    if (pwd.length < 4) { setErr('รหัสต้องมีอย่างน้อย 4 ตัวอักษร'); return; }
    if (pwd !== pwd2) { setErr('รหัสไม่ตรงกัน'); return; }
    onSet(target.id, hashPassword(pwd));
  };
  if (!target) return null;
  return (
    <Modal open={!!target} onClose={onClose} title={`ตั้งรหัสผ่าน — ${target.name}`}
      footer={<><button className="btn btn-outline" onClick={onClose}>ยกเลิก</button><button className="btn btn-primary" onClick={submit} disabled={!pwd || !pwd2}><Icon name="check" size={13} /> บันทึก</button></>}>
      <div className="col gap-12">
        <div className="alert alert-info">
          <Icon name="info" size={14} style={{ marginTop: 1 }} />
          <div className="text-xs flex-1">{target.passwordHash ? 'เปลี่ยนรหัสผ่านใหม่' : 'ตั้งรหัสผ่านครั้งแรก'} — ผู้ใช้ต้องใส่รหัสนี้เพื่อ login · เก็บใน localStorage (ไม่ใช่ cloud)</div>
        </div>
        <div className="field">
          <label className="field-label">รหัสผ่านใหม่ <span className="req">*</span></label>
          <div className="row gap-6">
            <input className="input" type={showPwd ? 'text' : 'password'} value={pwd} onChange={(e) => { setPwd(e.target.value); setErr(''); }} placeholder="อย่างน้อย 4 ตัวอักษร" autoFocus />
            <button type="button" className="btn btn-outline btn-sm" onClick={() => setShowPwd(s => !s)} style={{ height: 38 }}>{showPwd ? 'ซ่อน' : 'แสดง'}</button>
          </div>
        </div>
        <div className="field">
          <label className="field-label">ยืนยันรหัสผ่าน <span className="req">*</span></label>
          <input className="input" type={showPwd ? 'text' : 'password'} value={pwd2} onChange={(e) => { setPwd2(e.target.value); setErr(''); }} placeholder="พิมพ์ซ้ำ" />
        </div>
        {err && <div className="alert alert-red"><Icon name="warning" size={14} style={{ marginTop: 1 }} /><div className="text-xs flex-1">{err}</div></div>}
      </div>
    </Modal>
  );
};

const AddEmployeeModal = ({ open, onClose, onAdd, DEPTS }) => {
  const [form, setForm] = React.useState({ name: '', deptKey: 'marketing', level: 'staff', roleTh: '', password: '', password2: '' });
  const [showPwd, setShowPwd] = React.useState(false);
  const [err, setErr] = React.useState('');
  const update = (patch) => setForm(f => ({ ...f, ...patch }));

  React.useEffect(() => {
    if (open) { setForm({ name: '', deptKey: 'marketing', level: 'staff', roleTh: '', password: '', password2: '' }); setErr(''); setShowPwd(false); }
  }, [open]);

  const suggestRole = `${LEVEL_TH[form.level]}${DEPTS[form.deptKey].th}`;
  const valid = form.name.trim().length > 1 && form.password.length >= 4 && form.password === form.password2;

  const submit = () => {
    setErr('');
    if (form.name.trim().length < 2) { setErr('กรุณาใส่ชื่อ-นามสกุล'); return; }
    if (form.password.length < 4) { setErr('รหัสผ่านต้องอย่างน้อย 4 ตัวอักษร'); return; }
    if (form.password !== form.password2) { setErr('รหัสผ่านไม่ตรงกัน'); return; }
    onAdd({ ...form, roleTh: form.roleTh.trim() || suggestRole, passwordHash: hashPassword(form.password) });
  };
  const genPwd = () => {
    const p = Math.random().toString(36).slice(2, 8); // 6-char random
    update({ password: p, password2: p });
    setShowPwd(true);
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="เพิ่มพนักงานใหม่"
      footer={
        <>
          <button className="btn btn-outline" onClick={onClose}>ยกเลิก</button>
          <button className="btn btn-primary" disabled={!valid} onClick={submit}>
            <Icon name="check" size={14} /> เพิ่มพนักงาน
          </button>
        </>
      }
    >
      <div className="col gap-16">
        <div className="field">
          <label className="field-label">ชื่อ-นามสกุล <span className="req">*</span></label>
          <input className="input" value={form.name} onChange={(e) => update({ name: e.target.value })} placeholder="เช่น สมชาย ใจดี" autoFocus />
        </div>
        <div className="grid grid-2">
          <div className="field">
            <label className="field-label">แผนก</label>
            <select className="select" value={form.deptKey} onChange={(e) => update({ deptKey: e.target.value })}>
              {Object.values(DEPTS).map(d => <option key={d.key} value={d.key}>{d.th}</option>)}
            </select>
          </div>
          <div className="field">
            <label className="field-label">ระดับ</label>
            <select className="select" value={form.level} onChange={(e) => update({ level: e.target.value })}>
              <option value="staff">พนักงาน</option>
              <option value="head">หัวหน้า</option>
              <option value="manager">ผู้จัดการ</option>
              <option value="director">ผู้อำนวยการ</option>
            </select>
          </div>
        </div>
        <div className="field">
          <label className="field-label">ตำแหน่ง (ไทย)</label>
          <input className="input" value={form.roleTh} onChange={(e) => update({ roleTh: e.target.value })} placeholder={suggestRole} />
          <div className="text-xs muted mt-4">เว้นว่างได้ — ระบบจะใช้ "{suggestRole}"</div>
        </div>

        {/* Password section — required */}
        <div style={{ padding: 12, background: 'var(--surface-2)', borderRadius: 8, border: '1px solid var(--border)' }}>
          <div className="row gap-8 mb-12" style={{ alignItems: 'center' }}>
            <Icon name="shield" size={14} style={{ color: 'var(--brand-ink)' }} />
            <span className="medium text-sm">ตั้งรหัสผ่านสำหรับ Login <span className="req">*</span></span>
            <button type="button" className="btn btn-ghost btn-sm" onClick={genPwd} style={{ marginLeft: 'auto', height: 26 }} title="สุ่มรหัสผ่าน 6 ตัวอักษร"><Icon name="zap" size={11} /> สุ่ม</button>
          </div>
          <div className="grid grid-2" style={{ gap: 10 }}>
            <div className="field">
              <label className="field-label">รหัสผ่าน (≥4 ตัว)</label>
              <div className="row gap-4">
                <input className="input" type={showPwd ? 'text' : 'password'} value={form.password} onChange={(e) => update({ password: e.target.value })} placeholder="อย่างน้อย 4 ตัวอักษร" />
                <button type="button" className="btn btn-outline btn-sm" onClick={() => setShowPwd(s => !s)} style={{ height: 38, minWidth: 50 }}>{showPwd ? '👁️' : '🔒'}</button>
              </div>
            </div>
            <div className="field">
              <label className="field-label">ยืนยันรหัสผ่าน</label>
              <input className="input" type={showPwd ? 'text' : 'password'} value={form.password2} onChange={(e) => update({ password2: e.target.value })} placeholder="พิมพ์ซ้ำ" />
            </div>
          </div>
          {form.password && form.password2 && form.password !== form.password2 && (
            <div className="text-xs mt-6" style={{ color: 'var(--red-ink)' }}>⚠️ รหัสผ่านไม่ตรงกัน</div>
          )}
          {form.password && form.password === form.password2 && form.password.length >= 4 && showPwd && (
            <div className="text-xs mt-6" style={{ color: 'var(--green-ink)' }}>✓ รหัสผ่านพร้อมใช้: <span className="medium" style={{ fontFamily: 'monospace' }}>{form.password}</span> — จดไว้หรือส่งให้พนักงาน</div>
          )}
        </div>

        {err && <div className="alert alert-red"><Icon name="warning" size={14} style={{ marginTop: 1 }} /><div className="text-xs">{err}</div></div>}

        <div className="alert alert-info">
          <Icon name="zap" size={14} style={{ marginTop: 1 }} />
          <div className="text-xs">พนักงานใหม่จะ login ได้ทันทีด้วยรหัสที่ตั้งไว้ · ระบบสุ่ม ID พนักงานให้อัตโนมัติ (เช่น MKT-005)</div>
        </div>
      </div>
    </Modal>
  );
};

Object.assign(window, { PeoplePage, AddEmployeeModal });
// ⟪AUTO-EXPORTS-START⟫
export { LEVEL_TH, LEVEL_ORDER, DEPT_PREFIX, PeoplePage, SetPasswordModal, AddEmployeeModal };
// ⟪AUTO-EXPORTS-END⟫
