// ⟪AUTO-HEADER-START⟫ generated by scripts/extract.mjs + gen-imports.mjs — do not edit this region by hand
import React from 'react';
import { Avatar, DateInput, Empty, Icon, Modal, OptionSelect, SplitProgress, StatusBadge, TypeIcon, addOptionItem, canViewClearingItem, downloadCSV, fmtBaht, getOptionItems, nowTh, parseTh, usePersistedState } from '../lib/core.jsx';
import { RequestRow } from './dashboard.jsx';
// ⟪AUTO-HEADER-END⟫
/* ============================================
   FlowDesk — Operational pages
   (Stock Report, Import File, Clearing, Audit Log)
   ============================================ */

// ===== Stock Report (ยืม-คืน-แถม) =====
const StockReportPage = ({ ctx }) => {
  const { state, setState } = ctx;
  const [tab, setTab] = React.useState('borrow');

  const borrowReqs = state.requests.filter(r => r.type === 'borrow');

  // Aggregate per SKU across all borrow requests
  const byProduct = {};
  borrowReqs.forEach(r => {
    (r.items || []).forEach(it => {
      if (!byProduct[it.sku]) byProduct[it.sku] = { sku: it.sku, taken: 0, sold: 0, returned: 0, bonus: 0, requests: [] };
      byProduct[it.sku].taken += it.qty;
      byProduct[it.sku].sold += it.sold || 0;
      byProduct[it.sku].returned += it.returned || 0;
      byProduct[it.sku].bonus += it.bonus || 0;
      byProduct[it.sku].requests.push(r.id);
    });
  });
  const agg = Object.values(byProduct);

  const sumTaken = agg.reduce((s, a) => s + a.taken, 0);
  const sumSold = agg.reduce((s, a) => s + a.sold, 0);
  const sumReturned = agg.reduce((s, a) => s + a.returned, 0);
  const sumBonus = agg.reduce((s, a) => s + a.bonus, 0);
  const sumRem = sumTaken - sumSold - sumReturned - sumBonus;

  return (
    <div>
      <div className="page-head">
        <div>
          <h1 className="page-title">รายงานสต๊อค ยืม–คืน–แถม</h1>
          <div className="page-sub">สรุปยอดสินค้าที่ยืมออกและการตัดสต๊อคจากยอดขาย</div>
        </div>
        <div className="row gap-8">
          <button className="btn btn-outline"><Icon name="filter" size={14} /> ช่วงเวลา · เดือนนี้</button>
          <button className="btn btn-outline" onClick={() => {
            const rows = [['SKU', 'สินค้า', 'ยืมออก', 'ขาย', 'แถม', 'คืน', 'คงค้าง', 'จำนวนใบยืม']];
            agg.forEach(a => { const p = state.products.find(p => p.sku === a.sku); rows.push([a.sku, p?.nameTh || '', a.taken, a.sold, a.bonus, a.returned, a.taken - a.sold - a.bonus - a.returned, a.requests.length]); });
            downloadCSV(`รายงานสต๊อก-${nowTh().replace(/[/:\s]/g, '-')}.csv`, rows);
          }}><Icon name="download" size={14} /> ส่งออก CSV</button>
        </div>
      </div>

      <div className="grid grid-4 mb-20">
        {[
          { lbl: 'ยืมออก',    val: sumTaken,    color: 'var(--ink-3)', pct: 100 },
          { lbl: 'ขายแล้ว',   val: sumSold,     color: 'var(--green)', pct: (sumSold / sumTaken * 100).toFixed(0) },
          { lbl: 'ของแถม',    val: sumBonus,    color: 'var(--violet)', pct: (sumBonus / sumTaken * 100).toFixed(0) },
          { lbl: 'รับคืน',    val: sumReturned, color: 'var(--blue)', pct: (sumReturned / sumTaken * 100).toFixed(0) }
        ].map((k, i) => (
          <div className="kpi" key={i}>
            <div className="kpi-label">{k.lbl}</div>
            <div className="row gap-8" style={{ alignItems: 'baseline' }}>
              <div className="kpi-value" style={{ color: k.color }}>{k.val}</div>
              <div className="text-xs muted en">หน่วย</div>
            </div>
            <div className="text-xs muted en">{k.pct}% ของยอดยืม</div>
          </div>
        ))}
      </div>

      <div className="card card-pad mb-20">
        <div className="spread mb-16">
          <h3 className="card-title">สัดส่วนยืม-ขาย-แถม-คืน-คงเหลือ</h3>
          <span className="text-xs muted en">รวม {sumTaken} หน่วย</span>
        </div>
        <div className="progress split" style={{ height: 28, background: 'var(--surface-3)' }}>
          <div style={{ flex: sumSold,     background: 'var(--green)',  display: 'grid', placeItems: 'center', color: 'white', fontSize: 11, fontFamily: 'var(--font-en)' }}>ขาย {sumSold}</div>
          <div style={{ flex: sumBonus,    background: 'var(--violet)', display: 'grid', placeItems: 'center', color: 'white', fontSize: 11, fontFamily: 'var(--font-en)' }}>แถม {sumBonus}</div>
          <div style={{ flex: sumReturned, background: 'var(--blue)',   display: 'grid', placeItems: 'center', color: 'white', fontSize: 11, fontFamily: 'var(--font-en)' }}>คืน {sumReturned}</div>
          <div style={{ flex: Math.max(sumRem, 0), background: 'var(--surface-3)', display: 'grid', placeItems: 'center', color: 'var(--ink-3)', fontSize: 11, fontFamily: 'var(--font-en)' }}>คงค้าง {sumRem}</div>
        </div>
      </div>

      <div className="tabs">
        <button className={`tab ${tab === 'borrow' ? 'active' : ''}`} onClick={() => setTab('borrow')}>
          ยอดยืมรายสินค้า <span className="tab-count">{agg.length}</span>
        </button>
        <button className={`tab ${tab === 'records' ? 'active' : ''}`} onClick={() => setTab('records')}>
          ใบยืมทั้งหมด <span className="tab-count">{borrowReqs.length}</span>
        </button>
        <button className={`tab ${tab === 'overdue' ? 'active' : ''}`} onClick={() => setTab('overdue')}>
          เกินกำหนด <span className="tab-count">{borrowReqs.filter(r => r.overdue).length}</span>
        </button>
      </div>

      {tab === 'borrow' && (
        <div className="card" style={{ overflow: 'hidden' }}>
          <table className="table">
            <thead>
              <tr>
                <th>สินค้า</th>
                <th className="right">ยืม</th>
                <th className="right" style={{ color: 'var(--green-ink)' }}>ขาย</th>
                <th className="right" style={{ color: 'var(--violet-ink)' }}>แถม</th>
                <th className="right" style={{ color: 'var(--blue-ink)' }}>คืน</th>
                <th className="right">คงค้าง</th>
                <th style={{ minWidth: 160 }}>สัดส่วน</th>
                <th className="right">ใบยืม</th>
              </tr>
            </thead>
            <tbody>
              {agg.map((a, i) => {
                const p = state.products.find(p => p.sku === a.sku);
                const remaining = a.taken - a.sold - a.returned - a.bonus;
                return (
                  <tr key={i}>
                    <td>
                      <div className="medium text-sm">{p?.nameTh}</div>
                      <div className="text-xs muted en">{a.sku} · {p?.unit}</div>
                    </td>
                    <td className="num-cell right">{a.taken}</td>
                    <td className="num-cell right" style={{ color: 'var(--green-ink)' }}>{a.sold}</td>
                    <td className="num-cell right" style={{ color: 'var(--violet-ink)' }}>{a.bonus}</td>
                    <td className="num-cell right" style={{ color: 'var(--blue-ink)' }}>{a.returned}</td>
                    <td className="num-cell right bold">{remaining}</td>
                    <td><SplitProgress taken={a.taken} sold={a.sold} returned={a.returned} bonus={a.bonus} /></td>
                    <td className="num-cell right en text-xs">{a.requests.length}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {tab === 'records' && (
        <div className="card" style={{ overflow: 'hidden' }}>
          {borrowReqs.map(r => {
            const u = state.users[r.requester];
            const c = state.customers.find(c => c.id === r.customerId);
            const totalQty = (r.items || []).reduce((s, i) => s + i.qty, 0);
            const sold = (r.items || []).reduce((s, i) => s + (i.sold || 0), 0);
            const returned = (r.items || []).reduce((s, i) => s + (i.returned || 0), 0);
            const bonus = (r.items || []).reduce((s, i) => s + (i.bonus || 0), 0);
            return (
              <div key={r.id} className="row gap-16" style={{
                padding: '16px 20px',
                borderBottom: '1px solid var(--border)',
                cursor: 'pointer'
              }} onClick={() => setState({ route: 'detail', selectedId: r.id })}>
                <TypeIcon type="borrow" size={36} />
                <div className="flex-1" style={{ minWidth: 0 }}>
                  <div className="row gap-8 mb-4">
                    <span className="en tnum text-xs muted">{r.id}</span>
                    <StatusBadge status={r.status} />
                    {r.overdue && <span className="badge badge-red">เกินกำหนด</span>}
                  </div>
                  <div className="medium" style={{ fontSize: 13.5 }}>{r.title}</div>
                  <div className="row gap-12 text-xs muted mt-4">
                    <span><Icon name="user" size={11} /> {u?.name}</span>
                    {c && <span><Icon name="building" size={11} /> {c.name}</span>}
                    <span><Icon name="calendar" size={11} /> ครบกำหนด {r.dueDate}</span>
                  </div>
                </div>
                <div className="col" style={{ minWidth: 240, alignItems: 'stretch' }}>
                  <div className="row gap-8 text-xs mb-4" style={{ justifyContent: 'space-between' }}>
                    <span className="muted">ยืม <span className="en tnum bold" style={{ color: 'var(--ink)' }}>{totalQty}</span></span>
                    <span style={{ color: 'var(--green-ink)' }}>ขาย {sold}</span>
                    <span style={{ color: 'var(--violet-ink)' }}>แถม {bonus}</span>
                    <span style={{ color: 'var(--blue-ink)' }}>คืน {returned}</span>
                  </div>
                  <SplitProgress taken={totalQty} sold={sold} returned={returned} bonus={bonus} />
                </div>
              </div>
            );
          })}
        </div>
      )}

      {tab === 'overdue' && (
        <div className="card" style={{ overflow: 'hidden' }}>
          {borrowReqs.filter(r => r.overdue).length === 0
            ? <div style={{ padding: 40 }}><Empty title="ไม่มีรายการเกินกำหนด" /></div>
            : borrowReqs.filter(r => r.overdue).map(r => (
              <RequestRow key={r.id} req={r} users={state.users} onClick={() => setState({ route: 'detail', selectedId: r.id })} />
            ))
          }
        </div>
      )}
    </div>
  );
};

// ===== Import File =====
const ImportFilePage = ({ ctx }) => {
  const { state, setState } = ctx;
  const [mode, setMode] = React.useState(state.importTarget ? 'sales' : 'sales');
  const [step, setStep] = React.useState('upload');
  const [targetId, setTargetId] = React.useState(state.importTarget || '');
  const [fileName, setFileName] = React.useState('');

  const activeBorrows = state.requests.filter(r => r.type === 'borrow' && (r.status === 'progress' || r.pendingClear));
  const targetReq = state.requests.find(r => r.id === targetId);

  const previewRows = targetReq && targetReq.items ? targetReq.items.map(it => {
    const p = state.products.find(p => p.sku === it.sku);
    return mode === 'sales'
      ? { sku: it.sku, name: p?.nameTh, soldUnits: Math.min(it.qty, Math.floor(it.qty * 0.6)), revenue: Math.floor(it.qty * 0.6) * (p?.price || 0) }
      : { sku: it.sku, name: p?.nameTh, returnedUnits: Math.max(0, it.qty - it.sold - it.bonus - 5) };
  }) : [];

  const apply = () => {
    if (!targetReq) return;
    const newItems = targetReq.items.map((it, i) => {
      const row = previewRows[i];
      if (mode === 'sales') {
        return { ...it, sold: (it.sold || 0) + row.soldUnits };
      } else {
        return { ...it, returned: (it.returned || 0) + (row.returnedUnits || 0) };
      }
    });
    setState({
      requests: state.requests.map(r => r.id === targetId ? { ...r, items: newItems } : r),
      activities: [
        { at: nowTh(), user: state.currentUserId, action: 'import', refId: targetId, summary: mode === 'sales' ? 'นำเข้ายอดขาย' : 'นำเข้าของคืน' },
        ...state.activities
      ]
    });
    setStep('done');
  };

  const reset = () => { setStep('upload'); setFileName(''); };

  return (
    <div>
      <div className="page-head">
        <div>
          <h1 className="page-title">Import File</h1>
          <div className="page-sub">นำเข้ายอดขายและของคืน เพื่ออัพเดทยอดยืมในระบบ</div>
        </div>
        <button className="btn btn-outline"><Icon name="download" size={14} /> ดาวน์โหลด Template</button>
      </div>

      <div className="tabs">
        <button className={`tab ${mode === 'sales' ? 'active' : ''}`} onClick={() => { setMode('sales'); reset(); }}>
          <Icon name="trending" size={12} /> ยอดขาย
        </button>
        <button className={`tab ${mode === 'return' ? 'active' : ''}`} onClick={() => { setMode('return'); reset(); }}>
          <Icon name="repeat" size={12} /> ของคืน
        </button>
      </div>

      <div className="grid" style={{ gridTemplateColumns: '2fr 1fr', gap: 16 }}>
        <div className="card card-pad">
          <h3 className="card-title mb-16">
            {mode === 'sales' ? 'นำเข้ายอดขายจากร้าน/บูธ' : 'นำเข้าของคืนเข้าคลัง'}
          </h3>

          <div className="field mb-16">
            <label className="field-label">เลือกใบยืมที่ต้องการอัพเดท <span className="req">*</span></label>
            <select className="select" value={targetId} onChange={(e) => setTargetId(e.target.value)}>
              <option value="">-- เลือกใบยืม --</option>
              {activeBorrows.map(r => (
                <option key={r.id} value={r.id}>{r.id} · {r.title}</option>
              ))}
            </select>
          </div>

          {step === 'upload' && (
            <div className="dropzone" onClick={() => { setFileName('sales_report_2026-06-01.xlsx'); setStep('preview'); }}>
              <div style={{
                width: 56, height: 56, borderRadius: 100,
                background: 'var(--brand-soft)',
                margin: '0 auto 12px',
                display: 'grid', placeItems: 'center',
                color: 'var(--brand-ink)'
              }}>
                <Icon name="upload" size={24} />
              </div>
              <div className="medium">ลากไฟล์มาวาง หรือคลิกเพื่อเลือกไฟล์</div>
              <div className="text-xs muted mt-4 en">รองรับ .xlsx, .csv ขนาดไม่เกิน 10MB</div>
              <div className="row gap-8 mt-16" style={{ justifyContent: 'center' }}>
                <span className="badge no-dot">Excel</span>
                <span className="badge no-dot">CSV</span>
              </div>
            </div>
          )}

          {step === 'preview' && (
            <div>
              <div className="alert alert-info mb-16">
                <Icon name="file" size={14} style={{ marginTop: 1 }} />
                <div className="flex-1">
                  <div className="medium">{fileName}</div>
                  <div className="text-xs mt-2">พบ {previewRows.length} รายการ · กำลังจับคู่กับใบยืม {targetId}</div>
                </div>
                <button className="btn btn-ghost btn-sm" onClick={reset}>เปลี่ยนไฟล์</button>
              </div>
              <table className="table">
                <thead>
                  {mode === 'sales' ? (
                    <tr><th>SKU</th><th>สินค้า</th><th className="right">ยอดยืม</th><th className="right">ขายในไฟล์</th><th className="right">รายได้</th><th>Match</th></tr>
                  ) : (
                    <tr><th>SKU</th><th>สินค้า</th><th className="right">ยอดยืม</th><th className="right">คืนในไฟล์</th><th>Match</th></tr>
                  )}
                </thead>
                <tbody>
                  {previewRows.map((row, i) => {
                    const it = targetReq.items[i];
                    return (
                      <tr key={i}>
                        <td className="num-cell text-xs">{row.sku}</td>
                        <td className="text-sm">{row.name}</td>
                        <td className="num-cell right">{it.qty}</td>
                        {mode === 'sales' ? (
                          <>
                            <td className="num-cell right" style={{ color: 'var(--green-ink)' }}>{row.soldUnits}</td>
                            <td className="num-cell right">{fmtBaht(row.revenue)}</td>
                          </>
                        ) : (
                          <td className="num-cell right" style={{ color: 'var(--blue-ink)' }}>{row.returnedUnits}</td>
                        )}
                        <td><span className="badge badge-green"><Icon name="check" size={10} /> Match</span></td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
              <div className="row gap-8 mt-16" style={{ justifyContent: 'flex-end' }}>
                <button className="btn btn-outline" onClick={reset}>ยกเลิก</button>
                <button className="btn btn-primary" onClick={apply}>
                  <Icon name="check" size={13} /> ยืนยันและอัพเดทยอด
                </button>
              </div>
            </div>
          )}

          {step === 'done' && (
            <div className="center" style={{ padding: '32px 20px' }}>
              <div style={{
                width: 64, height: 64, borderRadius: 100,
                background: 'var(--green-soft)',
                color: 'var(--green-ink)',
                margin: '0 auto 16px',
                display: 'grid', placeItems: 'center'
              }}>
                <Icon name="check" size={28} />
              </div>
              <div className="text-lg bold mb-8">นำเข้าสำเร็จ</div>
              <div className="text-sm muted mb-20">อัพเดท {previewRows.length} รายการในใบยืม {targetId} เรียบร้อย</div>
              <div className="row gap-8" style={{ justifyContent: 'center' }}>
                <button className="btn btn-outline" onClick={() => { reset(); setTargetId(''); }}>นำเข้าไฟล์อื่น</button>
                <button className="btn btn-primary" onClick={() => setState({ route: 'detail', selectedId: targetId })}>
                  ดูใบยืม <Icon name="arrowRight" size={13} />
                </button>
              </div>
            </div>
          )}
        </div>

        <div className="col gap-16">
          <div className="card card-pad">
            <h3 className="card-title mb-12">วิธีใช้งาน</h3>
            <ol style={{ margin: 0, paddingLeft: 18, fontSize: 13, color: 'var(--ink-2)', lineHeight: 1.7 }}>
              <li>เลือกใบยืมที่ต้องการอัพเดท</li>
              <li>อัพโหลดไฟล์ {mode === 'sales' ? 'ยอดขาย' : 'ของคืน'} (.xlsx / .csv)</li>
              <li>ระบบจะ Match SKU กับรายการในใบยืม</li>
              <li>ตรวจสอบและกดยืนยันเพื่อตัดสต๊อค</li>
            </ol>
          </div>
          <div className="card card-pad">
            <h3 className="card-title mb-12">{mode === 'sales' ? 'Template ยอดขาย' : 'Template ของคืน'}</h3>
            <div className="text-xs muted mb-12">คอลัมน์ที่ต้องมีในไฟล์:</div>
            <div className="col gap-6">
              {(mode === 'sales'
                ? ['SKU', 'Product Name', 'Sold Units', 'Unit Price', 'Total Revenue', 'Sales Date']
                : ['SKU', 'Product Name', 'Returned Units', 'Return Reason', 'Return Date']
              ).map((c, i) => (
                <div key={i} className="row gap-8" style={{
                  padding: '6px 10px',
                  background: 'var(--surface-2)',
                  borderRadius: 6,
                  fontSize: 12,
                  fontFamily: 'var(--font-en)'
                }}>
                  <Icon name="check" size={10} style={{ color: 'var(--green-ink)' }} />
                  {c}
                </div>
              ))}
            </div>
            <button className="btn btn-outline btn-sm mt-16" style={{ width: '100%' }}>
              <Icon name="download" size={12} /> ดาวน์โหลด Template
            </button>
          </div>
          <div className="card card-pad">
            <h3 className="card-title mb-12">ประวัติการนำเข้า</h3>
            <div className="col gap-10">
              {state.activities.filter(a => a.action === 'import').slice(0, 6).length === 0 ? (
                <div className="text-xs muted center" style={{ padding: 20 }}>ยังไม่มีประวัติการนำเข้า</div>
              ) : state.activities.filter(a => a.action === 'import').slice(0, 6).map((h, i, arr) => {
                const u = state.users[h.user];
                return (
                  <div key={i} className="row gap-8" style={{ paddingBottom: 8, borderBottom: i < arr.length - 1 ? '1px solid var(--border)' : 'none' }}>
                    <Icon name="file" size={16} className="muted" />
                    <div className="flex-1" style={{ minWidth: 0 }}>
                      <div className="text-sm" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{h.summary}</div>
                      <div className="text-xs muted">{h.refId} · {u?.name?.split(' ')[0] || h.user}</div>
                    </div>
                    <div className="text-xs muted en">{h.at.split(' ')[0]}</div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// ===== IOU Clearing =====
const ClearingPage = ({ ctx }) => {
  const { state, setState, currentUser } = ctx;
  const [target, setTarget] = React.useState(state.clearTarget || null);
  const [receipts, setReceipts] = React.useState([]);
  const isAccounting = currentUser.deptKey === 'accounting';
  // Scope: mine = ของฉัน (เคลียร์เอง), verify = บัญชี (ตรวจสอบของคนอื่น), all = ภาพรวมบัญชี
  const [scopeRaw, setScope] = usePersistedState('clearing.scope', isAccounting ? 'verify' : 'mine');
  // 🐛FIX: scope persist ข้าม user บนเครื่องเดียวกัน — non-accounting เจอ 'verify'/'all' ค้าง → หน้าเปล่า
  const scope = isAccounting ? scopeRaw : 'mine';
  const [verifyTarget, setVerifyTarget] = React.useState(null);

  React.useEffect(() => {
    if (state.clearTarget) setTarget(state.clearTarget);
  }, [state.clearTarget]);
  // 🐛FIX: มาจากปุ่ม "ตีกลับ" ในหน้า detail — เปิด tab ตรวจสอบ + modal ให้เลย
  React.useEffect(() => {
    if (state.clearVerifyTarget && isAccounting) {
      setScope('verify');
      setVerifyTarget(state.clearVerifyTarget);
      setState({ clearVerifyTarget: null });
    }
  }, [state.clearVerifyTarget]);
  // 🐛FIX: clearTarget ชี้คำขอที่หายไปแล้ว (sync/ลบ) → หน้าเปล่าไม่มีทางออก — ล้างทิ้ง
  React.useEffect(() => {
    if (target && !state.requests.find(r => r.id === target)) { setTarget(null); setReceipts([]); }
  }, [target, state.requests]);

  // กรองตามสิทธิ์: เห็นเฉพาะของผู้ขอเอง + คนในแผนกที่เกี่ยวข้องตาม config
  const visibleExpense = state.requests.filter(r =>
    r.type === 'expense' && canViewClearingItem(r, currentUser, state.users)
  );
  const myExpense = visibleExpense.filter(r => r.requester === currentUser.id);

  // === 3 buckets ===
  // 1. รอผู้ขอยื่นเคลียร์ (requester)
  // 🐛FIX: เดิม (cleared < amount) ตัดรายการที่ยื่นเต็มจำนวนแล้วโดนตีกลับออก → หายถาวร ยื่นใหม่ไม่ได้
  // 🐛FIX v3.2: เคลียร์ได้เฉพาะคำขอที่อนุมัติครบแล้ว (progress/done) — IOU ที่ยังรออนุมัติ/ถูกปฏิเสธ
  // ห้ามขึ้นในคิวเคลียร์ (เดิมขึ้นตั้งแต่ยังไม่อนุมัติ ถ้าโดนปฏิเสธจะติดค้างในระบบ)
  const toSubmit = myExpense.filter(r =>
    (r.status === 'progress' || r.status === 'done') &&
    r.pendingClear &&
    (!r.clearingStatus || r.clearingStatus === 'rejected') &&
    (r.clearingStatus === 'rejected' || (r.cleared || 0) < r.amount)
  );
  // 2. ผู้ขอยื่นแล้ว รอบัญชีตรวจ (visible to requester as 'submitted', and accounting needs to verify)
  const submittedMine = myExpense.filter(r => r.clearingStatus === 'submitted');
  const submittedAll = visibleExpense.filter(r => r.clearingStatus === 'submitted'); // สำหรับบัญชี
  // 3. เคลียร์แล้ว (verified)
  const verifiedMine = myExpense.filter(r => r.clearingStatus === 'verified' || ((r.cleared || 0) >= r.amount && !r.pendingClear && !r.clearingStatus));
  const verifiedAll = visibleExpense.filter(r => r.clearingStatus === 'verified' || ((r.cleared || 0) >= r.amount && !r.pendingClear && !r.clearingStatus));

  const req = state.requests.find(r => r.id === target);
  const totalReceipts = receipts.reduce((s, r) => s + (Number(r.amount) || 0), 0);

  // ผู้ขอยื่นเคลียร์ → clearingStatus = 'submitted', บัญชียังต้องตรวจ
  const submitClear = () => {
    if (!target) return;
    setState({
      requests: state.requests.map(r => r.id === target ? {
        ...r,
        cleared: totalReceipts,
        clearingStatus: 'submitted',
        clearedSubmittedAt: nowTh(),
        clearingRejectReason: undefined,
        pendingClear: true,  // ยังถือว่า pendingClear=true จนกว่าจะ verify
        lastActivity: `ยื่นเคลียร์เอกสาร ${fmtBaht(totalReceipts)} — รอบัญชีตรวจสอบ`
      } : r),
      activities: [
        { at: nowTh(), user: state.currentUserId, action: 'clear', refId: target, summary: `ยื่นเคลียร์เอกสาร ${fmtBaht(totalReceipts)} — รอบัญชีตรวจสอบ` },
        ...state.activities
      ],
      clearTarget: null
    });
    setTarget(null);
    setReceipts([]);
    window.toast(`ยื่นเคลียร์ ${fmtBaht(totalReceipts)} เรียบร้อย — รอบัญชีตรวจสอบ`, { level: 'success', duration: 6000 });
  };

  // บัญชี approve → clearingStatus='verified'
  const verifyClear = (id) => {
    setState({
      requests: state.requests.map(r => r.id === id ? {
        ...r,
        clearingStatus: 'verified',
        clearedVerifiedAt: nowTh(),
        clearedVerifiedBy: currentUser.id,
        pendingClear: false,
        lastActivity: `บัญชีอนุมัติเคลียร์แล้ว`
      } : r),
      activities: [{ at: nowTh(), user: currentUser.id, action: 'check', refId: id, summary: 'บัญชีอนุมัติเคลียร์เอกสาร' }, ...state.activities]
    });
    setVerifyTarget(null);
    window.toast(`อนุมัติเคลียร์ ${id} เรียบร้อย`, { level: 'success' });
  };
  // บัญชี reject → clearingStatus='rejected', ผู้ขอต้องแก้ใหม่
  const rejectClear = (id, reason) => {
    if (!reason || !reason.trim()) { window.toast('กรุณาระบุเหตุผล', { level: 'warning' }); return; }
    setState({
      requests: state.requests.map(r => r.id === id ? {
        ...r,
        clearingStatus: 'rejected',
        clearingRejectReason: reason,
        clearingRejectedAt: nowTh(),
        clearingRejectedBy: currentUser.id,
        pendingClear: true,
        lastActivity: `บัญชีตีกลับเคลียร์: ${reason}`
      } : r),
      activities: [{ at: nowTh(), user: currentUser.id, action: 'reject', refId: id, summary: `บัญชีตีกลับเคลียร์: ${reason}` }, ...state.activities]
    });
    setVerifyTarget(null);
    window.toast(`ตีกลับเคลียร์ ${id} — ผู้ขอต้องแก้และยื่นใหม่`, { level: 'warning' });
  };

  return (
    <div>
      <div className="page-head">
        <div>
          <h1 className="page-title">เคลียร์เอกสารค่าใช้จ่าย (IOU)</h1>
          <div className="page-sub">
            {scope === 'verify' && isAccounting ? '👁 มุมมองบัญชี — ตรวจสอบใบเสร็จจากผู้ขอ' :
             scope === 'all' && isAccounting ? '📊 ภาพรวมการเคลียร์ทั้งบริษัท' :
             'รายการเงินสดล่วงหน้าที่คุณต้องเคลียร์ตามใบเสร็จจริง'}
          </div>
        </div>
        {isAccounting && (
          <div className="tabs" style={{ margin: 0 }}>
            <button className={`tab ${scope === 'mine' ? 'active' : ''}`} onClick={() => setScope('mine')}>ของฉัน {toSubmit.length > 0 && <span className="tab-count">{toSubmit.length}</span>}</button>
            <button className={`tab ${scope === 'verify' ? 'active' : ''}`} onClick={() => setScope('verify')} style={{ color: scope === 'verify' ? undefined : 'var(--violet-ink)', fontWeight: 600 }}>👁 ตรวจสอบ (บัญชี) {submittedAll.length > 0 && <span className="tab-count" style={{ background: 'var(--violet)', color: 'white' }}>{submittedAll.length}</span>}</button>
            <button className={`tab ${scope === 'all' ? 'active' : ''}`} onClick={() => setScope('all')}>ภาพรวม</button>
          </div>
        )}
      </div>

      {!target && !verifyTarget && (
        <>
          {/* === MINE: ของฉัน (ผู้ขอ) === */}
          {scope === 'mine' && (
            <>
              <div className="grid grid-3 mb-20">
                <div className="kpi"><div className="kpi-label">รอยื่นเคลียร์</div><div className="kpi-value">{toSubmit.length}</div><div className="text-xs muted">รวม {fmtBaht(toSubmit.reduce((s, r) => s + r.amount - (r.cleared || 0), 0))}</div><div className="kpi-icon" style={{ background: 'var(--amber-soft)', color: 'var(--amber-ink)' }}><Icon name="clock" size={16} /></div></div>
                <div className="kpi"><div className="kpi-label">รอบัญชีตรวจ</div><div className="kpi-value" style={{ color: 'var(--violet-ink)' }}>{submittedMine.length}</div><div className="text-xs muted">ยื่นแล้ว · รอ verify</div><div className="kpi-icon" style={{ background: 'var(--violet-soft)', color: 'var(--violet-ink)' }}><Icon name="clock" size={16} /></div></div>
                <div className="kpi"><div className="kpi-label">เคลียร์เสร็จ</div><div className="kpi-value" style={{ color: 'var(--green-ink)' }}>{verifiedMine.length}</div><div className="text-xs muted">รวม {fmtBaht(verifiedMine.reduce((s, r) => s + (r.cleared || 0), 0))}</div><div className="kpi-icon" style={{ background: 'var(--green-soft)', color: 'var(--green-ink)' }}><Icon name="check" size={16} /></div></div>
              </div>

              {toSubmit.some(r => r.clearingStatus === 'rejected') && (
                <div className="alert alert-red mb-16">
                  <Icon name="warning" size={14} style={{ marginTop: 1 }} />
                  <div className="flex-1">
                    <div className="medium text-sm">⚠️ มี {toSubmit.filter(r => r.clearingStatus === 'rejected').length} รายการที่บัญชีตีกลับ — โปรดแก้ไขและยื่นใหม่</div>
                  </div>
                </div>
              )}

              <div className="card" style={{ overflow: 'hidden' }}>
                <div className="card-head">
                  <h3 className="card-title">รายการรอเคลียร์ของคุณ</h3>
                  <span className="text-xs muted">{toSubmit.length} รายการ</span>
                </div>
                {toSubmit.length === 0 ? (
                  <div style={{ padding: 40 }}><Empty title="ไม่มีรายการรอเคลียร์" sub="ใบเสร็จส่งครบ ไม่มีอะไรค้าง" icon="check" /></div>
                ) : (
                  <table className="table">
                    <thead><tr><th>คำขอ</th><th className="right">เบิกล่วงหน้า</th><th className="right">เคลียร์</th><th className="right">คงค้าง</th><th>ครบกำหนด</th><th>สถานะ</th><th></th></tr></thead>
                    <tbody>
                      {toSubmit.map(r => {
                        const remaining = r.amount - (r.cleared || 0);
                        const wasRejected = r.clearingStatus === 'rejected';
                        return (
                          <tr key={r.id} className="clickable" onClick={() => setTarget(r.id)} style={{ background: wasRejected ? 'color-mix(in oklch, var(--red) 6%, var(--surface))' : undefined, borderLeft: wasRejected ? '3px solid var(--red)' : undefined }}>
                            <td><div className="row gap-12"><TypeIcon type="expense" size={28} /><div><div className="en tnum text-xs muted">{r.id}</div><div className="medium text-sm">{r.title}</div>{wasRejected && r.clearingRejectReason && <div className="text-xs" style={{ color: 'var(--red-ink)', marginTop: 2 }}>↩ ตีกลับ: {r.clearingRejectReason}</div>}</div></div></td>
                            <td className="num-cell right">{fmtBaht(r.amount)}</td>
                            <td className="num-cell right" style={{ color: 'var(--green-ink)' }}>{fmtBaht(r.cleared || 0)}</td>
                            <td className="num-cell right bold" style={{ color: 'var(--amber-ink)' }}>{fmtBaht(remaining)}</td>
                            <td><div className="text-sm en">{r.clearDueDate}</div>{r.overdue && <div className="text-xs" style={{ color: 'var(--red-ink)' }}>เกินกำหนด</div>}</td>
                            <td>{wasRejected ? <span className="badge badge-red" style={{ fontSize: 10 }}>ต้องแก้</span> : <span className="badge badge-amber" style={{ fontSize: 10 }}>รอยื่น</span>}</td>
                            <td><button className="btn btn-primary btn-sm">{wasRejected ? 'แก้และส่งใหม่' : 'เคลียร์'}</button></td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                )}
              </div>

              {submittedMine.length > 0 && (
                <div className="card mt-20" style={{ overflow: 'hidden' }}>
                  <div className="card-head" style={{ background: 'var(--violet-soft)' }}>
                    <h3 className="card-title">⏳ ยื่นแล้ว — รอบัญชีตรวจสอบ</h3>
                    <span className="text-xs muted">{submittedMine.length} รายการ · รวม {fmtBaht(submittedMine.reduce((s, r) => s + (r.cleared || 0), 0))}</span>
                  </div>
                  <table className="table">
                    <thead><tr><th>คำขอ</th><th className="right">เคลียร์</th><th>ยื่นเมื่อ</th><th></th></tr></thead>
                    <tbody>
                      {submittedMine.map(r => (
                        <tr key={r.id} className="clickable" onClick={() => setState({ route: 'detail', selectedId: r.id })}>
                          <td><div className="row gap-12"><TypeIcon type="expense" size={28} /><div><div className="en tnum text-xs muted">{r.id}</div><div className="medium text-sm">{r.title}</div></div></div></td>
                          <td className="num-cell right">{fmtBaht(r.cleared || 0)}</td>
                          <td className="text-sm">{r.clearedSubmittedAt}</td>
                          <td><span className="badge" style={{ background: 'var(--violet)', color: 'white', fontSize: 10 }}>⏳ รอ verify</span></td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </>
          )}

          {/* === VERIFY: บัญชีตรวจสอบ === */}
          {scope === 'verify' && isAccounting && (
            <>
              <div className="alert mb-16" style={{ background: 'var(--violet-soft)', borderColor: 'var(--violet)' }}>
                <Icon name="wallet" size={14} style={{ marginTop: 1, color: 'var(--violet-ink)' }} />
                <div className="flex-1">
                  <div className="medium text-sm" style={{ color: 'var(--violet-ink)' }}>👁 มุมมองบัญชี — ตรวจสอบใบเสร็จที่ผู้ขอยื่นมา</div>
                  <div className="text-xs muted mt-2">กด ✓ อนุมัติเมื่อใบเสร็จครบถ้วน หรือ ✗ ตีกลับพร้อมเหตุผลให้ผู้ขอแก้ใหม่</div>
                </div>
              </div>
              <div className="card" style={{ overflow: 'hidden' }}>
                <div className="card-head" style={{ background: 'var(--violet-soft)' }}>
                  <h3 className="card-title">รอตรวจสอบ ({submittedAll.length})</h3>
                  <span className="text-xs muted">รวมยอด {fmtBaht(submittedAll.reduce((s, r) => s + (r.cleared || 0), 0))}</span>
                </div>
                {submittedAll.length === 0 ? (
                  <div style={{ padding: 40 }}><Empty title="ไม่มีรายการรอตรวจสอบ" sub="ผู้ขอยังไม่ได้ยื่นเคลียร์" icon="check" /></div>
                ) : (
                  <table className="table">
                    <thead><tr><th>คำขอ</th><th>ผู้ขอ</th><th className="right">เบิก</th><th className="right">เคลียร์</th><th>ยื่นเมื่อ</th><th>การกระทำ</th></tr></thead>
                    <tbody>
                      {submittedAll.map(r => {
                        const u = state.users[r.requester];
                        return (
                          <tr key={r.id} style={{ background: 'color-mix(in oklch, var(--violet) 4%, var(--surface))' }}>
                            <td className="clickable" onClick={() => setVerifyTarget(r.id)}><div className="row gap-12"><TypeIcon type="expense" size={28} /><div><div className="en tnum text-xs muted">{r.id}</div><div className="medium text-sm">{r.title}</div></div></div></td>
                            <td><div className="row gap-8"><Avatar user={u} size="sm" /><span className="text-sm">{u?.name?.split(' ')[0]}</span></div></td>
                            <td className="num-cell right">{fmtBaht(r.amount)}</td>
                            <td className="num-cell right bold" style={{ color: 'var(--violet-ink)' }}>{fmtBaht(r.cleared || 0)}</td>
                            <td className="text-sm">{r.clearedSubmittedAt}</td>
                            <td>
                              <div className="row gap-6">
                                <button className="btn btn-success btn-sm" onClick={(e) => { e.stopPropagation(); verifyClear(r.id); }} title="อนุมัติเคลียร์"><Icon name="check" size={11} /> อนุมัติ</button>
                                <button className="btn btn-danger btn-sm" onClick={(e) => { e.stopPropagation(); setVerifyTarget(r.id); }} title="ตีกลับ"><Icon name="x" size={11} /> ตีกลับ</button>
                              </div>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                )}
              </div>
            </>
          )}

          {/* === ALL: ภาพรวม === */}
          {scope === 'all' && isAccounting && (
            <>
              <div className="grid grid-3 mb-20">
                <div className="kpi"><div className="kpi-label">รอผู้ขอยื่น</div><div className="kpi-value" style={{ color: 'var(--amber-ink)' }}>{visibleExpense.filter(r => r.pendingClear && (!r.clearingStatus || r.clearingStatus === 'rejected')).length}</div><div className="kpi-icon" style={{ background: 'var(--amber-soft)', color: 'var(--amber-ink)' }}><Icon name="clock" size={16} /></div></div>
                <div className="kpi"><div className="kpi-label">รอบัญชีตรวจ</div><div className="kpi-value" style={{ color: 'var(--violet-ink)' }}>{submittedAll.length}</div><div className="kpi-icon" style={{ background: 'var(--violet-soft)', color: 'var(--violet-ink)' }}><Icon name="clock" size={16} /></div></div>
                <div className="kpi"><div className="kpi-label">เคลียร์เสร็จ</div><div className="kpi-value" style={{ color: 'var(--green-ink)' }}>{verifiedAll.length}</div><div className="text-xs muted">รวม {fmtBaht(verifiedAll.reduce((s, r) => s + (r.cleared || 0), 0))}</div><div className="kpi-icon" style={{ background: 'var(--green-soft)', color: 'var(--green-ink)' }}><Icon name="check" size={16} /></div></div>
              </div>
              <div className="card" style={{ overflow: 'hidden' }}>
                <div className="card-head"><h3 className="card-title">ภาพรวมการเคลียร์ทั้งบริษัท</h3><span className="text-xs muted">{visibleExpense.length} รายการ</span></div>
                <table className="table">
                  <thead><tr><th>คำขอ</th><th>ผู้ขอ</th><th className="right">เบิก</th><th className="right">เคลียร์</th><th>สถานะ</th></tr></thead>
                  <tbody>
                    {visibleExpense.slice(0, 50).map(r => {
                      const u = state.users[r.requester];
                      const st = r.clearingStatus === 'verified' ? { lbl: '✓ เคลียร์เสร็จ', color: 'var(--green)' } :
                                 r.clearingStatus === 'submitted' ? { lbl: '⏳ รอ verify', color: 'var(--violet)' } :
                                 r.clearingStatus === 'rejected' ? { lbl: '↩ ตีกลับ', color: 'var(--red)' } :
                                 r.pendingClear ? { lbl: 'รอผู้ขอยื่น', color: 'var(--amber)' } :
                                 { lbl: '–', color: 'var(--ink-3)' };
                      return (
                        <tr key={r.id} className="clickable" onClick={() => setState({ route: 'detail', selectedId: r.id })}>
                          <td><div className="row gap-12"><TypeIcon type="expense" size={24} /><div><div className="en tnum text-xs muted">{r.id}</div><div className="text-sm">{r.title}</div></div></div></td>
                          <td className="text-sm">{u?.name?.split(' ')[0]}</td>
                          <td className="num-cell right">{fmtBaht(r.amount)}</td>
                          <td className="num-cell right">{fmtBaht(r.cleared || 0)}</td>
                          <td><span className="badge" style={{ background: st.color, color: 'white', fontSize: 10 }}>{st.lbl}</span></td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </>
          )}
        </>
      )}

      {target && req && (
        <ClearingDetail req={req} state={state} setState={setState} receipts={receipts} setReceipts={setReceipts}
          onBack={() => { setTarget(null); setReceipts([]); }}
          totalReceipts={totalReceipts}
          submitClear={submitClear}
        />
      )}

      {/* Modal: Reject clearing (accounting) */}
      <RejectClearingModal
        open={!!verifyTarget && scope === 'verify'}
        target={verifyTarget}
        req={state.requests.find(r => r.id === verifyTarget)}
        onClose={() => setVerifyTarget(null)}
        onReject={(reason) => rejectClear(verifyTarget, reason)}
      />
    </div>
  );
};

// Modal สำหรับบัญชีตีกลับเคลียร์
const RejectClearingModal = ({ open, target, req, onClose, onReject }) => {
  const [reason, setReason] = React.useState('');
  React.useEffect(() => { if (!open) setReason(''); }, [open]);
  if (!open || !req) return null;
  const presets = ['ใบเสร็จไม่ครบ', 'ยอดไม่ตรง', 'ใบเสร็จไม่ชัดเจน/เบลอ', 'เลขผู้เสียภาษีไม่ครบ', 'รายการไม่เกี่ยวข้องกับงาน'];
  return (
    <Modal open={open} onClose={onClose} title={`ตีกลับเคลียร์เอกสาร — ${target}`}
      footer={<><button className="btn btn-outline" onClick={onClose}>ยกเลิก</button><button className="btn btn-danger" onClick={() => onReject(reason)} disabled={!reason.trim()}><Icon name="x" size={13} /> ตีกลับ</button></>}>
      <div className="col gap-12">
        <div className="alert alert-amber"><Icon name="warning" size={14} style={{ marginTop: 1 }} /><div className="text-sm">ผู้ขอจะได้รับแจ้งให้แก้ไขใบเสร็จและยื่นใหม่ — โปรดระบุเหตุผลที่ชัดเจน</div></div>
        <div className="field">
          <label className="field-label">เหตุผลที่พบบ่อย</label>
          <div className="row gap-6 flex-wrap">
            {presets.map((p, i) => <button key={i} type="button" className="chip" onClick={() => setReason(reason ? reason + ' · ' + p : p)} style={{ fontSize: 12 }}><Icon name="plus" size={10} /> {p}</button>)}
          </div>
        </div>
        <div className="field"><label className="field-label">เหตุผล <span className="req">*</span></label><textarea className="textarea" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="ระบุเหตุผลที่ตีกลับ..." style={{ minHeight: 100 }} autoFocus /></div>
      </div>
    </Modal>
  );
};

const ClearingDetail = ({ req, state, setState, receipts, setReceipts, onBack, totalReceipts, submitClear }) => {
  const u = state.users[req.requester];
  // 🐛FIX: เดิม balance = totalReceipts - amount ทำให้ป้าย "ต้องคืน/บริษัทจ่ายเพิ่ม" สลับด้าน
  // ตอนนี้: balance > 0 = ใช้น้อยกว่าที่เบิก (เหลือเงินต้องคืนบริษัท) · balance < 0 = ใช้เกิน (บริษัทโอนเพิ่ม)
  const balance = req.amount - totalReceipts;

  const addReceipt = () => setReceipts([...receipts, { id: Date.now(), label: '', amount: 0, file: null, vat: false }]);
  const updateReceipt = (i, patch) => {
    const next = [...receipts];
    next[i] = { ...next[i], ...patch };
    setReceipts(next);
  };
  const delReceipt = (i) => setReceipts(receipts.filter((_, idx) => idx !== i));

  return (
    <div>
      <div className="row gap-8 mb-12">
        <button className="btn btn-ghost btn-sm" onClick={onBack} style={{ padding: '4px 8px', height: 26 }}>
          <Icon name="arrowLeft" size={12} /> ย้อนกลับ
        </button>
        <span className="text-xs muted">เคลียร์เอกสาร · {req.id}</span>
      </div>

      <div className="grid" style={{ gridTemplateColumns: '2fr 1fr', gap: 16 }}>
        <div className="card card-pad">
          <div className="row gap-16 mb-20">
            <TypeIcon type="expense" size={44} />
            <div>
              <div className="text-xs muted en">{req.id}</div>
              <div className="text-xl bold">{req.title}</div>
              <div className="row gap-12 text-xs muted mt-4">
                <span><Icon name="user" size={11} /> {u?.name}</span>
                <span><Icon name="calendar" size={11} /> เบิก {req.createdAt}</span>
                <span><Icon name="clock" size={11} /> เคลียร์ภายใน {req.clearDueDate}</span>
              </div>
            </div>
          </div>

          <h3 className="card-title mb-12">เอกสารใบเสร็จ</h3>
          <div className="card" style={{ overflow: 'hidden', marginBottom: 16 }}>
            <table className="table table-compact">
              <thead>
                <tr>
                  <th>รายการ</th>
                  <th style={{ width: 140 }}>หมวด</th>
                  <th style={{ width: 80 }} className="center">VAT</th>
                  <th style={{ width: 140 }} className="right">จำนวนเงิน</th>
                  <th style={{ width: 100 }}>ใบเสร็จ</th>
                  <th style={{ width: 36 }}></th>
                </tr>
              </thead>
              <tbody>
                {receipts.length === 0 && (
                  <tr><td colSpan="6" className="center muted" style={{ padding: 24 }}>
                    ยังไม่มีใบเสร็จ — กด "เพิ่มใบเสร็จ" เพื่อเริ่ม
                  </td></tr>
                )}
                {receipts.map((r, i) => (
                  <tr key={r.id}>
                    <td><OptionSelect value={r.label} onChange={(v) => updateReceipt(i, { label: v })} options={getOptionItems(state, 'receipt')} onAdd={(v) => setState && addOptionItem(state, setState, 'receipt', v)} placeholder="-- เลือกรายการ --" height={32} /></td>
                    <td>
                      <select className="select" style={{ height: 32 }} value={r.category || ''} onChange={(e) => updateReceipt(i, { category: e.target.value })}>
                        <option value="">-- หมวด --</option>
                        <option>ค่าเดินทาง</option>
                        <option>ค่าอาหาร/รับรอง</option>
                        <option>ค่าที่พัก</option>
                        <option>ค่าน้ำมัน</option>
                        <option>อื่นๆ</option>
                      </select>
                    </td>
                    <td className="center"><input type="checkbox" checked={r.vat} onChange={(e) => updateReceipt(i, { vat: e.target.checked })} /></td>
                    <td><input className="input" style={{ height: 32, textAlign: 'right' }} type="number" value={r.amount} onChange={(e) => updateReceipt(i, { amount: Number(e.target.value) })} /></td>
                    <td>
                      {r.file ? (
                        <span className="badge badge-green"><Icon name="check" size={10} /> แนบแล้ว</span>
                      ) : (
                        <button className="btn btn-outline btn-sm" onClick={() => updateReceipt(i, { file: `receipt_${i+1}.jpg` })}>
                          <Icon name="paperclip" size={11} /> แนบ
                        </button>
                      )}
                    </td>
                    <td><button className="btn btn-ghost btn-sm btn-icon-only" onClick={() => delReceipt(i)}><Icon name="trash" size={13} /></button></td>
                  </tr>
                ))}
                <tr style={{ background: 'var(--surface-2)' }}>
                  <td colSpan="3" className="right bold text-sm">รวมใบเสร็จ</td>
                  <td className="num-cell right bold">{fmtBaht(totalReceipts)}</td>
                  <td colSpan="2"></td>
                </tr>
              </tbody>
            </table>
          </div>

          <button className="btn btn-outline" onClick={addReceipt}>
            <Icon name="plus" size={13} /> เพิ่มใบเสร็จ
          </button>
        </div>

        <div className="col gap-16">
          <div className="card card-pad">
            <h3 className="card-title mb-12">สรุปการเคลียร์</h3>
            <div className="col gap-10">
              <div className="spread">
                <span className="text-sm muted">เบิกล่วงหน้า</span>
                <span className="en tnum medium">{fmtBaht(req.amount)}</span>
              </div>
              <div className="spread">
                <span className="text-sm muted">รวมใบเสร็จ</span>
                <span className="en tnum medium" style={{ color: 'var(--green-ink)' }}>{fmtBaht(totalReceipts)}</span>
              </div>
              <div className="divider" style={{ margin: '4px 0' }}></div>
              <div className="spread">
                <span className="text-sm bold">{balance >= 0 ? 'ต้องคืนบริษัท' : 'บริษัทต้องจ่ายเพิ่ม'}</span>
                <span className="en tnum bold text-lg" style={{ color: balance >= 0 ? 'var(--blue-ink)' : 'var(--amber-ink)' }}>
                  {fmtBaht(Math.abs(balance))}
                </span>
              </div>
            </div>

            <div className="alert alert-info mt-16">
              <Icon name="info" size={13} style={{ marginTop: 1 }} />
              <div className="text-xs">
                {balance > 0
                  ? `ใช้น้อยกว่าที่เบิก — โอนคืน ${fmtBaht(balance)} ให้บริษัท`
                  : balance < 0
                  ? `ใช้มากกว่าที่เบิก — บริษัทจะโอนเพิ่ม ${fmtBaht(-balance)}`
                  : 'ใช้พอดีกับที่เบิก'}
              </div>
            </div>

            <button
              className="btn btn-primary mt-16"
              style={{ width: '100%' }}
              disabled={receipts.length === 0 || receipts.some(r => !r.label || !r.amount)}
              onClick={submitClear}
            >
              <Icon name="fileCheck" size={14} /> ยื่นเคลียร์ → รอบัญชีตรวจสอบ
            </button>
            <div className="text-xs muted mt-8 center">บัญชีจะได้รับแจ้งเตือนเพื่อตรวจสอบใบเสร็จ ก่อนยืนยันปิดเคลียร์</div>
          </div>

          <div className="card card-pad">
            <h3 className="card-title mb-12">รายการเบิกล่วงหน้า</h3>
            <table className="table table-compact" style={{ marginTop: -8 }}>
              <tbody>
                {req.breakdown.map((b, i) => (
                  <tr key={i}>
                    <td className="text-xs muted">{b.label}</td>
                    <td className="num-cell right text-sm">{fmtBaht(b.amount)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

// ===== Audit Log =====
const AuditLogPage = ({ ctx }) => {
  const { state } = ctx;
  const [filterUser, setFilterUser] = usePersistedState('audit.user', 'all');
  const [filterAction, setFilterAction] = usePersistedState('audit.action', 'all');
  const [search, setSearch] = React.useState('');
  const [dateFrom, setDateFrom] = React.useState('');
  const [dateTo, setDateTo] = React.useState('');
  const [quickRange, setQuickRange] = usePersistedState('audit.range', '7d');

  const actionMap = {
    create:  { lbl: 'สร้าง',         color: 'brand'  },
    approve: { lbl: 'อนุมัติ',       color: 'green'  },
    reject:  { lbl: 'ปฏิเสธ',        color: 'red'    },
    import:  { lbl: 'นำเข้าไฟล์',   color: 'blue'   },
    clear:   { lbl: 'เคลียร์',       color: 'violet' },
    'qr-scan': { lbl: 'สแกน QR',     color: 'brand'  },
    return:  { lbl: 'รับคืน',        color: 'blue'   },
    comment: { lbl: 'คอมเมนต์',     color: 'ghost'  }
  };

  React.useEffect(() => {
    if (quickRange === 'custom') return;
    const today = new Date(); const fmt = (d) => `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`;
    if (quickRange === 'today') { setDateFrom(fmt(today)); setDateTo(fmt(today)); }
    else if (quickRange === '7d') { const d = new Date(today); d.setDate(d.getDate() - 6); setDateFrom(fmt(d)); setDateTo(fmt(today)); }
    else if (quickRange === '30d') { const d = new Date(today); d.setDate(d.getDate() - 29); setDateFrom(fmt(d)); setDateTo(fmt(today)); }
    else if (quickRange === '90d') { const d = new Date(today); d.setDate(d.getDate() - 89); setDateFrom(fmt(d)); setDateTo(fmt(today)); }
    else if (quickRange === 'all') { setDateFrom(''); setDateTo(''); }
  }, [quickRange]);

  let list = state.activities;
  if (filterUser !== 'all') list = list.filter(a => a.user === filterUser);
  if (filterAction !== 'all') list = list.filter(a => a.action === filterAction);
  if (dateFrom) { const from = parseTh(dateFrom); if (from) list = list.filter(a => { const d = parseTh(a.at); return d && d >= from; }); }
  if (dateTo) { const to = parseTh(dateTo); if (to) { to.setHours(23, 59, 59); list = list.filter(a => { const d = parseTh(a.at); return d && d <= to; }); } }
  if (search) list = list.filter(a => (a.summary + a.refId).toLowerCase().includes(search.toLowerCase()));

  const exportCSV = () => {
    const rows = [['เวลา', 'ผู้ใช้', 'แผนก', 'รหัส', 'การกระทำ', 'อ้างอิง', 'รายละเอียด', 'IP']];
    list.forEach((a, i) => { const u = state.users[a.user]; rows.push([a.at, u?.name || a.user, u?.dept || '', u?.id || a.user, actionMap[a.action]?.lbl || a.action, a.refId, a.summary, '192.168.1.' + (20 + (i % 30))]); });
    downloadCSV(`audit-log-${nowTh().replace(/[/:\s]/g, '-')}.csv`, rows);
  };

  return (
    <div>
      <div className="page-head">
        <div>
          <h1 className="page-title">Audit Log</h1>
          <div className="page-sub">บันทึกการกระทำทั้งหมดในระบบ ใครทำอะไร เมื่อไหร่ · {list.length} รายการ</div>
        </div>
        <div className="row gap-8">
          <button className="btn btn-outline" onClick={exportCSV} disabled={list.length === 0}><Icon name="download" size={14} /> ส่งออก CSV</button>
        </div>
      </div>

      <div className="card card-pad mb-16">
        <div className="row gap-6 flex-wrap mb-12">
          <span className="text-xs muted en" style={{ marginRight: 4 }}>RANGE</span>
          {[['today','วันนี้'],['7d','7 วัน'],['30d','30 วัน'],['90d','90 วัน'],['all','ทั้งหมด'],['custom','กำหนดเอง']].map(([k,lbl]) => (
            <button key={k} className={`chip ${quickRange === k ? 'active' : ''}`} onClick={() => setQuickRange(k)}>{lbl}</button>
          ))}
          {quickRange === 'custom' && <>
            <span className="text-xs muted" style={{ marginLeft: 8 }}>จาก</span>
            <DateInput value={dateFrom} onChange={setDateFrom} className="input" />
            <span className="text-xs muted">ถึง</span>
            <DateInput value={dateTo} onChange={setDateTo} className="input" />
          </>}
        </div>
        <div className="row gap-12 flex-wrap">
          <div className="search" style={{ flex: 1, maxWidth: 320 }}>
            <Icon name="search" size={14} className="search-icon" />
            <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ค้นหา ID หรือคำอธิบาย..." />
          </div>
          <select className="select" style={{ maxWidth: 200 }} value={filterUser} onChange={(e) => setFilterUser(e.target.value)}>
            <option value="all">ผู้ใช้ทั้งหมด</option>
            {Object.values(state.users).map(u => <option key={u.id} value={u.id}>{u.name}</option>)}
          </select>
          <select className="select" style={{ maxWidth: 200 }} value={filterAction} onChange={(e) => setFilterAction(e.target.value)}>
            <option value="all">การกระทำทั้งหมด</option>
            {Object.entries(actionMap).map(([k, v]) => <option key={k} value={k}>{v.lbl}</option>)}
          </select>
          <button className="btn btn-ghost" onClick={() => { setFilterUser('all'); setFilterAction('all'); setSearch(''); setQuickRange('7d'); }}>
            <Icon name="x" size={13} /> Clear
          </button>
        </div>
      </div>

      <div className="card" style={{ overflow: 'hidden' }}>
        <table className="table">
          <thead>
            <tr>
              <th style={{ width: 160 }}>เวลา</th>
              <th>ผู้ใช้</th>
              <th>การกระทำ</th>
              <th>คำขอ</th>
              <th>รายละเอียด</th>
              <th style={{ width: 120 }}>IP</th>
            </tr>
          </thead>
          <tbody>
            {list.map((a, i) => {
              const u = state.users[a.user];
              const ac = actionMap[a.action] || { lbl: a.action, color: 'ghost' };
              return (
                <tr key={i}>
                  <td className="num-cell text-xs muted">{a.at}</td>
                  <td>
                    <div className="row gap-8">
                      <Avatar user={u} size="sm" />
                      <div>
                        <div className="text-sm medium">{u?.name}</div>
                        <div className="text-xs muted en">{u?.role}</div>
                      </div>
                    </div>
                  </td>
                  <td><span className={`badge badge-${ac.color}`}>{ac.lbl}</span></td>
                  <td className="num-cell text-xs">{a.refId}</td>
                  <td className="text-sm">{a.summary}</td>
                  <td className="num-cell text-xs muted">192.168.1.{20 + (i % 30)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
        {list.length === 0 && <div style={{ padding: 40 }}><Empty title="ไม่พบกิจกรรม" /></div>}
      </div>
    </div>
  );
};

Object.assign(window, { StockReportPage, ImportFilePage, ClearingPage, AuditLogPage });
// ⟪AUTO-EXPORTS-START⟫
export { StockReportPage, ImportFilePage, ClearingPage, RejectClearingModal, ClearingDetail, AuditLogPage };
// ⟪AUTO-EXPORTS-END⟫
