// ⟪AUTO-HEADER-START⟫ generated by scripts/extract.mjs + gen-imports.mjs — do not edit this region by hand
import React from 'react';
import { CURRENT_USER_KEY, PERSIST_FIELDS, PERSIST_KEY, consumeInvite, getSyncConfig, loadPersistedState, mergeActivities, mergeArrayByKey, mergeRequests, mergeUsersById, pullFromCloud, pushToCloud, setSyncConfig } from '../cloud/binSync.js';
import { isFirebaseMode } from '../cloud/firebase.js';
import { useFirebaseSync } from '../cloud/useFirebaseSync.js';
import { MOCK } from '../data/mock.js';
import { DEFAULT_OPTION_LISTS, Icon, ToastHost, canApproveStep, canReceiveRequest, getPermissions, hashPassword, mergeOptionLists, usePersistedState, verifyPassword } from '../lib/core.jsx';
import { CalendarPage, ExecReportPage, MasterDataPage, RecurringPage, SettingsPage, TemplatesPage } from '../pages/adminSettings.jsx';
import { ApprovalsPage, DashboardPage, MyRequestsPage } from '../pages/dashboard.jsx';
import { InboxPage, InsightsPage, IntakePage, ScorecardPage } from '../pages/inboxInsights.jsx';
import { PeoplePage } from '../pages/people.jsx';
import { CreateRequest, RequestDetailPage } from '../pages/requestDetail.jsx';
import { AuditLogPage, ClearingPage, ImportFilePage, StockReportPage } from '../pages/stockClearing.jsx';
import { CommandPalette, KeyboardHelp, Sidebar, TopBar } from './chrome.jsx';
// ⟪AUTO-HEADER-END⟫
// Firebase mode — ค่าคงที่จาก build env; เมื่อเปิด จะปิด legacy bin-sync/invite (ดู useFirebaseSync)
const FB_MODE = isFirebaseMode();

// ===== Login Screen — แสดงเมื่อมี user ใดๆในระบบที่ตั้ง password =====
const LoginScreen = ({ users, onLogin }) => {
  const [userId, setUserId] = React.useState('');
  const [pwd, setPwd] = React.useState('');
  const [err, setErr] = React.useState('');
  const [showPwd, setShowPwd] = React.useState(false);

  const sortedUsers = React.useMemo(() => Object.values(users).sort((a, b) =>
    a.dept.localeCompare(b.dept, 'th') || a.name.localeCompare(b.name, 'th')
  ), [users]);
  // ตรวจว่ามีใครตั้งรหัสไว้มั้ย — ถ้าไม่มีเลย แสดง quick-setup button
  const anyHasPwd = sortedUsers.some(u => u.passwordHash);

  const submit = (e) => {
    e?.preventDefault?.();
    setErr('');
    const u = users[userId];
    if (!u) { setErr('กรุณาเลือกผู้ใช้'); return; }
    if (!u.passwordHash) { onLogin(u.id); return; } // ไม่มี password — เข้าได้เลย
    if (!verifyPassword(pwd, u.passwordHash)) { setErr('รหัสผ่านไม่ถูกต้อง'); return; }
    onLogin(u.id);
  };

  const quickSetup = () => {
    // ตั้งรหัส 1234 ให้ทุกคน + reload เพื่อให้ App init ใหม่
    try {
      const persistKey = 'fd-app-state';
      const raw = JSON.parse(localStorage.getItem(persistKey) || '{}');
      const updated = { ...(raw.users || users) };
      Object.keys(updated).forEach(uid => {
        if (!updated[uid].passwordHash) updated[uid] = { ...updated[uid], passwordHash: hashPassword('1234') };
      });
      localStorage.setItem(persistKey, JSON.stringify({ ...raw, users: updated }));
      window.location.reload();
    } catch (e) { alert('ตั้งรหัสไม่สำเร็จ: ' + e.message); }
  };

  const selectedUser = users[userId];
  const needsPwd = selectedUser && selectedUser.passwordHash;

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'linear-gradient(135deg, color-mix(in oklch, var(--brand) 6%, var(--bg)) 0%, color-mix(in oklch, var(--violet) 6%, var(--bg)) 100%)', display: 'grid', placeItems: 'center', zIndex: 1000, padding: 20 }}>
      <div style={{ background: 'var(--surface)', borderRadius: 16, boxShadow: 'var(--shadow-lg)', padding: 36, maxWidth: 420, width: '100%', animation: 'scaleIn 0.25s' }}>
        <div className="row gap-12 mb-20" style={{ alignItems: 'center' }}>
          <div className="sidebar-logo-mark" style={{ width: 40, height: 40, fontSize: 16 }}>FD</div>
          <div>
            <div style={{ fontSize: 18, fontWeight: 600 }}>FlowDesk</div>
            <div className="text-xs muted">ระบบคำขออนุมัติ</div>
          </div>
        </div>
        <div className="text-sm mb-16" style={{ color: 'var(--ink-2)' }}>เลือกผู้ใช้และใส่รหัสผ่านเพื่อเข้าระบบ</div>
        <form onSubmit={submit} className="col gap-12">
          <div className="field">
            <label className="field-label">ผู้ใช้</label>
            <select className="select" value={userId} onChange={(e) => { setUserId(e.target.value); setPwd(''); setErr(''); }} autoFocus>
              <option value="">— เลือกผู้ใช้ —</option>
              {sortedUsers.map(u => (
                <option key={u.id} value={u.id}>{u.name} · {u.roleTh} ({u.dept}){u.passwordHash ? ' 🔒' : ''}</option>
              ))}
            </select>
          </div>
          {needsPwd && (
            <div className="field">
              <label className="field-label">รหัสผ่าน</label>
              <div className="row gap-6">
                <input className="input" type={showPwd ? 'text' : 'password'} value={pwd} onChange={(e) => { setPwd(e.target.value); setErr(''); }} placeholder="กรอกรหัสผ่าน" />
                <button type="button" className="btn btn-outline btn-sm" onClick={() => setShowPwd(s => !s)} style={{ height: 38 }}>{showPwd ? 'ซ่อน' : 'แสดง'}</button>
              </div>
            </div>
          )}
          {selectedUser && !needsPwd && (
            <div className="alert alert-info">
              <Icon name="info" size={14} style={{ marginTop: 1 }} />
              <div className="text-xs flex-1">ผู้ใช้นี้ยังไม่ได้ตั้งรหัสผ่าน — เข้าได้เลย · แนะนำให้ตั้งรหัสที่ <span className="medium">Settings → ทีมงาน</span></div>
            </div>
          )}
          {err && <div className="alert alert-red"><Icon name="warning" size={14} style={{ marginTop: 1 }} /><div className="text-xs flex-1">{err}</div></div>}
          <button type="submit" className="btn btn-primary" style={{ width: '100%' }} disabled={!userId}>
            <Icon name="check" size={14} /> เข้าสู่ระบบ
          </button>
        </form>
        {!anyHasPwd && (
          <div className="alert alert-amber mt-16">
            <Icon name="zap" size={14} style={{ marginTop: 1 }} />
            <div className="text-xs flex-1">
              <div className="medium mb-2">🎯 Quick Demo Setup</div>
              <div style={{ lineHeight: 1.6 }}>ยังไม่มีใครตั้งรหัสผ่าน — กดปุ่มด้านล่างเพื่อตั้งรหัส <span className="medium" style={{ fontFamily: 'monospace' }}>1234</span> ให้ทุกคนทันที (สำหรับทดลอง)</div>
              <button type="button" className="btn btn-amber btn-sm mt-8" onClick={quickSetup} style={{ background: 'var(--amber)', color: 'white', borderColor: 'var(--amber)' }}>
                <Icon name="zap" size={12} /> ตั้งรหัส "1234" ให้ทุกคน + reload
              </button>
            </div>
          </div>
        )}
        <div className="text-xs muted mt-16 center" style={{ lineHeight: 1.5 }}>
          {anyHasPwd
            ? <>ใส่รหัสผ่านที่ admin ให้ · ลืมรหัส? ติดต่อ admin ที่ Settings → ทีมงาน</>
            : <>ครั้งแรก: ผู้ใช้ทุกคนยังไม่มีรหัสผ่าน — กดเข้าได้เลย<br/>หรือกดปุ่ม Quick Demo ด้านบนเพื่อตั้งรหัส 1234 ให้ทุกคน</>}
        </div>
      </div>
    </div>
  );
};

const App = () => {
  // ตรวจ invite link ก่อน — ถ้ามี #join=... → apply config ทันที + clean URL
  // ทำใน useMemo เพื่อให้รันครั้งเดียวก่อน mount
  const inviteApplied = React.useMemo(() => (FB_MODE ? false : consumeInvite()), []);
  React.useEffect(() => {
    if (inviteApplied) {
      window.toast?.('🔗 เข้าร่วมห้องซิงค์อัตโนมัติแล้ว — กำลังโหลดข้อมูล...', { level: 'success', duration: 6000 });
    }
  }, [inviteApplied]);
  const persisted = React.useMemo(loadPersistedState, []);
  // Session — ตรวจว่า login แล้วหรือยัง
  const [sessionUserId, setSessionUserId] = React.useState(() => {
    try {
      const v = localStorage.getItem('fd-session-user');
      return v || null;
    } catch (e) { return null; }
  });
  const [state, _setState] = React.useState({
    // UI state — รีเซ็ตทุกครั้ง
    route: 'dashboard',
    selectedId: null,
    createOpen: false,
    createTemplate: null,
    importTarget: null,
    clearTarget: null,
    // Data — โหลดจาก localStorage ถ้ามี, ไม่งั้นใช้ default จาก MOCK
    // currentUserId: per-device (ไม่ sync) — โหลดจาก fd-current-user ก่อน → fallback default
    currentUserId: (() => {
      try { return localStorage.getItem(CURRENT_USER_KEY) || 'MKT-002'; }
      catch (e) { return 'MKT-002'; }
    })(),
    // Auto-merge: เติม user ใหม่จาก MOCK (เช่น CEO EXE-001) ที่ยังไม่มีใน persisted
    users: (() => {
      if (!persisted?.users) return MOCK.users;
      const merged = { ...persisted.users };
      Object.keys(MOCK.users).forEach(id => {
        if (!merged[id]) merged[id] = MOCK.users[id];
      });
      return merged;
    })(),
    products: persisted?.products || MOCK.products,
    customers: persisted?.customers || MOCK.customers,
    // v3.1: รายการตัวเลือก dropdown — เติม key ใหม่จาก DEFAULT ที่ persisted ยังไม่มี
    optionLists: { ...DEFAULT_OPTION_LISTS, ...(persisted?.optionLists || {}) },
    requests: persisted?.requests || MOCK.requests,
    activities: persisted?.activities || MOCK.activities
  });
  // setState: รองรับทั้ง object patch และ function patch
  // + ประทับ updatedAt อัตโนมัติบน request/user ที่ถูกแก้ (identity เปลี่ยน)
  //   → sync merge ใช้ updatedAt ตัดสินได้แม่นยำ (comment/verify/priority ไม่โดน cloud ทับ)
  // Firebase realtime sync — subscribe/push อยู่ใน hook ทั้งหมด, no-op เมื่อ FB_MODE=false
  useFirebaseSync(state, _setState);

  const setState = (patch) => _setState(s => {
    const p = typeof patch === 'function' ? patch(s) : patch;
    const next = { ...p };
    try {
      if (next.requests && next.requests !== s.requests && Array.isArray(next.requests)) {
        const prevById = new Map((s.requests || []).map(r => [r.id, r]));
        const now = Date.now();
        next.requests = next.requests.map(r => (r && prevById.get(r.id) !== r) ? { ...r, updatedAt: now } : r);
      }
      if (next.users && next.users !== s.users) {
        const now = Date.now();
        const out = {};
        Object.entries(next.users).forEach(([k, v]) => { out[k] = (v && s.users && s.users[k] !== v) ? { ...v, updatedAt: now } : v; });
        next.users = out;
      }
    } catch (e) {}
    return { ...s, ...next };
  });

  // ===== Undo Stack — Ctrl+Z รองรับ undo สูงสุด 10 step =====
  const undoStackRef = React.useRef([]);
  const redoStackRef = React.useRef([]);
  const setStateWithUndo = (patch, label = 'การกระทำ') => {
    _setState(s => {
      // เก็บ snapshot ก่อนเปลี่ยน (เฉพาะ requests + activities)
      undoStackRef.current.push({ requests: s.requests, activities: s.activities, label, at: Date.now() });
      if (undoStackRef.current.length > 10) undoStackRef.current.shift();
      redoStackRef.current = []; // clear redo เมื่อทำ action ใหม่
      return { ...s, ...patch };
    });
  };
  const undo = () => {
    const stack = undoStackRef.current;
    if (stack.length === 0) { window.toast?.('ไม่มีอะไรให้ย้อน', { level: 'info' }); return; }
    const prev = stack.pop();
    _setState(s => {
      redoStackRef.current.push({ requests: s.requests, activities: s.activities, label: prev.label });
      if (redoStackRef.current.length > 10) redoStackRef.current.shift();
      return { ...s, requests: prev.requests, activities: prev.activities };
    });
    window.toast?.(`↶ ย้อน: ${prev.label}`, { level: 'info' });
  };
  const redo = () => {
    const stack = redoStackRef.current;
    if (stack.length === 0) { window.toast?.('ไม่มีอะไรให้ทำซ้ำ', { level: 'info' }); return; }
    const next = stack.pop();
    _setState(s => {
      undoStackRef.current.push({ requests: s.requests, activities: s.activities, label: next.label });
      return { ...s, requests: next.requests, activities: next.activities };
    });
    window.toast?.(`↷ ทำซ้ำ: ${next.label}`, { level: 'info' });
  };
  // expose globally
  React.useEffect(() => {
    window.fdUndo = undo;
    window.fdRedo = redo;
  }, []);
  React.useEffect(() => {
    const onKey = (e) => {
      const tag = (e.target.tagName || '').toLowerCase();
      if (tag === 'input' || tag === 'textarea' || tag === 'select') return;
      if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo(); }
      else if ((e.ctrlKey || e.metaKey) && (e.key === 'y' || (e.shiftKey && e.key === 'Z'))) { e.preventDefault(); redo(); }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  // Auto-save: เมื่อข้อมูลเปลี่ยน → เขียนกลับ localStorage + cloud (debounced)
  // ⚠️ ป้องกัน race condition: ไม่ push ขึ้น cloud จนกว่าจะ pull initial sync เสร็จก่อน
  const cloudPushTimer = React.useRef(null);
  const initialPullDone = React.useRef(false);
  const lastPersistHash = React.useRef('');
  // เก็บ currentUserId ลง localStorage per-device (ไม่ sync)
  React.useEffect(() => {
    try { if (state.currentUserId) localStorage.setItem(CURRENT_USER_KEY, state.currentUserId); } catch (e) {}
  }, [state.currentUserId]);

  React.useEffect(() => {
    try {
      const subset = {};
      PERSIST_FIELDS.forEach(k => { subset[k] = state[k]; });
      // 🛡️ Hard guard — ห้าม push currentUserId เด็ดขาด (per-device only)
      delete subset.currentUserId;
      const serialized = JSON.stringify(subset);
      // 🐛FIX ping-pong: ถ้าเนื้อหาไม่เปลี่ยนจริง (แค่ identity เปลี่ยนจาก merge) → ไม่ push ซ้ำ
      // เดิม: 2 เครื่อง idle จะ pull→merge→push วนกันไม่รู้จบ ทุก 10 วิ
      if (lastPersistHash.current === serialized) return;
      lastPersistHash.current = serialized;
      localStorage.setItem(PERSIST_KEY, serialized);
      // Push to cloud (debounced 2s) — เฉพาะตอน initial pull เสร็จแล้วเท่านั้น
      const cfg = getSyncConfig();
      if (!FB_MODE && cfg.enabled && cfg.bucketUrl && initialPullDone.current) {
        clearTimeout(cloudPushTimer.current);
        cloudPushTimer.current = setTimeout(async () => {
          // 🔁 Pre-push merge — ก่อน push ดึง cloud ล่าสุดมา merge กันการ concurrent edit ทำให้ข้อมูลเครื่องอื่นหาย
          let toSend = { ...subset };
          try {
            const cfgNow = getSyncConfig();
            const latest = await pullFromCloud(cfgNow.bucketUrl);
            if (latest && latest._version && latest._version > (cfgNow.lastVersion || 0)) {
              // cloud มีของใหม่กว่า version ที่เราเคยเห็น → merge ก่อน push
              if ('requests' in latest)   toSend.requests   = mergeRequests(toSend.requests, latest.requests);
              if ('activities' in latest) toSend.activities = mergeActivities(toSend.activities, latest.activities);
              if ('users' in latest)      toSend.users      = mergeUsersById(toSend.users, latest.users);
              if ('products' in latest)   toSend.products   = mergeArrayByKey(toSend.products, latest.products, 'sku');
              if ('customers' in latest)  toSend.customers  = mergeArrayByKey(toSend.customers, latest.customers, 'id');
              if ('optionLists' in latest) toSend.optionLists = mergeOptionLists(toSend.optionLists, latest.optionLists);
              setSyncConfig({ ...cfgNow, lastPullAt: Date.now(), lastVersion: latest._version });
              // อัปเดต local state ด้วย merged result (ให้ตรงกัน)
              _setState(s => ({
                ...s,
                requests:   toSend.requests   || s.requests,
                activities: toSend.activities || s.activities,
                users:      toSend.users      || s.users,
                products:   toSend.products   || s.products,
                customers:  toSend.customers  || s.customers,
                optionLists: toSend.optionLists || s.optionLists,
              }));
            }
          } catch (e) { console.warn('Pre-push pull failed:', e.message); }
          const payload = { ...toSend, _version: Date.now(), _device: cfg.deviceId || 'unknown' };
          delete payload.currentUserId; // double-guard
          const ok = await pushToCloud(cfg.bucketUrl, payload);
          if (ok) setSyncConfig({ ...getSyncConfig(), lastPushAt: Date.now(), lastVersion: payload._version });
        }, 2000);
      }
    } catch (e) {
      console.warn('Persist failed:', e);
    }
  }, [state.requests, state.activities, state.users, state.products, state.customers]);

  // Auto-pull: ทุก 10 วินาที ถ้าเปิด sync · ตอนเริ่มต้นดึงทันที + ตั้ง initialPullDone
  React.useEffect(() => {
    let cancelled = false;
    const tick = async (isInitial) => {
      if (cancelled) return;
      if (FB_MODE) { initialPullDone.current = true; return; }
      const cfg = getSyncConfig();
      if (cfg.enabled && cfg.bucketUrl) {
        const data = await pullFromCloud(cfg.bucketUrl);
        if (data && data._version && data._version > (cfg.lastVersion || 0)) {
          // มีข้อมูลใหม่กว่า — MERGE กับ local (กัน last-write-wins ทำให้ข้อมูลข้ามเครื่องหาย)
          let contentChanged = false;
          _setState(s => {
            const merged = { ...s };
            if ('requests' in data)   merged.requests   = mergeRequests(s.requests, data.requests);
            if ('activities' in data) merged.activities = mergeActivities(s.activities, data.activities);
            if ('users' in data)      merged.users      = mergeUsersById(s.users, data.users);
            if ('products' in data)   merged.products   = mergeArrayByKey(s.products, data.products, 'sku');
            if ('customers' in data)  merged.customers  = mergeArrayByKey(s.customers, data.customers, 'id');
            if ('optionLists' in data) merged.optionLists = mergeOptionLists(s.optionLists, data.optionLists);
            // 🐛FIX ping-pong: ถ้า merge แล้วเนื้อหาเหมือนเดิม → คืน state เดิม (React ข้าม re-render)
            try {
              const same = PERSIST_FIELDS.every(k => JSON.stringify(merged[k]) === JSON.stringify(s[k]));
              if (same) return s;
            } catch (e) {}
            contentChanged = true;
            // 🛡️ Hard guard — ห้าม pull เขียนทับ currentUserId เด็ดขาด (per-device)
            return merged;
          });
          // 🐛FIX: อ่าน config สดใหม่ + Math.max กัน push ที่เพิ่งเสร็จระหว่าง await โดน version เก่าทับ
          const cfgFresh = getSyncConfig();
          setSyncConfig({ ...cfgFresh, lastPullAt: Date.now(), lastVersion: Math.max(cfgFresh.lastVersion || 0, data._version) });
          if (!isInitial && contentChanged) window.toast && window.toast(`ข้อมูลซิงค์จาก ${data._device || 'เครื่องอื่น'} แล้ว`, { level: 'info', duration: 3000 });
        } else if (isInitial && !data) {
          // remote ว่างจริง — push state ปัจจุบันขึ้นไป (สำหรับ admin คนแรก)
          // แต่ถ้าเป็น invite (ไม่มี persisted data) ไม่ต้องทำอะไร
        }
        // pull เสร็จไม่ว่าจะมีข้อมูลหรือไม่ → ปลดล็อค push
        initialPullDone.current = true;
      } else {
        // ไม่ได้เปิด sync → push ได้ทันที
        initialPullDone.current = true;
      }
    };
    tick(true);
    const id = setInterval(() => tick(false), 10000);
    return () => { cancelled = true; clearInterval(id); };
  }, []);

  // Apply session user (ถ้า login ไว้)
  React.useEffect(() => {
    if (sessionUserId && state.users[sessionUserId] && state.currentUserId !== sessionUserId) {
      _setState(s => ({ ...s, currentUserId: sessionUserId }));
    }
  }, [sessionUserId]);

  // บังคับ login เสมอ — คนที่ยังไม่ได้ตั้งรหัสจะกด "เข้าสู่ระบบ" โดยไม่ต้องใส่รหัสได้
  const anyPasswordSet = React.useMemo(() => {
    return Object.values(state.users).some(u => u && u.passwordHash);
  }, [state.users]);
  const needsLogin = !sessionUserId;

  const doLogin = (uid) => {
    try { localStorage.setItem('fd-session-user', uid); } catch (e) {}
    setSessionUserId(uid);
    _setState(s => ({ ...s, currentUserId: uid }));
  };
  const doLogout = () => {
    try { localStorage.removeItem('fd-session-user'); } catch (e) {}
    setSessionUserId(null);
    window.toast && window.toast('ออกจากระบบแล้ว', { level: 'info' });
  };
  // ให้ window เข้าถึง logout ได้ (จากที่อื่น)
  React.useEffect(() => { window.__fdLogout = doLogout; return () => { delete window.__fdLogout; }; }, []);

  const currentUser = state.users[state.currentUserId];

  const [helpOpen, setHelpOpen] = React.useState(false);
  const [sidebarOpen, setSidebarOpen] = React.useState(false);
  const [navKey, setNavKey] = React.useState(null);
  const [paletteOpen, setPaletteOpen] = React.useState(false);

  React.useEffect(() => {
    const onHelp = () => setHelpOpen(true);
    window.addEventListener('fd-open-help', onHelp);
    return () => window.removeEventListener('fd-open-help', onHelp);
  }, []);

  React.useEffect(() => {
    const handler = (e) => {
      // Cmd/Ctrl+K → Command Palette (allowed even inside inputs)
      if ((e.ctrlKey || e.metaKey) && (e.key === 'k' || e.key === 'K')) {
        e.preventDefault(); setPaletteOpen(o => !o); return;
      }
      const tag = (e.target.tagName || '').toLowerCase();
      if (tag === 'input' || tag === 'textarea' || tag === 'select') return;
      if (state.createOpen || helpOpen || paletteOpen) return;
      if (e.key === '?') { e.preventDefault(); setHelpOpen(true); return; }
      if (e.key === 'n' || e.key === 'N') { e.preventDefault(); setState({ createOpen: true }); return; }
      if (e.key === 't' || e.key === 'T') {
        const next = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
        if (next === 'dark') document.documentElement.setAttribute('data-theme', 'dark'); else document.documentElement.removeAttribute('data-theme');
        try { localStorage.setItem('fd-theme', next); } catch (e) {}
        return;
      }
      if (e.key === 'g' || e.key === 'G') { setNavKey('g'); setTimeout(() => setNavKey(null), 1500); return; }
      if (navKey === 'g') {
        const map = { d: 'dashboard', i: 'inbox', a: 'approvals', m: 'my-requests', c: 'calendar', s: 'scorecard', x: 'insights' };
        const route = map[e.key.toLowerCase()];
        if (route) { e.preventDefault(); setState({ route, selectedId: null }); setNavKey(null); }
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [state.createOpen, helpOpen, paletteOpen, navKey]);

  const ctx = { state, setState, currentUser };

  // Permission guard: ถ้าเข้าหน้าที่ไม่มีสิทธิ์ → redirect ไป dashboard
  const perms = getPermissions(currentUser);
  const routePermMap = {
    'insights': 'canInsights', 'scorecard': 'canScorecard', 'approvals': 'canViewApprovalsPage',
    'intake': 'canViewIntake', 'clearing': 'canViewClearing', 'exec': 'canViewExecReport',
    'stock': 'canViewStockReport', 'master': 'canViewMaster', 'audit': 'canViewAudit',
    'import': 'canViewIntake'
  };
  const guardKey = routePermMap[state.route];
  const shouldRedirect = guardKey && perms[guardKey] === false;
  React.useEffect(() => {
    if (shouldRedirect) {
      setState({ route: 'dashboard' });
      if (window.toast) window.toast('คุณไม่มีสิทธิ์เข้าหน้านี้', { level: 'warning' });
    }
  }, [shouldRedirect, state.route]);

  let page;
  switch (state.route) {
    case 'dashboard':   page = <DashboardPage ctx={ctx} />; break;
    case 'inbox':       page = <InboxPage ctx={ctx} />; break;
    case 'insights':    page = perms.canInsights ? <InsightsPage ctx={ctx} /> : <DashboardPage ctx={ctx} />; break;
    case 'my-requests': page = <MyRequestsPage ctx={ctx} />; break;
    case 'scorecard':   page = perms.canScorecard ? <ScorecardPage ctx={ctx} /> : <DashboardPage ctx={ctx} />; break;
    case 'templates':   page = <TemplatesPage ctx={ctx} />; break;
    case 'recurring':   page = <RecurringPage ctx={ctx} />; break;
    case 'calendar':    page = <CalendarPage ctx={ctx} />; break;
    case 'approvals':   page = perms.canViewApprovalsPage ? <ApprovalsPage ctx={ctx} /> : <DashboardPage ctx={ctx} />; break;
    case 'intake':      page = perms.canViewIntake ? <IntakePage ctx={ctx} /> : <DashboardPage ctx={ctx} />; break;
    case 'detail':      page = <RequestDetailPage ctx={ctx} />; break;
    case 'stock':       page = perms.canViewStockReport ? <StockReportPage ctx={ctx} /> : <DashboardPage ctx={ctx} />; break;
    case 'import':      page = perms.canViewIntake ? <ImportFilePage ctx={ctx} /> : <DashboardPage ctx={ctx} />; break;
    case 'clearing':    page = <ClearingPage ctx={ctx} />; break;
    case 'exec':        page = perms.canViewExecReport ? <ExecReportPage ctx={ctx} /> : <DashboardPage ctx={ctx} />; break;
    case 'master':      page = perms.canViewMaster ? <MasterDataPage ctx={ctx} /> : <DashboardPage ctx={ctx} />; break;
    case 'employees':   page = <PeoplePage ctx={ctx} />; break;
    case 'settings':    page = <SettingsPage ctx={ctx} />; break;
    case 'audit':       page = perms.canViewAudit ? <AuditLogPage ctx={ctx} /> : <DashboardPage ctx={ctx} />; break;
    default:            page = <DashboardPage ctx={ctx} />;
  }

  // ถ้าต้อง login ก่อน — แสดง LoginScreen
  if (needsLogin) {
    return <LoginScreen users={state.users} onLogin={doLogin} />;
  }

  return (
    <div className={`app ${sidebarOpen ? 'sidebar-open' : ''}`}>
      <Sidebar state={state} setState={setState} currentUser={currentUser} onClose={() => setSidebarOpen(false)} />
      {sidebarOpen && <div className="sidebar-backdrop" onClick={() => setSidebarOpen(false)}></div>}
      <div className="main">
        <TopBar state={state} setState={setState} currentUser={currentUser} onMenu={() => setSidebarOpen(true)} onHelp={() => setHelpOpen(true)} />
        <div className="content content-narrow">
          {page}
        </div>
      </div>
      {navKey === 'g' && (
        <div style={{ position: 'fixed', bottom: 20, left: '50%', transform: 'translateX(-50%)', background: 'var(--ink)', color: 'var(--surface)', padding: '8px 14px', borderRadius: 8, fontSize: 12, fontFamily: 'var(--font-en)', boxShadow: 'var(--shadow-lg)', zIndex: 9999 }}>
          กด g แล้ว ตามด้วย: <kbd>d</kbd> dashboard · <kbd>i</kbd> inbox · <kbd>a</kbd> approvals · <kbd>m</kbd> my · <kbd>c</kbd> calendar · <kbd>s</kbd> scorecard · <kbd>x</kbd> insights
        </div>
      )}
      <CreateRequest ctx={ctx} />
      <KeyboardHelp open={helpOpen} onClose={() => setHelpOpen(false)} />
      <CommandPalette ctx={ctx} open={paletteOpen} onClose={() => setPaletteOpen(false)} />
      <ToastHost />
      <OnboardingTour ctx={ctx} />
      <BottomNav state={state} setState={setState} currentUser={currentUser} />
      <button className="fab no-print" onClick={() => setState({ createOpen: true })} title="สร้างคำขอใหม่" aria-label="สร้างคำขอใหม่">
        <Icon name="plus" size={26} />
      </button>
    </div>
  );
};

// ===== BottomNav — มือถือเท่านั้น (≤768px) =====
const BottomNav = ({ state, setState, currentUser }) => {
  const perms = getPermissions(currentUser);
  const pendingForMe = state.requests.filter(r => r.status === 'pending' && canApproveStep(r.flow[r.currentStep], currentUser.id)).length;
  const myToReceive = state.requests.filter(r => canReceiveRequest(r, currentUser, state.users)).length;
  const route = state.route;
  // 5 ปุ่มหลัก
  const items = [
    { key: 'dashboard', icon: 'home', label: 'แรก', perm: 'canDashboard' },
    { key: 'inbox', icon: 'inbox', label: 'กล่องงาน', perm: 'canInbox', badge: pendingForMe + myToReceive },
    { key: 'my-requests', icon: 'list', label: 'ของฉัน', perm: 'canMyRequests' },
    { key: 'calendar', icon: 'calendar', label: 'ปฏิทิน', perm: 'canCalendar' },
    { key: 'scorecard', icon: 'trophy', label: 'KPI', perm: 'canScorecard' }
  ].filter(it => !it.perm || perms[it.perm] !== false);
  return (
    <nav className="bottom-nav no-print" aria-label="bottom navigation">
      {items.map(it => {
        const active = route === it.key;
        return (
          <button key={it.key} className={`bottom-nav-item ${active ? 'active' : ''}`} onClick={() => setState({ route: it.key })}>
            <span style={{ position: 'relative' }}>
              <Icon name={it.icon} size={20} />
              {it.badge > 0 && (
                <span style={{ position: 'absolute', top: -4, right: -8, minWidth: 16, height: 16, padding: '0 4px', borderRadius: 100, background: 'var(--red)', color: 'white', fontSize: 10, fontWeight: 700, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-en)' }}>{it.badge > 99 ? '99+' : it.badge}</span>
              )}
            </span>
            <span className="bottom-nav-label">{it.label}</span>
          </button>
        );
      })}
    </nav>
  );
};

const OnboardingTour = ({ ctx }) => {
  const [seen, setSeen] = usePersistedState('onboarding.seen', false);
  if (seen) return null;
  return (
    <div style={{ position: 'fixed', bottom: 20, left: 20, right: 20, maxWidth: 380, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, boxShadow: 'var(--shadow-lg)', padding: 16, zIndex: 90, animation: 'slideUp 0.3s' }}>
      <div className="row spread mb-8">
        <span className="text-xs medium" style={{ color: 'var(--brand-ink)', letterSpacing: '0.02em' }}>ยินดีต้อนรับ</span>
        <button onClick={() => setSeen(true)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-3)', padding: 0 }}><Icon name="x" size={14} /></button>
      </div>
      <div className="text-sm" style={{ lineHeight: 1.5, marginBottom: 12 }}>
        ระบบนี้ใช้สำหรับสร้างและติดตามคำขออนุมัติของบริษัท — เริ่มได้จากปุ่ม <span className="medium">สร้างคำขอ</span> มุมบนขวา
      </div>
      <div className="text-xs muted">กด <kbd style={{ padding: '1px 5px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 3, fontFamily: 'var(--font-en)', fontSize: 10 }}>?</kbd> เพื่อดูทางลัดคีย์บอร์ด</div>
    </div>
  );
};

// ⟪AUTO-EXPORTS-START⟫
export { FB_MODE, LoginScreen, App, BottomNav, OnboardingTour };
// ⟪AUTO-EXPORTS-END⟫
