// ⟪AUTO-HEADER-START⟫ generated by scripts/extract.mjs + gen-imports.mjs — do not edit this region by hand
import React from 'react';
import { getSyncConfig } from '../cloud/binSync.js';
import { Avatar, Icon, Modal, StatusBadge, TypeIcon, canApproveStep, canReceiveRequest, fmtBaht, getPermissions, isUserOOO, nowTh, slaInfo } from '../lib/core.jsx';
// ⟪AUTO-HEADER-END⟫
const NAV = [
  { section: 'ภาพรวม' },
  { key: 'dashboard',   icon: 'home',     label: 'หน้าแรก' },
  { key: 'inbox',       icon: 'inbox',    label: 'กล่องงาน', badgeKey: 'approvals' },
  { key: 'insights',    icon: 'zap',      label: 'ข้อมูลเชิงลึก' },
  { section: 'งานของคุณ' },
  { key: 'my-requests', icon: 'list',     label: 'คำขอที่ส่ง' },
  { key: 'scorecard',   icon: 'star',     label: 'ผลงาน' },
  { key: 'templates',   icon: 'copy',     label: 'แม่แบบ' },
  { key: 'recurring',   icon: 'repeat',   label: 'คำขอประจำ' },
  { key: 'calendar',    icon: 'calendar', label: 'ปฏิทิน' },
  { section: 'งานที่รอจัดการ' },
  { key: 'approvals',   icon: 'inbox',    label: 'รออนุมัติ', badgeKey: 'approvals' },
  { key: 'intake',      icon: 'truck',    label: 'รอรับเรื่อง', badgeKey: 'intake' },
  { key: 'clearing',    icon: 'wallet',   label: 'เคลียร์เอกสาร', badgeKey: 'clearing' },
  { section: 'ข้อมูลและรายงาน' },
  { key: 'exec',        icon: 'bar',      label: 'รายงานผู้บริหาร' },
  { key: 'stock',       icon: 'layers',   label: 'สต๊อก' },
  { key: 'master',      icon: 'package',  label: 'ข้อมูลหลัก' },
  { key: 'audit',       icon: 'shield',   label: 'บันทึกกิจกรรม' },
  { section: 'ระบบ' },
  { key: 'settings',    icon: 'settings', label: 'ตั้งค่า' }
];

const Sidebar = ({ state, setState, currentUser, onClose }) => {
  // wrap setState — ถ้าเป็นมือถือ (drawer open) ปิด drawer หลังกด
  const isDrawerMode = typeof window !== 'undefined' && window.innerWidth <= 768;
  const navigate = (patch) => {
    setState(patch);
    if (isDrawerMode && onClose) setTimeout(onClose, 50);
  };
  const route = state.route;
  const perms = getPermissions(currentUser);
  const pendingForMe = state.requests.filter(r =>
    r.status === 'pending' && canApproveStep(r.flow[r.currentStep], currentUser.id)
  ).length;
  // นับ clearing badge — รวมของผู้ขอ + ของบัญชีที่ต้องตรวจ
  const myPendingClears = state.requests.filter(r =>
    r.requester === currentUser.id && r.type === 'expense' && r.pendingClear &&
    (!r.clearingStatus || r.clearingStatus === 'rejected') && (r.cleared || 0) < r.amount
  ).length;
  const accountingVerifyCount = currentUser.deptKey === 'accounting'
    ? state.requests.filter(r => r.type === 'expense' && r.clearingStatus === 'submitted').length
    : 0;
  const clearingBadge = myPendingClears + accountingVerifyCount;
  // จำนวนงานที่แผนกของฉัน "รอรับเรื่อง" — ใช้ canReceiveRequest แทน (dept-aware ทุกแผนก)
  const intakeCount = state.requests.filter(r => canReceiveRequest(r, currentUser, state.users)).length;

  // Map nav key → permission key
  const navPerm = {
    'dashboard': 'canDashboard', 'inbox': 'canInbox', 'insights': 'canInsights',
    'my-requests': 'canMyRequests', 'scorecard': 'canScorecard', 'templates': 'canTemplates',
    'recurring': 'canRecurring', 'calendar': 'canCalendar',
    'approvals': 'canViewApprovalsPage', 'intake': 'canViewIntake', 'clearing': 'canViewClearing',
    'exec': 'canViewExecReport', 'stock': 'canViewStockReport', 'master': 'canViewMaster',
    'audit': 'canViewAudit', 'settings': 'canViewSettings'
  };

  const badgeFor = (k) => k === 'approvals' ? pendingForMe : k === 'clearing' ? clearingBadge : k === 'intake' ? intakeCount : 0;

  return (
    <aside className="sidebar">
      <div className="sidebar-logo">
        <div className="sidebar-logo-mark">FD</div>
        <div>
          <div className="sidebar-logo-name">FlowDesk</div>
          <div className="sidebar-logo-sub">{state.requests.length > 0 ? `${state.requests.length} คำขอ · v3.4-dark` : 'ระบบคำขออนุมัติ · v3.4-dark'}</div>
        </div>
      </div>
      <nav className="sidebar-nav">
        {(() => {
          // กรอง NAV ตาม permission และซ่อน section ที่ไม่มี item เหลือ
          const result = [];
          let currentSection = null;
          let sectionHasItems = false;
          NAV.forEach((item, i) => {
            if (item.section) {
              if (currentSection !== null && sectionHasItems) result.push(currentSection);
              currentSection = <div key={i} className="nav-section">{item.section}</div>;
              sectionHasItems = false;
              return;
            }
            const permKey = navPerm[item.key];
            if (permKey && perms[permKey] === false) return; // hide
            sectionHasItems = true;
            if (currentSection) { result.push(currentSection); currentSection = null; }
            const isActive = route === item.key || (item.key === 'my-requests' && route === 'detail');
            const badge = item.badgeKey ? badgeFor(item.badgeKey) : 0;
            result.push(
              <button
                key={item.key}
                className={`nav-item ${isActive ? 'active' : ''}`}
                onClick={() => navigate({ route: item.key, selectedId: null, importTarget: null, clearTarget: null })}
              >
                <Icon name={item.icon} size={16} className="icon" />
                {item.label}
                {badge > 0 && <span className="nav-badge">{badge}</span>}
              </button>
            );
          });
          return result;
        })()}
      </nav>
      <div className="sidebar-foot" style={{ flexDirection: 'column', alignItems: 'stretch', gap: 10, padding: 12 }}>
        {pendingForMe > 0 && (
          <button className="row gap-8" onClick={() => navigate({ route: 'approvals' })} style={{ padding: '8px 10px', background: 'var(--amber-soft)', border: '1px solid oklch(85% 0.05 80)', borderRadius: 8, cursor: 'pointer', textAlign: 'left' }}>
            <Icon name="bell" size={14} style={{ color: 'var(--amber-ink)' }} />
            <div style={{ flex: 1, minWidth: 0 }}>
              <div className="text-xs medium" style={{ color: 'var(--amber-ink)' }}>{pendingForMe} คำขอรออนุมัติ</div>
              <div className="text-xs muted">กดเพื่อพิจารณา</div>
            </div>
          </button>
        )}
        <div className="row gap-10">
          <Avatar user={currentUser} size="md" />
          <div style={{ flex: 1, minWidth: 0 }}>
            <div className="text-sm medium" style={{ color: 'var(--ink)' }}>{currentUser.name.split(' ')[0]}</div>
            <div className="text-xs muted" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{currentUser.roleTh}</div>
          </div>
          <button className="btn btn-ghost btn-icon-only btn-sm" title="ตั้งค่า" onClick={() => navigate({ route: 'settings' })}>
            <Icon name="settings" size={14} />
          </button>
          <button className="btn btn-ghost btn-icon-only btn-sm" title="ออกจากระบบ" onClick={() => { if (window.__fdLogout) window.__fdLogout(); }}>
            <Icon name="x" size={14} />
          </button>
        </div>
      </div>
    </aside>
  );
};

const TopBar = ({ state, setState, currentUser, onMenu, onHelp }) => {
  const [userMenu, setUserMenu] = React.useState(false);
  const [userSearch, setUserSearch] = React.useState('');
  const [notifOpen, setNotifOpen] = React.useState(false);
  const [theme, setTheme] = React.useState(() => document.documentElement.getAttribute('data-theme') || 'light');
  const [spin, setSpin] = React.useState(false);
  const [globalQ, setGlobalQ] = React.useState('');
  const [searchOpen, setSearchOpen] = React.useState(false);
  const [syncCfg, setSyncCfg] = React.useState(getSyncConfig);
  const userMenuRef = React.useRef(null);
  const notifRef = React.useRef(null);
  const userSearchRef = React.useRef(null);
  const searchRef = React.useRef(null);

  React.useEffect(() => {
    const h = () => setSyncCfg(getSyncConfig());
    window.addEventListener('fd-sync-config-changed', h);
    const id = setInterval(() => setSyncCfg(getSyncConfig()), 5000);
    return () => { window.removeEventListener('fd-sync-config-changed', h); clearInterval(id); };
  }, []);

  React.useEffect(() => {
    const k = (e) => {
      if (e.key === 'Escape') setSearchOpen(false);
    };
    window.addEventListener('keydown', k);
    return () => window.removeEventListener('keydown', k);
  }, []);

  const toggleTheme = () => {
    const next = theme === 'dark' ? 'light' : 'dark';
    setTheme(next);
    if (next === 'dark') document.documentElement.setAttribute('data-theme', 'dark');
    else document.documentElement.removeAttribute('data-theme');
    try { localStorage.setItem('fd-theme', next); } catch (e) {}
  };
  const doRefresh = () => { setSpin(true); setTimeout(() => setSpin(false), 700); };

  React.useEffect(() => {
    const handler = (e) => {
      if (userMenuRef.current && !userMenuRef.current.contains(e.target)) { setUserMenu(false); setUserSearch(''); }
      if (notifRef.current && !notifRef.current.contains(e.target)) setNotifOpen(false);
    };
    window.addEventListener('mousedown', handler);
    return () => window.removeEventListener('mousedown', handler);
  }, []);

  React.useEffect(() => {
    if (userMenu && userSearchRef.current) setTimeout(() => userSearchRef.current?.focus(), 50);
    if (!userMenu) setUserSearch('');
  }, [userMenu]);

  const myReqIds = new Set(state.requests.filter(r => r.requester === currentUser.id).map(r => r.id));
  const notifs = [
    ...state.requests.filter(r => r.status === 'pending' && canApproveStep(r.flow[r.currentStep], currentUser.id)).slice(0, 5).map(r => ({ at: r.lastActivity || 'รอ', text: `${r.id} ${r.title} — รออนุมัติของคุณ`, type: 'approve', reqId: r.id })),
    // 🆕 คำขอที่อนุมัติครบ — รอแผนกของฉันกดรับเรื่อง
    ...state.requests.filter(r => canReceiveRequest(r, currentUser, state.users)).slice(0, 5).map(r => ({ at: r.lastActivity || 'พร้อมรับ', text: `${r.id} ${r.title} — อนุมัติครบแล้ว รอรับเรื่อง`, type: 'qr', reqId: r.id })),
    ...state.activities.filter(a => myReqIds.has(a.refId) && a.user !== currentUser.id).slice(0, 5).map(a => { const u = state.users[a.user]; return { at: a.at.split(' ')[1] || a.at, text: `${u?.name?.split(' ')[0] || a.user} ${a.summary} ${a.refId}`, type: a.action === 'approve' ? 'approve' : a.action === 'reject' ? 'reject' : 'qr', reqId: a.refId }; }),
    ...state.requests.filter(r => r.requester === currentUser.id && r.pendingClear && r.type === 'expense' && (r.status === 'progress' || r.status === 'done') && r.clearDueDate).slice(0, 3).map(r => { const sla = slaInfo(r.clearDueDate); return sla && (sla.level === 'overdue' || sla.level === 'urgent' || sla.level === 'today') ? { at: 'SLA', text: `${r.id} ต้องเคลียร์เอกสาร — ${sla.label}`, type: 'warn', reqId: r.id } : null; }).filter(Boolean)
  ].slice(0, 10);
  const hasNotifs = notifs.length > 0;

  const q = globalQ.trim().toLowerCase();
  const matched = q ? (() => {
    const reqMatches = state.requests.filter(r => (r.id + r.title + (r.purpose || '')).toLowerCase().includes(q)).slice(0, 6);
    const userMatches = Object.values(state.users).filter(u => (u.name + u.id + u.dept + u.roleTh).toLowerCase().includes(q)).slice(0, 5);
    const productMatches = state.products.filter(p => (p.sku + p.nameTh).toLowerCase().includes(q)).slice(0, 4);
    return { reqMatches, userMatches, productMatches };
  })() : null;

  return (
    <header className="topbar">
      <button className="btn btn-ghost btn-icon-only menu-btn" onClick={onMenu} title="เมนู"><Icon name="menu" size={18} /></button>
      <div className="search" ref={searchRef} style={{ position: 'relative' }}>
        <Icon name="search" size={14} className="search-icon" />
        <input placeholder="ค้นหาคำขอ, พนักงาน, สินค้า... (Ctrl+K)" value={globalQ}
          onChange={e => { setGlobalQ(e.target.value); setSearchOpen(true); }}
          onFocus={() => setSearchOpen(true)}
          onBlur={() => setTimeout(() => setSearchOpen(false), 150)} />
        {searchOpen && q && matched && (
          <div className="dropdown-menu" style={{ position: 'absolute', top: 'calc(100% + 4px)', left: 0, right: 0, maxHeight: 480, overflowY: 'auto', padding: 4 }}>
            {matched.reqMatches.length === 0 && matched.userMatches.length === 0 && matched.productMatches.length === 0 && (
              <div className="text-xs muted center" style={{ padding: 24 }}>ไม่พบผลลัพธ์สำหรับ "{q}"</div>
            )}
            {matched.reqMatches.length > 0 && (
              <div>
                <div className="text-xs muted" style={{ padding: '8px 10px 4px', fontWeight: 600, textTransform: 'uppercase' }}>คำขอ · {matched.reqMatches.length}</div>
                {matched.reqMatches.map(r => (
                  <button key={r.id} className="dropdown-item" onMouseDown={() => { setState({ route: 'detail', selectedId: r.id }); setSearchOpen(false); setGlobalQ(''); }}>
                    <TypeIcon type={r.type} size={28} />
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div className="row gap-8"><span className="en tnum text-xs muted">{r.id}</span><StatusBadge status={r.status} /></div>
                      <div className="text-sm medium" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.title}</div>
                    </div>
                  </button>
                ))}
              </div>
            )}
            {matched.userMatches.length > 0 && (
              <div>
                <div className="text-xs muted" style={{ padding: '8px 10px 4px', fontWeight: 600, textTransform: 'uppercase', borderTop: '1px solid var(--border)', marginTop: 4 }}>พนักงาน · {matched.userMatches.length}</div>
                {matched.userMatches.map(u => (
                  <button key={u.id} className="dropdown-item" onMouseDown={() => { setState({ currentUserId: u.id, route: 'dashboard' }); setSearchOpen(false); setGlobalQ(''); }}>
                    <Avatar user={u} size="sm" />
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div className="text-sm medium" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{u.name}</div>
                      <div className="text-xs muted">{u.roleTh} · {u.dept}</div>
                    </div>
                  </button>
                ))}
              </div>
            )}
            {matched.productMatches.length > 0 && (
              <div>
                <div className="text-xs muted" style={{ padding: '8px 10px 4px', fontWeight: 600, textTransform: 'uppercase', borderTop: '1px solid var(--border)', marginTop: 4 }}>สินค้า · {matched.productMatches.length}</div>
                {matched.productMatches.map(p => (
                  <button key={p.sku} className="dropdown-item" onMouseDown={() => { setState({ route: 'master' }); setSearchOpen(false); setGlobalQ(''); }}>
                    <div style={{ width: 28, height: 28, borderRadius: 6, background: 'var(--brand-soft)', color: 'var(--brand-ink)', display: 'grid', placeItems: 'center' }}><Icon name="package" size={14} /></div>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div className="text-sm medium" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{p.nameTh}</div>
                      <div className="text-xs muted en">{p.sku} · {fmtBaht(p.price)}</div>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
      <div className="topbar-actions">
        <button className="btn btn-primary btn-sm" onClick={() => setState({ createOpen: true })} title="สร้างคำขอ">
          <Icon name="plus" size={13} /> <span className="topbar-mobile-hide">สร้างคำขอ</span>
        </button>

        <button className="btn btn-ghost btn-icon-only topbar-mobile-hide" title="รีเฟรช" onClick={doRefresh}>
          <span style={{ display: 'inline-flex', transition: 'transform 0.7s', transform: spin ? 'rotate(360deg)' : 'none' }}>
            <Icon name="refresh" size={16} />
          </span>
        </button>
        <button className="btn btn-ghost btn-icon-only" title={theme === 'dark' ? 'โหมดสว่าง' : 'โหมดมืด'} onClick={toggleTheme}>
          <Icon name={theme === 'dark' ? 'sun' : 'moon'} size={16} />
        </button>
        <button className="btn btn-ghost btn-icon-only" style={{ position: 'relative' }} title={syncCfg.enabled ? `Cloud Sync: เปิด · ดันล่าสุด ${syncCfg.lastPushAt ? new Date(syncCfg.lastPushAt).toLocaleTimeString('th-TH') : 'ยังไม่เคย'}` : 'Cloud Sync: ปิด (กดเพื่อตั้งค่า)'} onClick={() => { setState({ route: 'settings' }); try { localStorage.setItem('fd-settings.tab', JSON.stringify('sync')); } catch (e) {} }}>
          <Icon name="cloud" size={16} style={{ color: syncCfg.enabled ? 'var(--green-ink)' : 'var(--ink-3)' }} />
          {syncCfg.enabled && <span style={{ position: 'absolute', top: 8, right: 8, width: 6, height: 6, borderRadius: 100, background: 'var(--green)', border: '1.5px solid var(--surface)' }}></span>}
        </button>
        <button className="btn btn-ghost btn-icon-only topbar-mobile-hide" title="ทางลัด (?)" onClick={onHelp}>
          <Icon name="info" size={16} />
        </button>

        <div className="dropdown" ref={notifRef}>
          <button className="btn btn-ghost btn-icon-only" onClick={() => setNotifOpen(!notifOpen)} style={{ position: 'relative' }}>
            <Icon name="bell" size={16} />
            {hasNotifs && <span style={{
              position: 'absolute', top: 6, right: 6,
              width: 8, height: 8, borderRadius: 100,
              background: 'var(--red)',
              border: '2px solid var(--surface)'
            }}></span>}
          </button>
          {notifOpen && (() => {
            const [notifTab, _setNotifTab] = [window.__notifTab || 'all', (v) => { window.__notifTab = v; setNotifOpen(false); setTimeout(() => setNotifOpen(true), 0); }];
            const grouped = {
              all: notifs,
              approve: notifs.filter(n => n.type === 'approve' || n.type === 'reject'),
              warn: notifs.filter(n => n.type === 'warn'),
              other: notifs.filter(n => n.type !== 'approve' && n.type !== 'reject' && n.type !== 'warn')
            };
            const tabList = grouped[notifTab] || notifs;
            return (
            <div className="dropdown-menu" style={{ width: 360, maxHeight: 540, overflowY: 'auto' }}>
              <div className="spread" style={{ padding: '8px 10px', borderBottom: '1px solid var(--border)' }}>
                <span className="bold text-sm">การแจ้งเตือน</span>
                <span className="text-xs muted en">{notifs.length} รายการ</span>
              </div>
              {/* Tabs */}
              <div className="row gap-4" style={{ padding: '6px 8px', borderBottom: '1px solid var(--border)' }}>
                {[
                  ['all', `ทั้งหมด · ${grouped.all.length}`],
                  ['approve', `อนุมัติ · ${grouped.approve.length}`],
                  ['warn', `แจ้งเตือน · ${grouped.warn.length}`],
                  ['other', `อื่นๆ · ${grouped.other.length}`]
                ].map(([key, lbl]) => (
                  <button key={key} onClick={() => _setNotifTab(key)} style={{ padding: '4px 8px', borderRadius: 5, border: 'none', cursor: 'pointer', background: notifTab === key ? 'var(--brand-soft)' : 'transparent', color: notifTab === key ? 'var(--brand-ink)' : 'var(--ink-3)', fontSize: 11, fontWeight: 500 }}>{lbl}</button>
                ))}
              </div>
              {tabList.length === 0 && <div className="text-xs muted center" style={{ padding: 30 }}>ไม่มีการแจ้งเตือนในหมวดนี้</div>}
              {tabList.map((n, i) => (
                <button key={i} className="dropdown-item" style={{ alignItems: 'flex-start', padding: '10px 10px' }}
                  onClick={() => { if (n.reqId) setState({ route: 'detail', selectedId: n.reqId }); setNotifOpen(false); }}>
                  <div style={{
                    width: 26, height: 26, borderRadius: 100,
                    background: n.type === 'approve' ? 'var(--green-soft)' : n.type === 'reject' ? 'var(--red-soft)' : n.type === 'warn' ? 'var(--amber-soft)' : 'var(--brand-soft)',
                    color: n.type === 'approve' ? 'var(--green-ink)' : n.type === 'reject' ? 'var(--red-ink)' : n.type === 'warn' ? 'var(--amber-ink)' : 'var(--brand-ink)',
                    display: 'grid', placeItems: 'center', flexShrink: 0
                  }}>
                    <Icon name={n.type === 'approve' ? 'check' : n.type === 'reject' ? 'x' : n.type === 'warn' ? 'warning' : 'qr'} size={12} />
                  </div>
                  <div style={{ flex: 1, minWidth: 0, textAlign: 'left' }}>
                    <div className="text-sm" style={{ lineHeight: 1.4, whiteSpace: 'normal' }}>{n.text}</div>
                    <div className="text-xs muted en mt-2">{n.at}</div>
                  </div>
                </button>
              ))}
              <div className="dropdown-sep"></div>
              <button className="dropdown-item center" style={{ color: 'var(--brand-ink)', justifyContent: 'center' }} onClick={() => { setState({ route: 'audit' }); setNotifOpen(false); }}>ดู Audit Log ทั้งหมด</button>
            </div>
            );
          })()}
        </div>

        <div className="dropdown" ref={userMenuRef}>
          <button
            className="btn btn-ghost btn-sm"
            onClick={() => setUserMenu(!userMenu)}
            style={{ padding: '4px 8px', height: 36, gap: 8 }}
          >
            <Avatar user={currentUser} size="sm" />
            <div className="role-switcher-text" style={{ textAlign: 'left' }}>
              <div className="text-xs muted" style={{ fontSize: 10, lineHeight: 1 }}>{currentUser.dept}</div>
              <div className="text-sm medium" style={{ lineHeight: 1.2 }}>{currentUser.name?.split(' ')[0] || currentUser.role}</div>
            </div>
            <Icon name="chevronDown" size={13} />
          </button>
          {userMenu && (() => {
            // Quick KPI for current user — today
            const todayStr = (() => { const d = new Date(); return `${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`; })();
            const myToday = state.activities.filter(a => a.user === currentUser.id && a.at && a.at.startsWith(todayStr));
            const myPending = state.requests.filter(r => r.requester === currentUser.id && r.status === 'pending').length;
            const myApprovals = state.requests.filter(r => r.status === 'pending' && canApproveStep(r.flow[r.currentStep], currentUser.id)).length;
            const logout = () => {
              if (!confirm('ออกจากระบบ?')) return;
              try { localStorage.removeItem('fd-session-user'); } catch (e) {}
              if (window.__fdLogout) window.__fdLogout();
              else window.location.reload();
            };
            return (
              <div className="dropdown-menu" style={{ width: 280 }}>
                {/* User Card */}
                <div style={{ padding: 14, background: 'linear-gradient(135deg, color-mix(in oklch, var(--brand) 8%, var(--surface)) 0%, var(--surface) 100%)', borderBottom: '1px solid var(--border)' }}>
                  <div className="row gap-10 mb-12" style={{ alignItems: 'center' }}>
                    <Avatar user={currentUser} size="lg" />
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div className="medium" style={{ fontSize: 14 }}>{currentUser.name}</div>
                      <div className="text-xs muted">{currentUser.roleTh}</div>
                      <div className="text-xs muted en">{currentUser.id} · {currentUser.dept}</div>
                    </div>
                  </div>
                  <div className="grid grid-3" style={{ gap: 6 }}>
                    <div style={{ padding: 6, background: 'var(--surface)', borderRadius: 6, textAlign: 'center', border: '1px solid var(--border)' }}>
                      <div className="en bold" style={{ fontSize: 16, color: myApprovals > 0 ? 'var(--amber-ink)' : 'var(--ink-3)', lineHeight: 1 }}>{myApprovals}</div>
                      <div className="text-xs muted mt-2" style={{ fontSize: 10 }}>รออนุมัติ</div>
                    </div>
                    <div style={{ padding: 6, background: 'var(--surface)', borderRadius: 6, textAlign: 'center', border: '1px solid var(--border)' }}>
                      <div className="en bold" style={{ fontSize: 16, color: myPending > 0 ? 'var(--blue-ink)' : 'var(--ink-3)', lineHeight: 1 }}>{myPending}</div>
                      <div className="text-xs muted mt-2" style={{ fontSize: 10 }}>รอผล</div>
                    </div>
                    <div style={{ padding: 6, background: 'var(--surface)', borderRadius: 6, textAlign: 'center', border: '1px solid var(--border)' }}>
                      <div className="en bold" style={{ fontSize: 16, color: myToday.length > 0 ? 'var(--green-ink)' : 'var(--ink-3)', lineHeight: 1 }}>{myToday.length}</div>
                      <div className="text-xs muted mt-2" style={{ fontSize: 10 }}>วันนี้</div>
                    </div>
                  </div>
                  {isUserOOO(currentUser.id) && (
                    <div className="row gap-6 mt-8" style={{ padding: '4px 8px', background: 'var(--amber-soft)', borderRadius: 6, alignItems: 'center' }}>
                      <Icon name="bellOff" size={11} style={{ color: 'var(--amber-ink)' }} />
                      <span className="text-xs medium" style={{ color: 'var(--amber-ink)', fontSize: 11 }}>โหมด OOO เปิดอยู่</span>
                    </div>
                  )}
                </div>

                {/* Menu items */}
                <button className="dropdown-item" onClick={() => { setState({ route: 'scorecard' }); setUserMenu(false); }}>
                  <Icon name="trophy" size={14} /> ผลงานของฉัน
                </button>
                <button className="dropdown-item" onClick={() => { setState({ route: 'my-requests' }); setUserMenu(false); }}>
                  <Icon name="list" size={14} /> คำขอที่ฉันส่ง
                </button>
                <button className="dropdown-item" onClick={() => { setState({ route: 'settings' }); try { localStorage.setItem('fd-settings.tab', JSON.stringify('ooo')); } catch (e) {} setUserMenu(false); }}>
                  <Icon name="bellOff" size={14} /> ตั้งค่า Out of Office
                </button>
                <button className="dropdown-item" onClick={() => { setState({ route: 'settings' }); try { localStorage.setItem('fd-settings.tab', JSON.stringify('signature')); } catch (e) {} setUserMenu(false); }}>
                  <Icon name="edit" size={14} /> ลายเซ็นของฉัน
                </button>
                <div className="dropdown-sep"></div>
                <button className="dropdown-item" onClick={logout} style={{ color: 'var(--red-ink)' }}>
                  <Icon name="x" size={14} /> ออกจากระบบ (Logout)
                </button>
              </div>
            );
          })()}
        </div>
      </div>
    </header>
  );
};

const KEYBOARD_SHORTCUTS = [
  { group: 'การนำทาง', items: [
    { keys: ['Ctrl/⌘', 'K'], action: 'เปิด Global Search' },
    { keys: ['G', 'D'], action: 'ไปหน้า Dashboard' },
    { keys: ['G', 'I'], action: 'ไปกล่องงาน Inbox' },
    { keys: ['G', 'A'], action: 'ไปหน้ารออนุมัติ' },
    { keys: ['G', 'M'], action: 'ไปคำขอของฉัน' },
    { keys: ['G', 'C'], action: 'ไปปฏิทิน' }
  ]},
  { group: 'การทำงานกับคำขอ', items: [
    { keys: ['N'], action: 'สร้างคำขอใหม่' },
    { keys: ['A'], action: 'อนุมัติ (ในหน้า Detail)' },
    { keys: ['R'], action: 'ปฏิเสธ (ในหน้า Detail)' },
    { keys: ['Ctrl/⌘', 'Enter'], action: 'ส่งความคิดเห็น (ในกล่องคอมเมนต์)' }
  ]},
  { group: 'อื่นๆ', items: [
    { keys: ['?'], action: 'แสดงทางลัดคีย์บอร์ด' },
    { keys: ['Esc'], action: 'ปิด Modal / Search' },
    { keys: ['T'], action: 'สลับ Dark/Light mode' }
  ]}
];

// ===== Command Palette (Ctrl+K) — Action center + search =====
const CommandPalette = ({ ctx, open, onClose }) => {
  const { state, setState } = ctx;
  const [q, setQ] = React.useState('');
  const [idx, setIdx] = React.useState(0);
  const inputRef = React.useRef(null);
  const listRef = React.useRef(null);
  // ===== Saved searches (per-user) =====
  const SAVED_KEY = 'fd-saved-searches';
  const [savedSearches, setSavedSearches] = React.useState(() => {
    try { return JSON.parse(localStorage.getItem(SAVED_KEY)) || []; } catch (e) { return []; }
  });
  const saveCurrentSearch = () => {
    if (!q.trim()) return;
    const next = [{ q: q.trim(), at: nowTh() }, ...savedSearches.filter(s => s.q !== q.trim())].slice(0, 10);
    setSavedSearches(next);
    try { localStorage.setItem(SAVED_KEY, JSON.stringify(next)); } catch (e) {}
    window.toast?.(`บันทึก "${q}" แล้ว`, { level: 'success' });
  };
  const deleteSavedSearch = (s) => {
    const next = savedSearches.filter(x => x.q !== s);
    setSavedSearches(next);
    try { localStorage.setItem(SAVED_KEY, JSON.stringify(next)); } catch (e) {}
  };

  React.useEffect(() => {
    if (open) { setQ(''); setIdx(0); setTimeout(() => inputRef.current?.focus(), 50); }
  }, [open]);

  // Build action list
  const actions = React.useMemo(() => {
    const goto = (route) => () => { setState({ route, selectedId: null }); onClose(); };
    const create = (type) => () => { setState({ createOpen: true, createTemplate: { type, preset: {} } }); onClose(); };
    const toggleTheme = () => {
      const next = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
      if (next === 'dark') document.documentElement.setAttribute('data-theme', 'dark'); else document.documentElement.removeAttribute('data-theme');
      try { localStorage.setItem('fd-theme', next); } catch (e) {}
      onClose();
    };
    return [
      { id: 'a-new', kind: 'action', label: 'สร้างคำขอใหม่', hint: 'เลือกประเภทคำขอ', icon: 'plus', keywords: 'new create เพิ่ม', onSelect: () => { setState({ createOpen: true, createTemplate: null }); onClose(); } },
      { id: 'a-new-event', kind: 'action', label: 'สร้างคำขออีเว้นท์', hint: 'จัดงาน · งบประมาณ', icon: 'calendar', keywords: 'event อีเวนท์ จัดงาน', onSelect: create('event') },
      { id: 'a-new-expense', kind: 'action', label: 'สร้างคำขอเบิกเงิน', hint: 'เบิกเงินสดล่วงหน้า', icon: 'wallet', keywords: 'expense เบิกเงิน iou', onSelect: create('expense') },
      { id: 'a-new-purchase', kind: 'action', label: 'สร้างคำขอจัดซื้อ', hint: 'อนุมัติซื้อของ', icon: 'tag', keywords: 'purchase ซื้อ', onSelect: create('purchase') },
      { id: 'a-new-borrow', kind: 'action', label: 'สร้างใบยืม-คืน', hint: 'ยืมสินค้าออกบูธ', icon: 'repeat', keywords: 'borrow ยืม', onSelect: create('borrow') },
      { id: 'a-new-ot', kind: 'action', label: 'สร้างคำขอ OT', hint: 'ทำงานล่วงเวลา', icon: 'clock', keywords: 'overtime ot โอที', onSelect: create('overtime') },
      { id: 'a-new-leave', kind: 'action', label: 'สร้างใบลา', hint: 'ลาป่วย · ลากิจ · ลาพักร้อน', icon: 'user', keywords: 'leave ลา', onSelect: create('leave') },
      { id: 'g-dashboard', kind: 'nav', label: 'ไปหน้าแรก', hint: 'g d', icon: 'home', keywords: 'home dashboard', onSelect: goto('dashboard') },
      { id: 'g-inbox', kind: 'nav', label: 'ไปกล่องงาน', hint: 'g i', icon: 'inbox', keywords: 'inbox', onSelect: goto('inbox') },
      { id: 'g-approvals', kind: 'nav', label: 'ไปรออนุมัติ', hint: 'g a', icon: 'check', keywords: 'approval', onSelect: goto('approvals') },
      { id: 'g-my', kind: 'nav', label: 'ไปคำขอที่ส่ง', hint: 'g m', icon: 'list', keywords: 'my requests', onSelect: goto('my-requests') },
      { id: 'g-calendar', kind: 'nav', label: 'ไปปฏิทิน', hint: 'g c', icon: 'calendar', keywords: 'calendar ปฏิทิน', onSelect: goto('calendar') },
      { id: 'g-insights', kind: 'nav', label: 'ไปข้อมูลเชิงลึก', hint: 'g x', icon: 'zap', keywords: 'insights analytics', onSelect: goto('insights') },
      { id: 'g-scorecard', kind: 'nav', label: 'ไปผลงาน', hint: 'g s', icon: 'star', keywords: 'scorecard performance', onSelect: goto('scorecard') },
      { id: 'g-exec', kind: 'nav', label: 'ไปรายงานผู้บริหาร', icon: 'bar', keywords: 'report executive', onSelect: goto('exec') },
      { id: 'g-audit', kind: 'nav', label: 'ไปบันทึกกิจกรรม', icon: 'shield', keywords: 'audit log', onSelect: goto('audit') },
      { id: 'g-settings', kind: 'nav', label: 'ไปตั้งค่า', icon: 'settings', keywords: 'settings ตั้งค่า', onSelect: goto('settings') },
      { id: 'g-signature', kind: 'nav', label: 'ตั้งลายเซ็นของฉัน', hint: 'ตั้งค่า → ลายเซ็น', icon: 'edit', keywords: 'signature ลายเซ็น', onSelect: () => { setState({ route: 'settings' }); try { localStorage.setItem('fd-settings.tab', JSON.stringify('signature')); } catch (e) {} onClose(); } },
      { id: 'g-workflow', kind: 'nav', label: 'แก้ไข Workflow', hint: 'ตั้งค่า → สายอนุมัติ', icon: 'settings', keywords: 'workflow flow rules', onSelect: () => { setState({ route: 'settings' }); try { localStorage.setItem('fd-settings.tab', JSON.stringify('flow')); } catch (e) {} onClose(); } },
      { id: 't-theme', kind: 'system', label: 'สลับโหมดสว่าง/มืด', hint: 'T', icon: document.documentElement.getAttribute('data-theme') === 'dark' ? 'sun' : 'moon', keywords: 'theme dark light', onSelect: toggleTheme },
      { id: 't-help', kind: 'system', label: 'ดูทางลัดคีย์บอร์ด', hint: '?', icon: 'info', keywords: 'help shortcuts', onSelect: () => { onClose(); setTimeout(() => window.dispatchEvent(new CustomEvent('fd-open-help')), 50); } }
    ];
  }, [setState, onClose]);

  const ql = q.trim().toLowerCase();
  const filtered = React.useMemo(() => {
    if (!ql) return { actions, requests: [], users: [], products: [], comments: [] };
    const score = (text) => text.toLowerCase().includes(ql) ? 1 : 0;
    const acts = actions.filter(a => score(a.label) || score(a.keywords || '') || score(a.hint || ''));
    // Deep search: รวม breakdown labels, items, venue
    const reqs = state.requests.filter(r => {
      if (score(r.id) || score(r.title) || score(r.purpose || '')) return true;
      if (r.venue && score(r.venue)) return true;
      if (r.breakdown && r.breakdown.some(b => score(b.label || ''))) return true;
      if (r.items && r.items.some(it => score(it.name || '') || score(it.sku || ''))) return true;
      return false;
    }).slice(0, 8);
    const usrs = Object.values(state.users).filter(u => score(u.name) || score(u.id) || score(u.roleTh) || score(u.dept)).slice(0, 5);
    const prods = state.products.filter(p => score(p.sku) || score(p.nameTh) || score(p.name || '')).slice(0, 4);
    // Comments search — match in discussion text
    const cmts = [];
    state.requests.forEach(r => {
      (r.discussion || []).forEach((c, ci) => {
        if (score(c.text)) cmts.push({ req: r, comment: c, ci });
      });
    });
    return { actions: acts, requests: reqs, users: usrs, products: prods, comments: cmts.slice(0, 5) };
  }, [ql, actions, state.requests, state.users, state.products]);

  const flat = React.useMemo(() => {
    const arr = [];
    filtered.actions.forEach(a => arr.push({ ...a, group: 'คำสั่ง' }));
    filtered.requests.forEach(r => arr.push({ kind: 'req', group: 'คำขอ', id: 'req-' + r.id, label: r.title, hint: r.id, data: r, onSelect: () => { setState({ route: 'detail', selectedId: r.id }); onClose(); } }));
    filtered.users.forEach(u => arr.push({ kind: 'user', group: 'พนักงาน', id: 'usr-' + u.id, label: u.name, hint: u.roleTh + ' · ' + u.dept, data: u, onSelect: () => { setState({ currentUserId: u.id, route: 'dashboard' }); onClose(); } }));
    filtered.products.forEach(p => arr.push({ kind: 'product', group: 'สินค้า', id: 'prd-' + p.sku, label: p.nameTh, hint: p.sku, data: p, onSelect: () => { setState({ route: 'master' }); onClose(); } }));
    (filtered.comments || []).forEach((c, i) => {
      const u = state.users[c.comment.by];
      arr.push({ kind: 'comment', group: 'ความคิดเห็น', id: 'cmt-' + c.req.id + '-' + c.ci, label: c.comment.text.slice(0, 60) + (c.comment.text.length > 60 ? '…' : ''), hint: `${c.req.id} · ${u?.name?.split(' ')[0] || c.comment.by}`, data: c, onSelect: () => { setState({ route: 'detail', selectedId: c.req.id }); onClose(); } });
    });
    return arr;
  }, [filtered, setState, onClose, state.users]);

  React.useEffect(() => { setIdx(0); }, [ql]);
  React.useEffect(() => {
    const cur = listRef.current?.querySelector('[data-cmd-idx="' + idx + '"]');
    cur?.scrollIntoView({ block: 'nearest' });
  }, [idx]);

  const onKey = (e) => {
    if (e.key === 'ArrowDown') { e.preventDefault(); setIdx(i => Math.min(flat.length - 1, i + 1)); }
    else if (e.key === 'ArrowUp') { e.preventDefault(); setIdx(i => Math.max(0, i - 1)); }
    else if (e.key === 'Enter') { e.preventDefault(); flat[idx]?.onSelect?.(); }
    else if (e.key === 'Escape') { e.preventDefault(); onClose(); }
  };

  if (!open) return null;

  // Group items by group label
  let lastGroup = null;
  return (
    <div className="modal-backdrop" onClick={onClose} style={{ alignItems: 'flex-start', paddingTop: '12vh' }}>
      <div onClick={(e) => e.stopPropagation()} style={{ background: 'var(--surface)', borderRadius: 14, boxShadow: '0 24px 64px -12px oklch(20% 0.04 60 / 0.35), 0 8px 16px -8px oklch(20% 0.04 60 / 0.2)', maxWidth: 640, width: '100%', maxHeight: '70vh', display: 'flex', flexDirection: 'column', overflow: 'hidden', animation: 'scaleIn 0.16s ease-out' }}>
        <div className="row gap-10" style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)' }}>
          <Icon name="search" size={16} style={{ color: 'var(--ink-3)' }} />
          <input ref={inputRef} value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={onKey}
            placeholder="พิมพ์เพื่อค้นหา หรือคำสั่ง..."
            style={{ flex: 1, border: 0, outline: 0, background: 'transparent', fontSize: 15, fontFamily: 'var(--font-thai)', color: 'var(--ink)' }} />
          {q.trim() && (
            <button onClick={saveCurrentSearch} title="บันทึกการค้นหานี้" style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--brand-ink)', padding: '4px 6px' }}><Icon name="bookmark" size={13} /></button>
          )}
          <kbd style={{ padding: '2px 6px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 4, fontFamily: 'var(--font-en)', fontSize: 10, color: 'var(--ink-3)' }}>esc</kbd>
        </div>
        <div ref={listRef} style={{ overflowY: 'auto', flex: 1, padding: 6 }}>
          {!q.trim() && savedSearches.length > 0 && (
            <>
              <div className="text-xs muted" style={{ padding: '10px 12px 4px', fontWeight: 600, letterSpacing: '0.04em', textTransform: 'uppercase' }}>ค้นหาที่บันทึก</div>
              {savedSearches.map((s, i) => (
                <div key={i} className="row gap-10" style={{ padding: '8px 12px', cursor: 'pointer', borderRadius: 8, alignItems: 'center' }} onClick={() => setQ(s.q)}>
                  <Icon name="bookmark" size={13} style={{ color: 'var(--ink-3)' }} />
                  <div style={{ flex: 1 }} className="text-sm">{s.q}</div>
                  <span className="text-xs muted en">{s.at}</span>
                  <button onClick={(e) => { e.stopPropagation(); deleteSavedSearch(s.q); }} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-4)', padding: 2 }} title="ลบ"><Icon name="x" size={11} /></button>
                </div>
              ))}
            </>
          )}
          {flat.length === 0 && !q.trim() && savedSearches.length === 0 ? (
            <div className="text-xs muted center" style={{ padding: 40 }}>เริ่มพิมพ์เพื่อค้นหา</div>
          ) : flat.length === 0 ? (
            <div className="text-xs muted center" style={{ padding: 40 }}>ไม่พบผลลัพธ์สำหรับ "{q}"</div>
          ) : flat.map((item, i) => {
            const showGroup = item.group !== lastGroup;
            lastGroup = item.group;
            const active = i === idx;
            return (
              <React.Fragment key={item.id}>
                {showGroup && <div className="text-xs muted" style={{ padding: '10px 12px 4px', fontWeight: 600, letterSpacing: '0.04em', textTransform: 'uppercase' }}>{item.group}</div>}
                <div data-cmd-idx={i}
                  onClick={() => item.onSelect?.()}
                  onMouseEnter={() => setIdx(i)}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 12, padding: '8px 12px',
                    borderRadius: 8, cursor: 'pointer',
                    background: active ? 'var(--brand-soft)' : 'transparent',
                    color: active ? 'var(--brand-ink)' : 'var(--ink)',
                    transition: 'background 0.1s'
                  }}>
                  {item.kind === 'user' && item.data ? <Avatar user={item.data} size="sm" /> :
                   item.kind === 'req' && item.data ? <TypeIcon type={item.data.type} size={26} /> :
                   item.kind === 'product' ? <div style={{ width: 26, height: 26, borderRadius: 6, background: 'var(--brand-soft)', color: 'var(--brand-ink)', display: 'grid', placeItems: 'center' }}><Icon name="package" size={13} /></div> :
                   item.icon ? <div style={{ width: 26, height: 26, borderRadius: 6, background: active ? 'var(--surface)' : 'var(--surface-2)', color: 'var(--ink-2)', display: 'grid', placeItems: 'center' }}><Icon name={item.icon} size={13} /></div> :
                   <div style={{ width: 26 }}></div>}
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div className="text-sm medium" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{item.label}</div>
                    {item.hint && <div className="text-xs muted" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{item.hint}</div>}
                  </div>
                  {active && <Icon name="arrowRight" size={12} style={{ color: 'var(--brand-ink)', opacity: 0.6 }} />}
                </div>
              </React.Fragment>
            );
          })}
        </div>
        <div className="row spread" style={{ padding: '8px 12px', borderTop: '1px solid var(--border)', background: 'var(--surface-2)', fontSize: 11, color: 'var(--ink-3)' }}>
          <div className="row gap-10">
            <span><kbd style={{ padding: '1px 5px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 3, fontFamily: 'var(--font-en)' }}>↑↓</kbd> เลื่อน</span>
            <span><kbd style={{ padding: '1px 5px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 3, fontFamily: 'var(--font-en)' }}>↵</kbd> เลือก</span>
          </div>
          <span className="en">{flat.length} รายการ</span>
        </div>
      </div>
    </div>
  );
};

const KeyboardHelp = ({ open, onClose }) => {
  if (!open) return null;
  return (
    <Modal open={open} onClose={onClose} title="ทางลัดคีย์บอร์ด" wide>
      <div className="grid grid-2" style={{ gap: 20 }}>
        {KEYBOARD_SHORTCUTS.map((g, gi) => (
          <div key={gi}>
            <div className="text-xs muted en" style={{ fontWeight: 600, letterSpacing: '0.04em', textTransform: 'uppercase', marginBottom: 10 }}>{g.group}</div>
            <div className="col gap-6">
              {g.items.map((it, ii) => (
                <div key={ii} className="row spread" style={{ padding: 6 }}>
                  <span className="text-sm">{it.action}</span>
                  <div className="row gap-3">
                    {it.keys.map((k, ki) => (
                      <React.Fragment key={ki}>
                        {ki > 0 && <span className="text-xs muted">+</span>}
                        <kbd style={{ padding: '2px 8px', background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 4, fontFamily: 'var(--font-en)', fontSize: 11, fontWeight: 600 }}>{k}</kbd>
                      </React.Fragment>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </Modal>
  );
};

// ⟪AUTO-EXPORTS-START⟫
export { NAV, Sidebar, TopBar, KEYBOARD_SHORTCUTS, CommandPalette, KeyboardHelp };
// ⟪AUTO-EXPORTS-END⟫
