#!/usr/bin/env node
/**
 * extract.mjs — สกัดโมดูลจาก original/index.html (ไฟล์ต้นฉบับ 13,472 บรรทัด)
 *
 * หลักการ: เนื้อโค้ดในแต่ละ <script> block ถูกคัดลอกแบบ byte-identical
 * ไม่แก้ไขอะไรข้างในเลย ยกเว้น transform เดียวที่ประกาศไว้ (บรรทัดแรกของ mock.js)
 * ส่วน import/export ถูกเติมใน region ที่มี marker ครอบ ตรวจย้อนได้ด้วย --verify
 *
 * ใช้งาน:
 *   node scripts/extract.mjs           # สกัดทุกโมดูล (เขียนทับ region ที่ generate เท่านั้น)
 *   node scripts/extract.mjs --verify  # byte-diff เนื้อ body ของทุกโมดูลกับต้นฉบับ
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = path.join(ROOT, 'original', 'index.html');

// marker ครอบ region ที่ generate — ห้ามแก้มือ
export const HDR_START = '// ⟪AUTO-HEADER-START⟫ generated by scripts/extract.mjs + gen-imports.mjs — do not edit this region by hand';
export const HDR_END = '// ⟪AUTO-HEADER-END⟫';
export const EXP_START = '// ⟪AUTO-EXPORTS-START⟫';
export const EXP_END = '// ⟪AUTO-EXPORTS-END⟫';

// manifest: บรรทัด (1-based, รวมปลายทั้งสองข้าง) ของ original/index.html → ไฟล์เป้าหมาย
// boundary ทุกจุดตรวจกับไฟล์จริงแล้ว (เปิด/ปิด <script> tag อยู่นอก range เสมอ)
export const MANIFEST = [
  { file: 'src/styles/global.css',      start: 17,    end: 861,   kind: 'css'  },
  { file: 'src/data/mock.js',           start: 875,   end: 1226,  kind: 'mock' },
  { file: 'src/lib/core.jsx',           start: 1231,  end: 2567,  kind: 'jsx'  },
  { file: 'src/pages/dashboard.jsx',    start: 2572,  end: 3597,  kind: 'jsx'  },
  { file: 'src/pages/requestDetail.jsx',start: 3602,  end: 5932,  kind: 'jsx'  },
  { file: 'src/pages/stockClearing.jsx',start: 5937,  end: 6981,  kind: 'jsx'  },
  { file: 'src/pages/people.jsx',       start: 6986,  end: 7482,  kind: 'jsx'  },
  { file: 'src/pages/inboxInsights.jsx',start: 7487,  end: 9137,  kind: 'jsx'  },
  { file: 'src/pages/adminSettings.jsx',start: 9142,  end: 11901, kind: 'jsx'  },
  { file: 'src/shell/chrome.jsx',       start: 11906, end: 12578, kind: 'jsx'  },
  { file: 'src/cloud/binSync.js',       start: 12579, end: 12940, kind: 'js'   },
  { file: 'src/shell/app.jsx',          start: 12941, end: 13467, kind: 'jsx'  },
];
// บรรทัด 13468 (ReactDOM.createRoot(...).render(<App />)) ถูกแทนด้วย src/main.jsx

// transform เดียวของทั้งระบบ: หัว IIFE ของ mock (window.MOCK → const MOCK + export)
const MOCK_ORIG_FIRST = 'window.MOCK = (() => {';
const MOCK_NEW_FIRST = 'const MOCK = (() => {';

// จับ top-level declaration ที่ column 0 เท่านั้น (เนื้อ block อยู่ column 0 ทั้งหมด)
const DECL_RE = /^(?:async\s+)?(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/;

const readSourceLines = () => {
  const raw = fs.readFileSync(SOURCE, 'utf8');
  if (raw.includes('\r')) throw new Error('original/index.html contains CR characters — expected LF only');
  return raw.split('\n');
};

const sliceBody = (lines, entry) => lines.slice(entry.start - 1, entry.end).join('\n');

const transformBody = (entry, body) => {
  if (entry.kind !== 'mock') return body;
  if (!body.startsWith(MOCK_ORIG_FIRST)) throw new Error(`mock.js: expected first line "${MOCK_ORIG_FIRST}"`);
  return MOCK_NEW_FIRST + body.slice(MOCK_ORIG_FIRST.length);
};

const untransformBody = (entry, body) => {
  if (entry.kind !== 'mock') return body;
  if (!body.startsWith(MOCK_NEW_FIRST)) throw new Error(`mock.js: expected transformed first line "${MOCK_NEW_FIRST}"`);
  return MOCK_ORIG_FIRST + body.slice(MOCK_NEW_FIRST.length);
};

const scanSymbols = (body) => {
  const names = [];
  for (const line of body.split('\n')) {
    const m = DECL_RE.exec(line);
    if (m) names.push(m[1]);
  }
  return names;
};

// อ่าน import lines เดิมใน header region (ถ้าไฟล์เคย generate แล้ว) เพื่อคงผลของ gen-imports ไว้
const readExistingImports = (filePath) => {
  if (!fs.existsSync(filePath)) return null;
  const content = fs.readFileSync(filePath, 'utf8');
  const hdrEnd = content.indexOf('\n' + HDR_END + '\n');
  const hdrStart = content.indexOf(HDR_START + '\n');
  if (hdrStart !== 0 || hdrEnd === -1) return null;
  return content.slice(HDR_START.length + 1, hdrEnd).split('\n').filter(l => l.trim() !== '');
};

const buildModule = (entry, body, existingImports) => {
  const symbols = scanSymbols(body);
  if (symbols.length === 0) throw new Error(`${entry.file}: no top-level symbols found`);
  const imports = existingImports && existingImports.length
    ? existingImports
    : [`import React from 'react';`];
  const extras = entry.kind === 'mock' ? ['window.MOCK = MOCK; // คงพฤติกรรมเดิม — โค้ดบางจุดอ้าง window.MOCK'] : [];
  return [
    HDR_START,
    ...imports,
    HDR_END,
    body,
    EXP_START,
    ...extras,
    `export { ${symbols.join(', ')} };`,
    EXP_END,
    '',
  ].join('\n');
};

// ดึง body ออกจากไฟล์ที่ generate แล้ว (ระหว่าง HDR_END กับ EXP_START)
export const extractBodyFromModule = (content, file) => {
  const endMark = '\n' + HDR_END + '\n';
  const expMark = '\n' + EXP_START + '\n';
  const i = content.indexOf(endMark);
  const j = content.indexOf(expMark);
  if (i === -1 || j === -1 || j < i) throw new Error(`${file}: missing auto-generated markers`);
  return content.slice(i + endMark.length, j);
};

const run = () => {
  const lines = readSourceLines();
  for (const entry of MANIFEST) {
    const target = path.join(ROOT, entry.file);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    const body = transformBody(entry, sliceBody(lines, entry));
    if (entry.kind === 'css') {
      fs.writeFileSync(target, body + '\n');
    } else {
      const existing = readExistingImports(target);
      fs.writeFileSync(target, buildModule(entry, body, existing));
    }
    console.log(`✓ ${entry.file}  (lines ${entry.start}–${entry.end}, ${entry.end - entry.start + 1} lines)`);
  }
  console.log('\nExtraction complete.');
};

const verify = () => {
  const lines = readSourceLines();
  let failed = 0;
  for (const entry of MANIFEST) {
    const target = path.join(ROOT, entry.file);
    const expected = sliceBody(lines, entry);
    let actual;
    try {
      const content = fs.readFileSync(target, 'utf8');
      actual = entry.kind === 'css'
        ? content.replace(/\n$/, '')
        : untransformBody(entry, extractBodyFromModule(content, entry.file));
    } catch (e) {
      console.error(`✗ ${entry.file}: ${e.message}`);
      failed++;
      continue;
    }
    if (actual === expected) {
      console.log(`✓ ${entry.file}: byte-identical (${expected.length.toLocaleString()} bytes)`);
    } else {
      failed++;
      const a = actual.split('\n'), b = expected.split('\n');
      let k = 0;
      while (k < Math.min(a.length, b.length) && a[k] === b[k]) k++;
      console.error(`✗ ${entry.file}: DIFFERS at body line ${k + 1} (source line ${entry.start + k})`);
      console.error(`    expected: ${JSON.stringify((b[k] ?? '<EOF>').slice(0, 120))}`);
      console.error(`    actual:   ${JSON.stringify((a[k] ?? '<EOF>').slice(0, 120))}`);
    }
  }
  if (failed) {
    console.error(`\n${failed} module(s) FAILED verification.`);
    process.exit(1);
  }
  console.log('\nAll modules byte-identical to source. ✔');
};

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  if (process.argv.includes('--verify')) verify();
  else run();
}
